Config = {}

-- settings
Config.Difficulty = 1000 -- use -1 for testing
Config.ReelSpeed = 0.0125
Config.Debug = false

-- fishing baits
Config.Baits = {
    "p_baitBread01x",
    "p_baitCorn01x",
    "p_baitCheese01x",
    "p_baitWorm01x",
    "p_baitCricket01x",
    "p_crawdad01x",
    "p_finishedragonfly01x",
    "p_FinisdFishlure01x",
    "p_finishdcrawd01x",
    "p_finishedragonflylegendary01x",
    "p_finisdfishlurelegendary01x",
    "p_finishdcrawdlegendary01x",
    "p_lgoc_spinner_v4",
    "p_lgoc_spinner_v6",
}

-- bait to catch fish
Config.BaitsPerFish = {
    ["p_baitBread01x"] = {
        "A_C_FISHBLUEGIL_01_MS",
        "A_C_FISHBLUEGIL_01_SM",
        "A_C_FISHPERCH_01_MS",
        "A_C_FISHPERCH_01_SM",
        "A_C_FISHBULLHEADCAT_01_MS",
        "A_C_FISHBULLHEADCAT_01_SM",
        "A_C_FISHRAINBOWTROUT_01_MS",
        "A_C_FISHLARGEMOUTHBASS_01_MS",
        "A_C_FISHREDFINPICKEREL_01_MS",
        "A_C_FISHREDFINPICKEREL_01_SM",
    },
    ["p_baitCorn01x"] = {
        "A_C_FISHBLUEGIL_01_MS",
        "A_C_FISHBLUEGIL_01_SM",
        "A_C_FISHPERCH_01_MS",
        "A_C_FISHPERCH_01_SM",
        "A_C_FISHBULLHEADCAT_01_MS",
        "A_C_FISHBULLHEADCAT_01_SM",
        "A_C_FISHRAINBOWTROUT_01_MS",
        "A_C_FISHLARGEMOUTHBASS_01_MS",
        "A_C_FISHREDFINPICKEREL_01_MS",
        "A_C_FISHREDFINPICKEREL_01_SM",
    },
    ["p_baitCheese01x"] = {
        "A_C_FISHBLUEGIL_01_MS",
        "A_C_FISHBLUEGIL_01_SM",
        "A_C_FISHPERCH_01_MS",
        "A_C_FISHPERCH_01_SM",
        "A_C_FISHBULLHEADCAT_01_MS",
        "A_C_FISHBULLHEADCAT_01_SM",
        "A_C_FISHRAINBOWTROUT_01_MS",
        "A_C_FISHLARGEMOUTHBASS_01_MS",
        "A_C_FISHREDFINPICKEREL_01_MS",
        "A_C_FISHREDFINPICKEREL_01_SM",
    },
    ["p_baitCricket01x"] = {
        "A_C_FISHBLUEGIL_01_MS",
        "A_C_FISHBLUEGIL_01_SM",
        "A_C_FISHLAKESTURGEON_01_LG",
        "A_C_FISHLARGEMOUTHBASS_01_LG",
        "A_C_FISHLARGEMOUTHBASS_01_MS",
        "A_C_FISHMUSKIE_01_LG",
        "A_C_FISHPERCH_01_MS",
        "A_C_FISHPERCH_01_SM",
        "A_C_FISHRAINBOWTROUT_01_LG",
        "A_C_FISHRAINBOWTROUT_01_MS",
        "A_C_FISHREDFINPICKEREL_01_MS",
        "A_C_FISHREDFINPICKEREL_01_SM",
        "A_C_FISHSMALLMOUTHBASS_01_LG",
    },
    ["p_baitWorm01x"] = {
        "A_C_FISHBLUEGIL_01_MS",
        "A_C_FISHBLUEGIL_01_SM",
        "A_C_FISHCHAINPICKEREL_01_MS",
        "A_C_FISHCHAINPICKEREL_01_SM",
        "A_C_FISHLAKESTURGEON_01_LG",
        "A_C_FISHLARGEMOUTHBASS_01_LG",
        "A_C_FISHLARGEMOUTHBASS_01_MS",
        "A_C_FISHPERCH_01_MS",
        "A_C_FISHPERCH_01_SM",
        "A_C_FISHRAINBOWTROUT_01_MS",
        "A_C_FISHREDFINPICKEREL_01_MS",
        "A_C_FISHREDFINPICKEREL_01_SM",
        "A_C_FISHROCKBASS_01_MS",
        "A_C_FISHSALMONSOCKEYE_01_ML",
        "A_C_FISHSALMONSOCKEYE_01_MS",
        "A_C_FISHSMALLMOUTHBASS_01_MS",
    },
    ["p_crawdad01x"] = {
        "A_C_FISHBLUEGIL_01_MS",
        "A_C_FISHBLUEGIL_01_SM",
        "A_C_FISHMUSKIE_01_LG",
        "A_C_FISHPERCH_01_MS",
        "A_C_FISHPERCH_01_SM",
        "A_C_FISHREDFINPICKEREL_01_MS",
        "A_C_FISHREDFINPICKEREL_01_SM",
    },
    ["p_finishedragonfly01x"] = {
        "A_C_FISHBLUEGIL_01_MS",
        "A_C_FISHBLUEGIL_01_SM",
        "A_C_FISHBULLHEADCAT_01_MS",
        "A_C_FISHBULLHEADCAT_01_SM",
        "A_C_FISHLAKESTURGEON_01_LG",
        "A_C_FISHNORTHERNPIKE_01_LG",
        "A_C_FISHPERCH_01_MS",
        "A_C_FISHPERCH_01_SM",
        "A_C_FISHREDFINPICKEREL_01_MS",
        "A_C_FISHREDFINPICKEREL_01_SM",
        "A_C_FISHSALMONSOCKEYE_01_LG",
        "A_C_FISHSALMONSOCKEYE_01_ML",
        "A_C_FISHSALMONSOCKEYE_01_MS",
        "A_C_FISHSMALLMOUTHBASS_01_MS",
    },
    ["p_FinisdFishlure01x"] = {
        "A_C_FISHBLUEGIL_01_MS",
        "A_C_FISHBLUEGIL_01_SM",
        "A_C_FISHBULLHEADCAT_01_MS",
        "A_C_FISHBULLHEADCAT_01_SM",
        "A_C_FISHLAKESTURGEON_01_LG",
        "A_C_FISHLONGNOSEGAR_01_LG",
        "A_C_FISHNORTHERNPIKE_01_LG",
        "A_C_FISHPERCH_01_MS",
        "A_C_FISHPERCH_01_SM",
        "A_C_FISHREDFINPICKEREL_01_MS",
        "A_C_FISHREDFINPICKEREL_01_SM",
        "A_C_FISHSALMONSOCKEYE_01_LG",
        "A_C_FISHSALMONSOCKEYE_01_ML",
        "A_C_FISHSALMONSOCKEYE_01_MS",
        "A_C_FISHSMALLMOUTHBASS_01_MS",
    },
    ["p_finishdcrawd01x"] = {
        "A_C_FISHBLUEGIL_01_MS",
        "A_C_FISHBLUEGIL_01_SM",
        "A_C_FISHBULLHEADCAT_01_MS",
        "A_C_FISHBULLHEADCAT_01_SM",
        "A_C_FISHCHAINPICKEREL_01_SM",
        "A_C_FISHLAKESTURGEON_01_LG",
        "A_C_FISHLONGNOSEGAR_01_LG",
        "A_C_FISHNORTHERNPIKE_01_LG",
        "A_C_FISHPERCH_01_MS",
        "A_C_FISHPERCH_01_SM",
        "A_C_FISHREDFINPICKEREL_01_MS",
        "A_C_FISHREDFINPICKEREL_01_SM",
        "A_C_FISHSALMONSOCKEYE_01_LG",
        "A_C_FISHSALMONSOCKEYE_01_ML",
        "A_C_FISHSALMONSOCKEYE_01_MS",
        "A_C_FISHSMALLMOUTHBASS_01_MS",
    },
    ["p_finishedragonflylegendary01x"] = {
        "A_C_FISHBLUEGIL_01_MS",
        "A_C_FISHBLUEGIL_01_SM",
        "A_C_FISHBULLHEADCAT_01_MS",
        "A_C_FISHBULLHEADCAT_01_SM",
        "A_C_FISHCHAINPICKEREL_01_MS",
        "A_C_FISHCHAINPICKEREL_01_SM",
        "A_C_FISHCHANNELCATFISH_01_LG",
        "A_C_FISHCHANNELCATFISH_01_XL",
        "A_C_FISHLAKESTURGEON_01_LG",
        "A_C_FISHNORTHERNPIKE_01_LG",
        "A_C_FISHLONGNOSEGAR_01_LG",
        "A_C_FISHPERCH_01_MS",
        "A_C_FISHPERCH_01_SM",
        "A_C_FISHREDFINPICKEREL_01_MS",
        "A_C_FISHREDFINPICKEREL_01_SM",
        "A_C_FISHSALMONSOCKEYE_01_LG",
        "A_C_FISHSALMONSOCKEYE_01_ML",
        "A_C_FISHSALMONSOCKEYE_01_MS",
        "A_C_FISHSMALLMOUTHBASS_01_MS",
    },
    ["p_finisdfishlurelegendary01x"] = {
        "A_C_FISHBLUEGIL_01_MS",
        "A_C_FISHBULLHEADCAT_01_MS",
        "A_C_FISHCHAINPICKEREL_01_MS",
        "A_C_FISHCHANNELCATFISH_01_LG",
        "A_C_FISHCHANNELCATFISH_01_XL",
        "A_C_FISHLAKESTURGEON_01_LG",
        "A_C_FISHLONGNOSEGAR_01_LG",
        "A_C_FISHNORTHERNPIKE_01_LG",
        "A_C_FISHPERCH_01_MS",
        "A_C_FISHREDFINPICKEREL_01_MS",
        "A_C_FISHSALMONSOCKEYE_01_LG",
        "A_C_FISHSALMONSOCKEYE_01_ML",
        "A_C_FISHSALMONSOCKEYE_01_MS",
        "A_C_FISHSMALLMOUTHBASS_01_LG",
        "A_C_FISHSMALLMOUTHBASS_01_MS",
    },
    ["p_finishdcrawdlegendary01x"] = {
        "A_C_FISHBLUEGIL_01_MS",
        "A_C_FISHBULLHEADCAT_01_MS",
        "A_C_FISHCHAINPICKEREL_01_MS",
        "A_C_FISHCHANNELCATFISH_01_LG",
        "A_C_FISHCHANNELCATFISH_01_XL",
        "A_C_FISHLAKESTURGEON_01_LG",
        "A_C_FISHLONGNOSEGAR_01_LG",
        "A_C_FISHNORTHERNPIKE_01_LG",
        "A_C_FISHPERCH_01_MS",
        "A_C_FISHREDFINPICKEREL_01_MS",
        "A_C_FISHSALMONSOCKEYE_01_LG",
        "A_C_FISHSALMONSOCKEYE_01_ML",
        "A_C_FISHSALMONSOCKEYE_01_MS",
        "A_C_FISHSMALLMOUTHBASS_01_LG",
        "A_C_FISHSMALLMOUTHBASS_01_MS",
    },
    ["p_lgoc_spinner_v4"] = {
        "A_C_FISHBLUEGIL_01_MS",
        "A_C_FISHBLUEGIL_01_SM",
        "A_C_FISHBULLHEADCAT_01_SM",
        "A_C_FISHCHAINPICKEREL_01_MS",
        "A_C_FISHCHAINPICKEREL_01_SM",
        "A_C_FISHLARGEMOUTHBASS_01_LG",
        "A_C_FISHLARGEMOUTHBASS_01_MS",
        "A_C_FISHLONGNOSEGAR_01_LG",
        "A_C_FISHNORTHERNPIKE_01_LG",
        "A_C_FISHPERCH_01_MS",
        "A_C_FISHPERCH_01_SM",
        "A_C_FISHREDFINPICKEREL_01_MS",
        "A_C_FISHREDFINPICKEREL_01_SM",
        "A_C_FISHROCKBASS_01_MS",
        "A_C_FISHROCKBASS_01_SM",
        "A_C_FISHSALMONSOCKEYE_01_LG",
        "A_C_FISHSALMONSOCKEYE_01_ML",
        "A_C_FISHSALMONSOCKEYE_01_MS",
        "A_C_FISHSMALLMOUTHBASS_01_LG",
        "A_C_FISHSMALLMOUTHBASS_01_MS",
    },
    ["p_lgoc_spinner_v6"] = {
        "A_C_FISHBLUEGIL_01_MS",
        "A_C_FISHBLUEGIL_01_SM",
        "A_C_FISHBULLHEADCAT_01_MS",
        "A_C_FISHBULLHEADCAT_01_SM",
        "A_C_FISHCHAINPICKEREL_01_MS",
        "A_C_FISHCHAINPICKEREL_01_SM",
        "A_C_FISHLARGEMOUTHBASS_01_LG",
        "A_C_FISHLARGEMOUTHBASS_01_MS",
        "A_C_FISHLONGNOSEGAR_01_LG",
        "A_C_FISHNORTHERNPIKE_01_LG",
        "A_C_FISHPERCH_01_MS",
        "A_C_FISHPERCH_01_SM",
        "A_C_FISHREDFINPICKEREL_01_MS",
        "A_C_FISHREDFINPICKEREL_01_SM",
        "A_C_FISHROCKBASS_01_MS",
        "A_C_FISHROCKBASS_01_SM",
        "A_C_FISHSALMONSOCKEYE_01_LG",
        "A_C_FISHSALMONSOCKEYE_01_ML",
        "A_C_FISHSALMONSOCKEYE_01_MS",
        "A_C_FISHSMALLMOUTHBASS_01_LG",
        "A_C_FISHSMALLMOUTHBASS_01_MS",
    }
}

-- fish data
Config.fishData = {
    A_C_FISHBLUEGIL_01_MS        = {"Crapet arlequin","PROVISION_FISH_BLUEGILL","PROVISION_BLUEGILL_DESC"},
    A_C_FISHBLUEGIL_01_SM        = {"Petit Crapet arlequin","PROVISION_FISH_BLUEGILL","PROVISION_BLUEGILL_DESC"},
    A_C_FISHBULLHEADCAT_01_MS    = {"Poisson-chat","PROVISION_FISH_BULLHEAD_CATFISH","PROVISION_BLUEGILL_DESC"},
    A_C_FISHBULLHEADCAT_01_SM    = {"Petit Poisson-chat","PROVISION_FISH_BULLHEAD_CATFISH","PROVISION_BLUEGILL_DESC"},
    A_C_FISHCHAINPICKEREL_01_MS  = {"Brochet maillé","PROVISION_FISH_CHAIN_PICKEREL","PROVISION_CHNPKRL_DESC"},
    A_C_FISHCHAINPICKEREL_01_SM  = {"Petit Brochet maillé","PROVISION_FISH_CHAIN_PICKEREL","PROVISION_CHNPKRL_DESC"},
    A_C_FISHCHANNELCATFISH_01_LG = {"Gros Barbue de rivière","PROVISION_FISH_CHANNEL_CATFISH","PROVISION_CHNCATFSH_DESC"},
    A_C_FISHCHANNELCATFISH_01_XL = {"Très gros Barbue de rivière","PROVISION_FISH_CHANNEL_CATFISH","PROVISION_CHNCATFSH_DESC"},
    A_C_FISHLAKESTURGEON_01_LG   = {"Gros Esturgeon jaune","PROVISION_FISH_LAKE_STURGEON","PROVISION_LKSTURG_DESC"},
    A_C_FISHLARGEMOUTHBASS_01_LG = {"Gros Achigan à grande bouche","PROVISION_FISH_LARGEMOUTH_BASS","PROVISION_LRGMTHBASS_DESC"},
    A_C_FISHLARGEMOUTHBASS_01_MS = {"Achigan à grande bouche","PROVISION_FISH_LARGEMOUTH_BASS","PROVISION_LRGMTHBASS_DESC"},
    A_C_FISHLONGNOSEGAR_01_LG    = {"Gros Lépisosté osseux","PROVISION_FISH_LONGNOSE_GAR","PROVISION_LNGNOSEGAR_DESC"},
    A_C_FISHMUSKIE_01_LG         = {"Gros Maskinongé","PROVISION_FISH_MUSKIE","PROVISION_MUSKIE_DESC"},
    A_C_FISHNORTHERNPIKE_01_LG   = {"Grand Brochet","PROVISION_FISH_NORTHERN_PIKE","PROVISION_NPIKE_DESC"},
    A_C_FISHPERCH_01_MS          = {"Perche","PROVISION_FISH_PERCH","PROVISION_PERCH_DESC"},
    A_C_FISHPERCH_01_SM          = {"Petite Perche","PROVISION_FISH_PERCH","PROVISION_PERCH_DESC"},
    A_C_FISHRAINBOWTROUT_01_LG   = {"Grosse Truite arc-en-ciel","PROVISION_FISH_STEELHEAD_TROUT","PROVISION_FISH_STHDTROUT_DESC"},
    A_C_FISHRAINBOWTROUT_01_MS   = {"Truite arc-en-ciel","PROVISION_FISH_STEELHEAD_TROUT","PROVISION_FISH_STHDTROUT_DESC"},
    A_C_FISHREDFINPICKEREL_01_MS = {"Brochet rouge","PROVISION_FISH_REDFIN_PICKEREL","PROVISION_RDFNPCKREL_DESC"},
    A_C_FISHREDFINPICKEREL_01_SM = {"Petit Brochet rouge","PROVISION_FISH_REDFIN_PICKEREL","PROVISION_RDFNPCKREL_DESC"},
    A_C_FISHROCKBASS_01_MS       = {"Crapet de roche","PROVISION_FISH_ROCK_BASS","PROVISION_ROCKBASS_DESC"},
    A_C_FISHROCKBASS_01_SM       = {"Petit Crapet de roche","PROVISION_FISH_ROCK_BASS","PROVISION_ROCKBASS_DESC"},
    A_C_FISHSALMONSOCKEYE_01_LG  = {"Très Gros Saumon rouge","PROVISION_FISH_SOCKEYE_SALMON_LEGENDARY","PROVISION_SCKEYESAL_DESC"},
    A_C_FISHSALMONSOCKEYE_01_ML  = {"Gros Saumon rouge","PROVISION_FISH_SOCKEYE_SALMON","PROVISION_SCKEYESAL_DESC"},
    A_C_FISHSALMONSOCKEYE_01_MS  = {"Saumon rouge","PROVISION_FISH_SOCKEYE_SALMON","PROVISION_SCKEYESAL_DESC"},
    A_C_FISHSMALLMOUTHBASS_01_LG = {"Gros Achigan à petite bouche","PROVISION_FISH_SMALLMOUTH_BASS","PROVISION_SMLMTHBASS_DESC"},
    A_C_FISHSMALLMOUTHBASS_01_MS = {"Achigan à petite bouche","PROVISION_FISH_SMALLMOUTH_BASS","PROVISION_SMLMTHBASS_DESC"},
}

Config.LangueEN = {
    error = {
            you_need_use_your_fishing_rod_first = 'Vous devez avoir votre canne en main.',
    },
    success = {
            var = 'text goes here',
    },
    primary = {
            you_got_fish_name = 'Vous avez eu un %{fish_name}',
    },
    menu = {
            var = 'text goes here',
    },
    commands = {
            var = 'text goes here',
    },
    progressbar = {
            var = 'text goes here',
    },
    text = {
        ready_to_fish = 'Prêt à pêcher!',
        fishing = 'Pêcher',
        get_the_fish = 'Prenez le poisson !',
        name = 'Nom',
        weight = 'Poids',
        prepare_fishing_rod = 'Préparer le lancer',
        cast_fishing_rod = 'Lancer la canne',
        hook = 'Hameçon',
        reset_cast = 'Relancer',
        reel_lure = 'Mouliner',
        reel_in = 'Mouliner',
        keep_fish = 'Garder le poisson',
        throw_fish = 'Relâcher le poisson',
    }
}
