Config = {}

Config.MaxWeight = 45.0 -- kg



Config.Crafting = {
    ["bandage"] = {
        items = {
            "empty","empty","empty",
            "cotton,3","purealcohol","empty",
            "empty","empty","empty"
        } ,
        requireJob = { "doctor" },
    },

    ["mbandage"] = {
        items = {
            "empty","empty","empty",
            "cotton,3","purealcohol,2","ginseng",
            "empty","empty","empty"
        },
        requireId = "cooking",
        requireJob = { "doctor" },
    },

    -------- cooking
    --
    --

    ["bread"] = {
        items = {
            "empty","flour","empty",
            "empty","water","empty",
            "empty","empty","empty"
        },
        requireId = "cooking",
    },
}

Config.Items = {
    ["water"] = {
        label = "Eau",
        description = "De l'eau",
        weight = 0.1,
        canBeDropped = true,
        canBeUsed = true,
        limit = 200,
        imgsrc = "items/water.png",
        type = "item_standard"
    },
    ["bread"] = {
        label = "Pain",
        description = "Du bon pain",
        weight = 0.1,
        canBeDropped = true,
        canBeUsed = true,
        limit = 200,
        imgsrc = "items/cooked_bread.png",
        type = "item_standard"
    },
    ["bandage"] = {
        label = "Bandage",
        description = "Utile pour stopper un saignement",
        weight = 0.1,
        canBeDropped = true,
        canBeUsed = true,
        limit = 100,
        imgsrc = "items/bandage.png",
        type = "item_standard"
    },
    ["WEAPON_REVOLVER_CATTLEMAN"] = {
        label = "Colt 1873",
        description = "L'outil de survie dans l'Ouest sauvage",
        weight = 10,
        canBeDropped = true,
                weaponHash = GetHashKey("WEAPON_REVOLVER_CATTLEMAN"),
        imgsrc = "items/WEAPON_REVOLVER_CATTLEMAN.png",
        type = "item_weapon"
    },
    ["WEAPON_REVOLVER_DOUBLEACTION"] = {
        label = "1873 Chamelot-Delvigne",
        description = "Un bijou technologique",
        weight = 10,
        canBeDropped = true,
                weaponHash = GetHashKey("WEAPON_REVOLVER_DOUBLEACTION"),
        imgsrc = "items/WEAPON_REVOLVER_DOUBLEACTION.png",
        type = "item_weapon"
    },
    ["WEAPON_REVOLVER_NAVY"] = {
        label = "Colt 1851 Navy",
        description = "L'arme favorite des corps d'armées",
        weight = 10,
        canBeDropped = true,
                weaponHash = GetHashKey("WEAPON_REVOLVER_NAVY"),
        imgsrc = "items/weapon_revolver_navy.png",
        type = "item_weapon",
    },
    ["WEAPON_REVOLVER_NAVY_CROSSOVER"] = {
        label = "Colt 1851 Navy",
        description = "L'arme favorite d'un vieux briscard",
        weight = 10,
        canBeDropped = true,
                weaponHash = GetHashKey("WEAPON_REVOLVER_NAVY_CROSSOVER"),
        imgsrc = "items/weapon_revolver_navy_crossover.png",
        type = "item_weapon",
    },
    ["WEAPON_PISTOL_VOLCANIC"] = {
        label = "Smith & Wesson 1855",
        description = "Une carabine de poche",
        weight = 10,
        canBeDropped = true,
                weaponHash = GetHashKey("WEAPON_PISTOL_VOLCANIC"),
        imgsrc = "items/WEAPON_PISTOL_VOLCANIC.png",
        type = "item_weapon"
    },
    ["WEAPON_PISTOL_SEMIAUTO"] = {
        label = "SemiAuto",
        description = "SemiAuto",
        weight = 0.5,
        canBeDropped = true,
                weaponHash = GetHashKey("WEAPON_PISTOL_SEMIAUTO"),
        imgsrc = "items/WEAPON_PISTOL_SEMIAUTO.png",
        type = "item_weapon"
    },
    ["WEAPON_PISTOL_MAUSER"] ={
        label = "Mauser",
        description = "Mauser",
        weight = 0.5,
        canBeDropped = true,
                weaponHash = GetHashKey("WEAPON_PISTOL_MAUSER"),
        imgsrc = "items/WEAPON_PISTOL_MAUSER.png",
        type = "item_weapon"
    },
    ["WEAPON_PISTOL_M1899"] ={
        label = "M1899",
        description = "M1899",
        weight = 0.5,
        canBeDropped = true,
                weaponHash = GetHashKey("WEAPON_PISTOL_M1899"),
        imgsrc = "items/m1899.png",
        type = "item_weapon"
    },
    ["WEAPON_REVOLVER_LEMAT"] ={
        label = "Lemat Revolver",
        description = "Alliage de précision et puissance",
        weight = 10,
        canBeDropped = true,
                weaponHash = GetHashKey("WEAPON_REVOLVER_LEMAT"),
        imgsrc = "items/WEAPON_REVOLVER_LEMAT.png",
        type = "item_weapon"
    },
    ["WEAPON_REVOLVER_SCHOFIELD"] = {
        label = "Smith & Wesson Model 3",
        description = "Pas de fioriture",
        weight = 10,
        canBeDropped = true,
                weaponHash = GetHashKey("WEAPON_REVOLVER_SCHOFIELD"),
        imgsrc = "items/WEAPON_REVOLVER_SCHOFIELD.png",
        type = "item_weapon"
    },
    --REAPEATERS
    ["WEAPON_REPEATER_CARBINE"] = {
        label = "M1865 Spencer",
        description = "Une belle carabine",
        weight = 23,
        canBeDropped = true,
                weaponHash = GetHashKey("WEAPON_REPEATER_CARBINE"),
        imgsrc = "items/WEAPON_REPEATER_CARBINE.png",
        type = "item_weapon"
    },
    ["WEAPON_REPEATER_EVANS"] = {
        label = "Evans",
        description = "Comment louper sa cible avec autant de cartouche",
        weight = 23,
        canBeDropped = true,
                weaponHash = GetHashKey("WEAPON_REPEATER_EVANS"),
        imgsrc = "items/WEAPON_REPEATER_EVANS.png",
        type = "item_weapon"
    },
    ["WEAPON_REPEATER_HENRY"] = {
        label = "1860 Henry",
        description = "Nommé après son créateur",
        weight = 23,
        canBeDropped = true,
                weaponHash = GetHashKey("WEAPON_REPEATER_HENRY"),
        imgsrc = "items/WEAPON_REPEATER_HENRY.png",
        type = "item_weapon"
    },
    ["WEAPON_REPEATER_WINCHESTER"] = {
        label = "Winchester 1873",
        description = "Célèbre à travers tout le pays",
        weight = 23,
        canBeDropped = true,
                weaponHash = GetHashKey("WEAPON_REPEATER_WINCHESTER"),
        imgsrc = "items/WEAPON_REPEATER_LANCASTER.png",
        type = "item_weapon"
    },
    --RIFLES
    ["WEAPON_RIFLE_VARMINT"] = {
        label = "Varmint",
        description = "Varmint",
        weight = 0.9,
        canBeDropped = true,
                weaponHash = GetHashKey("WEAPON_RIFLE_VARMINT"),
        imgsrc = "items/WEAPON_RIFLE_VARMINT.png",
        type = "item_weapon"
    },
    ["WEAPON_RIFLE_BOLTACTION"] = {
        label = "Bolt action",
        description = "Bolt action",
        weight = 0.9,
        canBeDropped = true,
                weaponHash = GetHashKey("WEAPON_RIFLE_BOLTACTION"),
        imgsrc = "items/WEAPON_RIFLE_BOLTACTION.png",
        type = "item_weapon"
    },
    ["WEAPON_SNIPERRIFLE_CARCANO"] = {
        label = "Carcano",
        description = "Carcano",
        weight = 0.9,
        canBeDropped = true,
                weaponHash = GetHashKey("WEAPON_SNIPERRIFLE_CARCANO"),
        imgsrc = "items/WEAPON_SNIPERRIFLE_CARCANO.png",
        type = "item_weapon"
    },
    ["WEAPON_SNIPERRIFLE_ROLLINGBLOCK"] = {
        label = "Remington Rolling Block",
        description = "Gardez la lunette propre",
        weight = 23,
        canBeDropped = true,
                weaponHash = GetHashKey("WEAPON_SNIPERRIFLE_ROLLINGBLOCK"),
        imgsrc = "items/WEAPON_SNIPERRIFLE_ROLLINGBLOCK.png",
        type = "item_weapon"
    },
    ["WEAPON_RIFLE_SPRINGFIELD"] = {
        label = "Springfield Model 1873",
        description = "L'efficacité",
        weight = 23,
        canBeDropped = true,
                weaponHash = GetHashKey("WEAPON_RIFLE_SPRINGFIELD"),
        imgsrc = "items/WEAPON_RIFLE_SPRINGFIELD.png",
        type = "item_weapon"
    },
    --SHOTGUNS
    ["WEAPON_SHOTGUN_PUMP"] = {
        label = "Pump",
        description = "Pump",
        weight = 0.9,
        canBeDropped = true,
                weaponHash = GetHashKey("WEAPON_SHOTGUN_PUMP"),
        imgsrc = "items/WEAPON_SHOTGUN_PUMP.png",
        type = "item_weapon"
    },
    ["WEAPON_SHOTGUN_REPEATING"] = {
        label = "Repeating shotgun",
        description = "Repeating shotgun",
        weight = 0.9,
        canBeDropped = true,
                weaponHash = GetHashKey("WEAPON_SHOTGUN_REPEATING"),
        imgsrc = "items/WEAPON_SHOTGUN_REPEATING.png",
        type = "item_weapon"
    },
    ["WEAPON_SHOTGUN_DOUBLEBARREL"] = {
        label = "Colt 1883",
        description = "Une vraie arme de gentleman",
        weight = 23,
        canBeDropped = true,
                weaponHash = GetHashKey("WEAPON_SHOTGUN_DOUBLEBARREL"),
        imgsrc = "items/WEAPON_SHOTGUN_DOUBLEBARREL.png",
        type = "item_weapon"
    },
    ["WEAPON_SHOTGUN_SAWEDOFF"] = {
        label = "Colt 1883 Scié",
        description = "Peut scier quelqu'un en deux",
        weight = 10,
        canBeDropped = true,
                weaponHash = GetHashKey("WEAPON_SHOTGUN_SAWEDOFF"),
        imgsrc = "items/WEAPON_SHOTGUN_SAWEDOFF.png",
        type = "item_weapon"
    },
    ["WEAPON_SHOTGUN_SEMIAUTO"] = {
        label = "Semiauto Shotgun",
        description = "Semiauto Shotgun",
        weight = 0.9,
        canBeDropped = true,
                weaponHash = GetHashKey("WEAPON_SHOTGUN_SEMIAUTO"),
        imgsrc = "items/WEAPON_SHOTGUN_SEMIAUTO.png",
        type = "item_weapon"
    },
    --MELEE WEAPONS
    ["WEAPON_MELEE_HATCHET_HUNTER"] =
	{
		label = "Hunter Hatchet",
		description = "Hunting Wild Animals",
		weight = 1.0,
		canBeDropped = true,
		requireLvl = 1,
		weaponHash = GetHashKey("WEAPON_MELEE_HATCHET_HUNTER"),
		  imgsrc = "items/WEAPON_MELEE_HATCHET_HUNTER.png",
		type = "item_weapon"
	},
    ["WEAPON_MELEE_HATCHET_DOUBLE_BIT"] =
	{
		label = "Double Bit Hatchet",
		description = "Hunting Wild Animals",
		weight = 1.0,
		canBeDropped = true,
		requireLvl = 1,
		weaponHash = GetHashKey("WEAPON_MELEE_HATCHET_DOUBLE_BIT"),
		imgsrc = "items/WEAPON_MELEE_HATCHET_DOUBLE_BIT.png",
		type = "item_weapon"
	},
	["WEAPON_MELEE_CLEAVER"] =
	{
		label = "Hachoir",
		description = "Chaque vrai boucher sait l'affûter",
		weight = 3,
		canBeDropped = true,
		requireLvl = 1,
		weaponHash = GetHashKey("WEAPON_MELEE_CLEAVER"),
		  imgsrc = "items/WEAPON_MELEE_CLEAVER.png",
		type = "item_weapon"
	},
    ["WEAPON_MELEE_KNIFE_JAWBONE"] =
	{
		label = "Jawbone Knife",
		description = "A symbol of designer tastes",
		weight = 1.0,
		canBeDropped = true,
		requireLvl = 1,
		weaponHash = GetHashKey("WEAPON_MELEE_KNIFE_JAWBONE"),
		  imgsrc = "items/WEAPON_MELEE_KNIFE_JAWBONE.png",
		type = "item_weapon"
	},
    ["WEAPON_MELEE_KNIFE_TRADER"] =
	{
		label = "Trader Knife",
		description = "A symbol of designer tastes",
		weight = 1.0,
		canBeDropped = true,
		requireLvl = 1,
		weaponHash = GetHashKey("WEAPON_MELEE_KNIFE_TRADER"),
		  imgsrc = "items/WEAPON_MELEE_KNIFE_TRADER.png",
		type = "item_weapon"
	},
    ["WEAPON_MELEE_KNIFE_HORROR"] =
	{
		label = "Horror Knife",
		description = "A symbol of designer tastes",
		weight = 1.0,
		canBeDropped = true,
		requireLvl = 1,
		weaponHash = GetHashKey("WEAPON_MELEE_KNIFE_HORROR"),
		  imgsrc = "items/WEAPON_MELEE_KNIFE_HORROR.png",
		type = "item_weapon"
	},
    ["WEAPON_MELEE_KNIFE_RUSTIC"] =
	{
		label = "Rustic Knife",
		description = "A symbol of designer tastes",
		weight = 1.0,
		canBeDropped = true,
		requireLvl = 1,
		weaponHash = GetHashKey("WEAPON_MELEE_KNIFE_RUSTIC"),
		  imgsrc = "items/WEAPON_MELEE_KNIFE_RUSTIC.png",
		type = "item_weapon"
	},
    ["WEAPON_MELEE_MACHETE"] =
    {
        label = "Machette",
        description = "Peut découper de large pièce de viande",
        weight = 8,
        canBeDropped = true,
        requireLvl = 1,
        weaponHash = GetHashKey("WEAPON_MELEE_MACHETE"),
          imgsrc = "items/WEAPON_MELEE_MACHETE.png",
        type = "item_weapon"
    },
    ["WEAPON_MELEE_MACHETE_HORROR"] =
    {
        label = "Horror Machete",
        description = "A horror machete",
        weight = 1,
        canBeDropped = true,
        requireLvl = 1,
        weaponHash = GetHashKey("WEAPON_MELEE_MACHETE_HORROR"),
          imgsrc = "items/WEAPON_MELEE_MACHETE_HORROR.png",
        type = "item_weapon"
    },
    ["WEAPON_MELEE_MACHETE_COLLECTOR"] =
    {
        label = "Collector Machete",
        description = "A collector machete",
        weight = 1,
        canBeDropped = true,
        requireLvl = 1,
        weaponHash = GetHashKey("WEAPON_MELEE_MACHETE_COLLECTOR"),
        imgsrc = "items/WEAPON_MELEE_MACHETE_COLLECTOR.png",
        type = "item_weapon"
    },
    ["WEAPON_FISHINGROD"] = {
        label = "Fishing Rod",
        description = "Fishing Rod",
        weight = 0.5,
        canBeDropped = true,
        weaponHash = GetHashKey("WEAPON_FISHINGROD"),
        imgsrc = "items/weapon_fishingrod.png",
        type = "item_weapon"
    },
    ["WEAPON_MELEE_KNIFE"] = {
        label = "Couteau de chasse",
        description = "Utile pour dépecer vos proies",
        weight = 1,
        canBeDropped = true,
        weaponHash = GetHashKey("WEAPON_MELEE_KNIFE"),
        imgsrc = "items/WEAPON_MELEE_KNIFE.png",
        type = "item_weapon"
    },
    ["WEAPON_MELEE_LANTERN"] = {
        label = "Lantern",
        description = "Lantern",
        weight = 0.5,
        canBeDropped = true,
        weaponHash = GetHashKey("WEAPON_MELEE_LANTERN"),
        imgsrc = "items/generic_horse_equip_lantern.png",
        type = "item_weapon"
    },
    ["WEAPON_MELEE_TORCH"] = {
        label = "Torch",
        description = "Torch",
        weight = 0.5,
        canBeDropped = true,
                weaponHash = GetHashKey("WEAPON_MELEE_TORCH"),
        imgsrc = "items/WEAPON_MELEE_TORCH.png",
        type = "item_weapon"
    },
    ["WEAPON_LANTERN_ELECTRIC"] = {
        label = "Electric Lantern",
        description = "Electric Lantern",
        weight = 0.5,
        canBeDropped = true,
        weaponHash = GetHashKey("WEAPON_MELEE_LANTERN_ELECTRIC"),
        imgsrc = "items/weapon_melee_electric_lantern.png",
        type = "item_weapon"
    },
    ["WEAPON_BOW"] = {
        label = "Bow",
        description = "Bow",
        weight = 0.25,
        canBeDropped = true,
                weaponHash = GetHashKey("WEAPON_BOW"),
        imgsrc = "items/WEAPON_BOW.png",
        type = "item_weapon"
    },
    ["WEAPON_BOW_IMPROVED"] = {
        label = "Improved Bow",
        description = "Improved Bow",
        weight = 0.25,
        canBeDropped = true,
        weaponHash = GetHashKey("WEAPON_BOW_IMPROVED"),
        imgsrc = "items/T_Bow_01ca.png",
        type = "item_weapon"
    },
    ["WEAPON_LASSO"] = {
        label = "Lasso",
        description = "Lasso",
        weight = 0.25,
        canBeDropped = true,
                weaponHash = GetHashKey("WEAPON_LASSO_REINFORCED"),
        imgsrc = "items/WEAPON_LASSO.png",
        type = "item_weapon"
    },
    ["WEAPON_MELEE_HATCHET"] = {
        label = "Hache",
        description = "Coupe du bois ou autre chose",
        weight = 3,
        canBeDropped = true,
                weaponHash = GetHashKey("WEAPON_MELEE_HATCHET"),
        imgsrc = "items/WEAPON_MELEE_HATCHET.png",
        type = "item_weapon"
    },
    ["WEAPON_THROWN_THROWING_KNIVES"] = {
        label = "Throwing knives",
        description = "Throwing knives",
        weight = 0.5,
        canBeDropped = true,
                weaponHash = GetHashKey("WEAPON_THROWN_THROWING_KNIVES"),
        imgsrc = "items/WEAPON_THROWN_THROWING_KNIVES.png",
        type = "item_weapon"
    },
    ["WEAPON_THROWN_TOMAHAWK"] = {
        label = "Tomahawk",
        description = "Un savoir faire ancestrale",
        weight = 3,
        canBeDropped = true,
                weaponHash = GetHashKey("WEAPON_THROWN_TOMAHAWK"),
        imgsrc = "items/WEAPON_THROWN_TOMAHAWK.png",
        type = "item_weapon"
    },
    ["WEAPON_THROWN_DYNAMITE"] = {
        label = "Dynamite stick",
        description = "Dynamite stick",
        weight = 0.5,
        canBeDropped = true,
                weaponHash = GetHashKey("WEAPON_THROWN_DYNAMITE"),
        imgsrc = "items/WEAPON_THROWN_DYNAMITE.png",
        type = "item_weapon"
    },
    ["WEAPON_THROWN_MOLOTOV"] = {
        label = "Molotov",
        description = "Molotov",
        weight = 0.25,
        canBeDropped = true,
                weaponHash = GetHashKey("WEAPON_THROWN_MOLOTOV"),
        imgsrc = "items/WEAPON_THROWN_MOLOTOV.png",
        type = "item_weapon"
    },
    ["WEAPON_KIT_BINOCULARS"] = {
        label = "Jumelle",
        description = "Binoculars",
        weight = 1,
        canBeDropped = true,
                weaponHash = GetHashKey("WEAPON_KIT_BINOCULARS"),
        imgsrc = "items/WEAPON_KIT_BINOCULARS.png",
        type = "item_weapon"
    },


    -- Custom

    ["pioche"] = {
        label = "Pioche",
        description = "Indispensable pour miner",
        weight = 2,
        canBeDropped = true,
        canBeUsed = true,
        limit = 200,
        imgsrc = "items/pickaxe.png",
        type = "item_standard"
    },
    ["ferbrut"] = {
        label = "Fer brut",
        description = "Minerai de Fer",
        weight = 0.5,
        canBeDropped = true,
        canBeUsed = false,
        limit = 1000,
        imgsrc = "items/ironore.png",
        type = "item_standard"
    },
    ["plombbrut"] = {
        label = "Plomb brut",
        description = "Minerai de Plomb",
        weight = 0.5,
        canBeDropped = true,
        canBeUsed = false,
        limit = 1000,
        imgsrc = "items/metal_ore.png",
        type = "item_standard"
    },
    ["cuivrebrut"] = {
        label = "Cuivre brut",
        description = "Minerai de Cuivre",
        weight = 0.5,
        canBeDropped = true,
        canBeUsed = false,
        limit = 1000,
        imgsrc = "items/copper_ore.png",
        type = "item_standard"
    },
    ["zincbrut"] = {
        label = "Zinc brut",
        description = "Minerai de Zinc",
        weight = 0.5,
        canBeDropped = true,
        canBeUsed = false,
        limit = 1000,
        imgsrc = "items/collector_fossil_pet_wood.png",
        type = "item_standard"
    },
    ["charbon"] = {
        label = "Charbon",
        description = "La base de toute industrie",
        weight = 0.2,
        canBeDropped = true,
        canBeUsed = false,
        limit = 2000,
        imgsrc = "items/rock.png",
        type = "item_standard"
    },
    ["cuivrepepite"] = {
        label = "Pépite de cuivre",
        description = "La base de toute industrie",
        weight = 0.1,
        canBeDropped = true,
        canBeUsed = false,
        limit = 2000,
        imgsrc = "items/pepitecuivre.png",
        type = "item_standard"
    },
    ["plombpepite"] = {
        label = "Pépite de plomb",
        description = "La base de toute industrie",
        weight = 0.1,
        canBeDropped = true,
        canBeUsed = false,
        limit = 2000,
        imgsrc = "items/silverore.png",
        type = "item_standard"
    },
    ["ferpepite"] = {
        label = "Pépite de fer",
        description = "La base de toute industrie",
        weight = 0.1,
        canBeDropped = true,
        canBeUsed = false,
        limit = 2000,
        imgsrc = "items/cannabis.png",
        type = "item_standard"
    },
    ["zincpepite"] = {
        label = "Pépite de zinc",
        description = "La base de toute industrie",
        weight = 0.2,
        canBeDropped = true,
        canBeUsed = false,
        limit = 2000,
        imgsrc = "items/provision_gold_nugget.png",
        type = "item_standard"
    },
    ["souffre"] = {
        label = "Souffre",
        description = "Utile pour fabriquer de la poudre à canon",
        weight = 0.5,
        canBeDropped = true,
        canBeUsed = false,
        limit = 2000,
        imgsrc = "items/collector_fossil_stone.png",
        type = "item_standard"
    },
    ["lingotfer"] = {
        label = "Lingot de fer",
        description = "La base de toute industrie",
        weight = 0.5,
        canBeDropped = true,
        canBeUsed = false,
        limit = 2000,
        imgsrc = "items/provision_goldbar_small.png",
        type = "item_standard"
    },
    ["douille"] = {
        label = "Douille",
        description = "La base de toute industrie",
        weight = 0.2,
        canBeDropped = true,
        canBeUsed = false,
        limit = 2000,
        imgsrc = "items/upgrade_pouch_ammo.png",
        type = "item_standard"
    },
    ["gunpowder"] = {
        label = "Poudre à canon",
        description = "La base de toute industrie",
        weight = 0.2,
        canBeDropped = true,
        canBeUsed = false,
        limit = 2000,
        imgsrc = "items/cocaine.png",
        type = "item_standard"
    },
    ["piecearme"] = {
        label = "Pièce d'arme",
        description = "La base de toute industrie",
        weight = 0.5,
        canBeDropped = true,
        canBeUsed = false,
        limit = 2000,
        imgsrc = "",
        type = "item_standard"
    },


    
    -- CHASSE
    ["graisse"] = {
        label = "Morceau de gras",
        description = "Du bon gras",
        weight = 0.1,
        canBeDropped = true,
        canBeUsed = false,
        limit = 2000,
        imgsrc = "items/generic_animal_fat.png",
        type = "item_standard"
    },
    ["steakreptile"] = {
        label = "Steak de Reptile",
        description = "Pour les plus courageux",
        weight = 0.1,
        canBeDropped = true,
        canBeUsed = false,
        limit = 2000,
        imgsrc = "items/consumable_meat_stringy_cooked.png",
        type = "item_standard"
    },
    ["fish"] = {
        label = "Poisson",
        description = "Poisson frais",
        weight = 0.3,
        canBeDropped = true,
        canBeUsed = false,
        limit = 2000,
        imgsrc = "items/cooked_fish.png",
        type = "item_standard"
    },
    ["cuir"] = {
        label = "Cuir",
        description = "L'animal a trop souffert",
        weight = 0.2,
        canBeDropped = true,
        canBeUsed = false,
        limit = 2000,
        imgsrc = "items/provision_armadillo_skin.png",
        type = "item_standard"
    },

    ---- ORPAILLAGE
    ["pepiteor"] = {
        label = "Petite pépite d'or",
        description = "Une petite pépite grandement convoitée",
        weight = 0.1,
        canBeDropped = true,
        canBeUsed = false,
        limit = 2000,
        imgsrc = "items/goldnugget.png",
        type = "item_standard"
    },
    ["cailloux"] = {
        label = "Dépôt riche en or",
        description = "Peut donner de l'or à une rampe de lavage",
        weight = 1.5,
        canBeDropped = true,
        canBeUsed = false,
        limit = 2000,
        imgsrc = "items/golden_nugget.png",
        type = "item_standard"
    },
    ["batée"] = {
        label = "Bâtée",
        description = "Outil nécessaire à l'orpaillage",
        weight = 1,
        canBeDropped = true,
        canBeUsed = true,
        limit = 2000,
        imgsrc = "items/goldpan.png",
        type = "item_standard"
    },
    ["goldramp"] = {
        label = "Rampe de lavage",
        description = "Utile pour séparer l'or des amas de cailloux",
        weight = 4,
        canBeDropped = true,
        canBeUsed = true,
        limit = 2000,
        imgsrc = "items/workbench.png",
        type = "item_standard"
    },



    --- Contrat
    ["contratvierge"] = {
        label = "Contrat Vierge",
        description = "Le patron signe en premier",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = true,
        limit = 2000,
        imgsrc = "items/assaultplans.png",
        type = "item_standard"
    },
    ["contratsigne"] = {
        label = "Contrat Signe",
        description = "Un justificatif de travail",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = false,
        limit = 1,
        imgsrc = "items/assaultplans.png",
        type = "item_standard"
    },
    ["contratusine"] = {
        label = "Contrat Usine",
        description = "Signez en bas pour commencer à travailler",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = true,
        limit = 2000,
        imgsrc = "items/assaultplans.png",
        type = "item_standard"
    },
    ["contratmineur"] = {
        label = "Contrat Mineur",
        description = "Signez en bas pour commencer à travailler",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = true,
        limit = 2000,
        imgsrc = "items/assaultplans.png",
        type = "item_standard"
    },


    --- CAMP
    ["spit"] = {
      label = "Feu de camp",
      description = "De quoi se chauffer et cuire sa nourriture",
      weight = 1.0,
      canBeDropped = true,
      canBeUsed = true,
      requireLvl = 0,
      limit = 2000,
      imgsrc = "items/kit_camp_simple.png",
      type = "item_standard",
    },
    ["grill"] = {
      label = "Grill",
      description = "De quoi griller sa viande",
      weight = 1.0,
      canBeDropped = true,
      canBeUsed = true,
      requireLvl = 0,
      limit = 2000,
      imgsrc = "items/upgrade_upg_cooking_spit.png",
      type = "item_standard",
    },
    ["cauldron"] = {
      label = "Marmite",
      description = "De quoi préparer divers plats et décoctions",
      weight = 2.0,
      canBeDropped = true,
      canBeUsed = true,
      requireLvl = 0,
      limit = 2000,
      imgsrc = "items/pot.png",
      type = "item_standard",
    },
    ["petitbois"] = {
        label = "Petit Bois",
        description = "Un petit bois",
        weight = 0.1,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/stick.png",
        type = "item_standard",
    },
    ["gourde"] = {
        label = "Gourde",
        description = "Avec ou sans modération, à vous de voir",
        weight = 0.3,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/consumable_cyprus_brandy.png",
        type = "item_standard",
    },
    ----- RECETTE CAMP ---- 
    ["grossteakcuit"] = {
        label = "Gros Steak Cuit",
        description = "Pour les plus gourmands",
        weight = 0.2,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/consumable_meat_prime_beef_cooked.png",
        type = "item_standard",
    },
    ["grossteakcarottesauvage"] = {
        label = "Gros Steak au carottes sauvages",
        description = "Pour les plus gourmands",
        weight = 0.2,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/consumable_prime_beef_thyme_cooked.png",
        type = "item_standard",
    },

    --- VAULT
    ["smallvault"] = {
        label = "Petit Coffre Fort",
        description = "De quoi protéger quelques biens",
        weight = 10,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/smallvault.png",
        type = "item_standard",
    },
    ["mediumvault"] = {
        label = "Coffre Fort",
        description = "De quoi protéger quelques biens",
        weight = 20,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/crate.png",
        type = "item_standard",
    },
    ["largevault"] = {
        label = "Grand Coffre Fort",
        description = "De quoi protéger quelques biens",
        weight = 30,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/provision_role_naturalist_sample_domesticated.png",
        type = "item_standard",
    },

    ------ STABLE ------
    ["createhorse"] = {
        label = "Certificat d'écurie",
        description = "Enregistre le chaval à votre nom",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/generic_official_doc.png",
        type = "item_standard",
    },
    ["transferhorse"] = {
        label = "Certificat",
        description = "Transfert le cheval à celui qui le se signe",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/folder_notes.png",
        type = "item_standard",
    },   
    ["horsereviver"] = {
        label = "Remontant pour cheval",
        description = "De quoi remettre un cheval sur ses pattes",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/consumable_horse_reviver.png",
        type = "item_standard",
    },
    ["horsestimulant"] = {
        label = "Stimulant pour cheval",
        description = "Un puissant stimulant pour cheval",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/consumable_potent_horse_medicine.png",
        type = "item_standard",
    },
    ["horsehaycube"] = {
        label = "Foin",
        description = "Un peu de foin pour votre cheval",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/haycube.png",
        type = "item_standard",
    },
    ["horsemedicine"] = {
        label = "Remède pour cheval",
        description = "Quand votre cheval est mal en point",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/consumable_horse_medicine.png",
        type = "item_standard",
    },
    ["fercheval"] = {
        label = "Fer à cheval",
        description = "Penser à les changer lorsque votre cheval est à bout",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/horseshoe.png",
        type = "item_standard",
    },
    ["brosse"] = {
        label = "Brosse",
        description = "Pour nettoyer votre cheval",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/brush.png",
        type = "item_standard",
    },

    ------ AMMO ----
    ["ammo_arrow"] = {
        label = "Flèche",
        description = "Une flèche, un mort",
        weight = 0.1,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/AMMO_ARROW.png",
        type = "item_ammo",
        ammoType = GetHashKey("AMMO_ARROW"),
    },
    ["ammo_arrow_poison"] = {
        label = "Flèche empoisonnée",
        description = "Une flèche, un mort",
        weight = 0.1,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/ammo_arrow_poison.png",
        type = "item_ammo",
        ammoType = GetHashKey("AMMO_ARROW_POISON"),
    },
    ["ammo_revolver"] = {
        label = "Balles de Revolver",
        description = "Une balle, un mort",
        weight = 0.05,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/AMMO_REVOLVER.png",
        type = "item_ammo",
        ammoType = GetHashKey("AMMO_REVOLVER"),
    },
    ["ammo_pistol"] = {
        label = "Balles de Pistolet",
        description = "Une balle, un mort",
        weight = 0.05,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/AMMO_PISTOL_VOLCANIC.png",
        type = "item_ammo",
        ammoType = GetHashKey("AMMO_PISTOL"),
    },
    ["ammo_repeater"] = {
        label = "Balles de Carabine",
        description = "Une balle, un mort",
        weight = 0.05,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/AMMO_REPEATER.png",
        type = "item_ammo",
        ammoType = GetHashKey("AMMO_REPEATER"),
    },
    ["ammo_rifle"] = {
        label = "Balles de Fusil",
        description = "Une balle, un mort",
        weight = 0.05,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/AMMO_RIFLE.png",
        type = "item_ammo",
        ammoType = GetHashKey("AMMO_RIFLE"),
    },
    ["ammo_shotgun"] = {
        label = "Chevrotine",
        description = "Une balle, un mort",
        weight = 0.05,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/AMMO_SHOTGUN_REPEATING.png",
        type = "item_ammo",
        ammoType = GetHashKey("AMMO_SHOTGUN"),
    },
    ----- Armurier ------
    ["repairkitweapon"] = {
        label = "Kit d'entretien d'arme",
        description = "Remise à neuf de votre machine à tuer",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/generic_skin_revolver.png",
        type = "item_standard",
    },
    ----- DOCTORS ---- 
    ["syringe"] = {
        label = "Seringue de digitaline",
        description = "De quoi remettre quelqu'un d'aplomb",
        weight = 0.1,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/consumable_health_serum.png",
        type = "item_standard",
    },


    ----  FERME ----
    ["ble"] = {
        label = "Blé",
        description = "À ne pas confondre avec l'oseille",
        weight = 0.2,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/wheat.png",
        type = "item_standard",
    },
    ["farine"] = {
        label = "Farine",
        description = "L'or blanc",
        weight = 0.4,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/flour.png",
        type = "item_standard",
    },

    ---- GUM FARMING ---
    ["Watering_Can"] = {
        label = "Sceau",
        description = "L'arroseur arrosé",
        weight = 1.0,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/bucket.png",
        type = "item_standard",
    },
    ["Teapot_Can"] = {
        label = "Arrosoir",
        description = "L'arroseur arrosé",
        weight = 2,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/wateringcan.png",
        type = "item_standard",
    },
    ["Engrais"] = {
        label = "Engrais",
        description = "Indispensable à tout fermier",
        weight = 1.0,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/papryka.png",
        type = "item_standard",
    },
    ["Corn_Seed"] = {
        label = "Graine de Maïs",
        description = "Une petite graine",
        weight = 0.1,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/cornseed.png",
        type = "item_standard",
    },
    ["Potato_Seed"] = {
        label = "Patate germée",
        description = "Une petite patate",
        weight = 0.1,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/potato.png",
        type = "item_standard",
    },
    ["Corn"] = {
        label = "Maïs",
        description = "Du bon Maïs",
        weight = 0.3,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/corn.png",
        type = "item_standard",
    },
    ----- gum ecology ---- 
    ["Wild_Carrot"] = {
        label = "Carotte Sauvage",
        description = "En bouillon ou en soupe",
        weight = 0.1,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/consumable_herb_wild_carrots.png",
        type = "item_standard",
    },
    ----- BETAIL -----
    ["sceaulait"] = {
        label = "Jarre de lait",
        description = "Les os sont solides",
        weight = 3,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/moonshine_pot.png",
        type = "item_standard",
    },
    ["foutrebovin"] = {
        label = "Foutre de bovin",
        description = "Bizarre d'avoir eu l'idée...",
        weight = 0.1,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/flask.png",
        type = "item_standard",
    },
    ["cuirbovin"] = {
        label = "Cuir de Bovin",
        description = "Du cuir solide",
        weight = 0.2,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/provision_iguana_skin.png",
        type = "item_standard",
    },
    ["viandebovine"] = {
        label = "Viande Bovine",
        description = "Destinée au plus fin des palais",
        weight = 0.2,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/provision_meat_big_game.png",
        type = "item_standard",
    },
    ----- telegram
    ["télégramme"] = {
        label = "Télégramme",
        description = "La communication est la clef",
        weight = 0,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/document_cloud_drop_letter.png",
        type = "item_standard",
    },

    ----- pablo ---- 
    ["viandegibier"] = {
        label = "Venaison",
        description = "Viande de gibier",
        weight = 0.1,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/provision_meat_mature_venison.png",
        type = "item_standard",
    },
    ["viande"] = {
        label = "Viande crue",
        description = "Meilleure une fois cuite",
        weight = 0.1,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/provision_meat_prime_beef.png",
        type = "item_standard",
    },
    ["graisseanimal"] = {
        label = "Graisse animale",
        description = "Utile dans un grand nombre de recette",
        weight = 0.1,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/generic_animal_fat.png",
        type = "item_standard",
    },
    ["peau"] = {
        label = "Peau",
        description = "Splendide une fois tannée",
        weight = 0.2,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/provision_pig_skin.png",
        type = "item_standard",
    },
    ["petitefourure"] = {
        label = "Petite fourrure",
        description = "Une petite fourrure idéal pour la confection de chapeaux",
        weight = 0.1,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/provision_rabbit_pelt.png",
        type = "item_standard",
    },
    ["viandepetitmamifere"] = {
        label = "Viande de petit gibier",
        description = "Meilleur une fois cuit",
        weight = 0.1,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/provision_meat_exotic_bird.png",
        type = "item_standard",
    },
    ["peauecailles"] = {
        label = "Peau à écailles",
        description = "",
        weight = 0.2,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/provision_alligator_skin.png",
        type = "item_standard",
    },
    ["viandereptile"] = {
        label = "Viande de reptile",
        description = "",
        weight = 0.1,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/provision_meat_stringy.png",
        type = "item_standard",
    },
    ["plume"] = {
        label = "Plume",
        description = "",
        weight = 0.1,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/feather.png",
        type = "item_standard",
    },
    ["peaupredateur"] = {
        label = "Peau de predateur",
        description = "",
        weight = 0.2,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/provision_moose_fur.png",
        type = "item_standard",
    },
    ["griffe"] = {
        label = "Griffe",
        description = "",
        weight = 0.05,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/provision_bobcat_claws.png",
        type = "item_standard",
    },
    ["bec"] = {
        label = "Bec",
        description = "",
        weight = 0.05,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/generic_animal_beak.png",
        type = "item_standard",
    },
    ["corne"] = {
        label = "Corne",
        description = "",
        weight = 0.1,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/generic_animal_horn.png",
        type = "item_standard",
    },
    ["pincecrabe"] = {
        label = "Pince de crabe",
        description = "",
        weight = 0.05,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/provision_meat_crustacean.png",
        type = "item_standard",
    },
    ["viandevolaille"] = {
        label = "Volaille",
        description = "",
        weight = 0.1,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/provision_meat_gamey_bird.png",
        type = "item_standard",
    },
    ["serre"] = {
        label = "Serre",
        description = "",
        weight = 0.05,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/provision_raven_claw.png",
        type = "item_standard",
    },
    ["bois"] = {
        label = "Bois",
        description = "",
        weight = 0.3,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/wood.png",
        type = "item_standard",
    },
    ["boiscerf"] = {
        label = "Bois de cerf",
        description = "",
        weight = 0.1,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/provision_buck_antlers.png",
        type = "item_standard",
    },
    ["queuerenard"] = {
        label = "Queue de renard",
        description = "",
        weight = 0.1,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/provision_squirrel_tail.png",
        type = "item_standard",
    },
    ["peauvisqueuse"] = {
        label = "Peau visqueuse",
        description = "",
        weight = 0.1,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/provision_trinket_iguana_scale.png",
        type = "item_standard",
    },
    ["glandevenin"] = {
        label = "Glande",
        description = "",
        weight = 0.2,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/provision_panther_eye.png",
        type = "item_standard",
    },
    ["dentrongeur"] = {
        label = "Dent de rongeur",
        description = "",
        weight = 0.1,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/provision_arrowhead_chipped.png",
        type = "item_standard",
    },
    ["defense"] = {
        label = "Défense",
        description = "",
        weight = 0.1,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/provision_boar_tusk.png",
        type = "item_standard",
    },
    ["queuedecastor"] = {
        label = "Queue de castor",
        description = "",
        weight = 0.1,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/provision_beaver_tail.png",
        type = "item_standard",
    },
    ["patteours"] = {
        label = "Patte d'ours",
        description = "",
        weight = 0.2,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/provision_lions_paw.png",
        type = "item_standard",
    },
    ["crocdecroco"] = {
        label = "Dent de crocodile",
        description = "",
        weight = 0.2,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/generic_animal_tooth.png",
        type = "item_standard",
    },
    ["carapace"] = {
        label = "Carapace",
        description = "",
        weight = 0.4,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/provision_trinket_turtle_shell.png",
        type = "item_standard",
    },
    ["peauserpent"] = {
        label = "Peau de serpent",
        description = "",
        weight = 0.2,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/provision_snake_skin.png",
        type = "item_standard",
    },
    ["croc"] = {
        label = "Croc de loup",
        description = "",
        weight = 0.1,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/provision_cougar_fang.png",
        type = "item_standard",
    },
    ["barbane"] = {
        label = "Barbane",
        description = "",
        weight = 0.05,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/consumable_herb_burdock_root.png",
        type = "item_standard",
    },
    ["saugeducolibri"] = {
        label = "Sauge du Colibri",
        description = "",
        weight = 0.05,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/consumable_herb_hummingbird_sage.png",
        type = "item_standard",
    },
    ["menthesauvage"] = {
        label = "Menthe Sauvage",
        description = "",
        weight = 0.05,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/consumable_herb_wild_mint.png",
        type = "item_standard",
    },
    ["coulemelle"] = {
        label = "Coulemelle",
        description = "",
        weight = 0.05,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/consumable_herb_parasol_mushroom.png",
        type = "item_standard",
    },
    ["asclepiade"] = {
        label = "Asclépiade",
        description = "",
        weight = 0.05,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/consumable_herb_milkweed.png",
        type = "item_standard",
    },
    ["ginseng"] = {
        label = "Ginseng",
        description = "",
        weight = 0.05,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/consumable_herb_american_ginseng.png",
        type = "item_standard",
    },
    ["millefeuille"] = {
        label = "Millefeuille",
        description = "",
        weight = 0.05,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/consumable_herb_yarrow.png",
        type = "item_standard",
    },
    ["chanterelle"] = {
        label = "Chanterelle",
        description = "",
        weight = 0.05,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/consumable_herb_chanterelles.png",
        type = "item_standard",
    },
    ["pouledesbois"] = {
        label = "Poule des bois ",
        description = "",
        weight = 0.05,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/consumable_herb_rams_head.png",
        type = "item_standard",
    },
    ["saugedudesert"] = {
        label = "Sauge du desert",
        description = "",
        weight = 0.05,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/consumable_herb_desert_sage.png",
        type = "item_standard",
    },
    ["jonccommun"] = {
        label = "Jonc commun",
        description = "",
        weight = 0.05,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/consumable_herb_common_bulrush.png",
        type = "item_standard",
    },
    ["pavot"] = {
        label = "Pavot",
        description = "",
        weight = 0.05,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/consumable_herb_prairie_poppy.png",
        type = "item_standard",
    },
    ["achillevisqueuse"] = {
        label = "Achillé Visqueuse",
        description = "",
        weight = 0.05,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/consumable_herb_english_mace.png",
        type = "item_standard",
    },
    ["camomillesauvage"] = {
        label = "Camomille sauvage",
        description = "",
        weight = 0.05,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/consumable_herb_wild_feverfew.png",
        type = "item_standard",
    },
    ["boletbai"] = {
        label = "Bolet-Baï",
        description = "",
        weight = 0.05,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/consumable_herb_bay_bolete.png",
        type = "item_standard",
    },
    ["baiedegaultherie"] = {
        label = "Baie de Gaultherie",
        description = "",
        weight = 0.05,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/consumable_herb_wintergreen_berry.png",
        type = "item_standard",
    },
    ["patate"] = {
        label = "Patate",
        description = "La pomme de terre",
        weight = 0.05,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/consumable_bread_chunk.png",
        type = "item_standard",
    },
    ["raisin"] = {
        label = "Raisin",
        description = "",
        weight = 0.05,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/consumable_herb_black_currant.png",
        type = "item_standard",
    },
    ["myrtille"] = {
        label = "Myrtille",
        description = "",
        weight = 0.051,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/consumable_herb_red_raspberry.png",
        type = "item_standard",
    },
    ["carrotesauvages"] = {
        label = "Carrotes sauvages",
        description = "",
        weight = 0.05,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/consumable_herb_wild_carrots.png",
        type = "item_standard",
    },
    ["orchideearaignee"] = {
        label = "Orchidée Araignée",
        description = "",
        weight = 0.05,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/orchid_spider.png",
        type = "item_standard",
    },
    ["sabotdelavierge"] = {
        label = "Sabot de la vierge",
        description = "",
        weight = 0.05,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/orchid_mf.png",
        type = "item_standard",
    },
    ["arethusebulbeuse"] = {
        label = "Aréthuse bulbeuse",
        description = "",
        weight = 0.05,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/orchid_dm.png",
        type = "item_standard",
    },
    ["epidendron"] = {
        label = "Épidendron",
        description = "",
        weight = 0.05,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/orchid_acunastar.png",
        type = "item_standard",
    },
    ["laurierrose"] = {
        label = "Laurier rose",
        description = "",
        weight = 0.05,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/consumable_herb_oleander_sage.png",
        type = "item_standard",
    },
    ["concoctionendurance"] = {
        label = "Essence de térébenthine",
        description = "Pour ceux manquant de vigueur",
        weight = 0.3,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/consumable_special_restorative.png",
        type = "item_standard",
    },
    ["concoctionanesthesiante "] = {
        label = "Emulsion Anesthésiante'",
        description = "Solution temporaire pour calmer la douleur",
        weight = 0.3,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/consumable_special_medicine.png",
        type = "item_standard",
    },
    ["concoctioncoagulation"] = {
        label = "Solution Coagulante",
        description = "A appliquer sur une plaie",
        weight = 0.3,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/consumable_special_snake_oil.png",
        type = "item_standard",
    },
    ["concoctiontonic"] = {
        label = "Tonic",
        description = "",
        weight = 0.3,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/consumable_special_tonic.png",
        type = "item_standard",
    },
    ["concoctionendurancemonture"] = {
        label = "Concoction d'endurance pour monture",
        description = "",
        weight = 0.3,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/consumable_tonic_potent_weight_gain.png",
        type = "item_standard",
    },
    ["concoctionanesthesiantemonture"] = {
        label = "Concoction anesthesiante pour monture",
        description = "",
        weight = 0.3,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/consumable_tonic_potent_weight_loss.png",
        type = "item_standard",
    },
    ["poison"] = {
        label = "Poison",
        description = "A ne pas avaler par mégarde",
        weight = 0.3,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/consumable_poison_tonic.png",
        type = "item_standard",
    },
    ["remedeinfection"] = {
        label = "Concentré Antiputride",
        description = "Soigne les infections",
        weight = 0.3,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/consumable_health_serum.png",
        type = "item_standard",
    },
    ["remedeantidouleur"] = {
        label = "Extrait de Camomille",
        description = "Soigne les maux",
        weight = 0.3,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/consumable_horse_medicine.png",
        type = "item_standard",
    },
    ["antidysentrie"] = {
        label = "Remède Digestif",
        description = "Règles les problèmes de bedon",
        weight = 0.3,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/consumable_horse_reviver.png",
        type = "item_standard",
    },
    ["antidote"] = {
        label = "Antidote",
        description = "A boire d'urgence",
        weight = 0.3,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/consumable_plymouth_gin.png",
        type = "item_standard",
    },
    ["antibiotic"] = {
        label = "Solution antibiotique",
        description = "A boire d'urgence",
        weight = 0.3,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/consumable_plymouth_gin.png",
        type = "item_standard",
    },
    ["antivenin"] = {
        label = "Antidote",
        description = "En cas de morsure",
        weight = 0.3,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/consumable_special_horse_medicine.png",
        type = "item_standard",
    },
    ["bandagecharbon"] = {
        label = "Bandage au charbon",
        description = "Bandage purifiant",
        weight = 0.1,
        canBeDropped = true,
        canBeUsed = true,
        limit = 100,
        imgsrc = "items/bandage.png",
        type = "item_standard"
    },
    ["bandagepatate"] = {
        label = "Bandage à la patate",
        description = "Bandage aux vertues apaisantes",
        weight = 0.1,
        canBeDropped = true,
        canBeUsed = true,
        limit = 100,
        imgsrc = "items/bandage.png",
        type = "item_standard"
    },
    ["attelle"] = {
        label = "Attelle",
        description = "Répare les vieux os",
        weight = 0.3,
        canBeDropped = true,
        canBeUsed = true,
        limit = 100,
        imgsrc = "items/generic_horse_equip_bedroll.png",
        type = "item_standard"
    },
    ["mortier"] = {
        label = "Mortier",
        description = "Permet de créer les plus viles concoctions",
        weight = 0.5,
        canBeDropped = true,
        canBeUsed = true,
        limit = 100,
        imgsrc = "items/mortar.png",
        type = "item_standard"
    },
    ["sucre"] = {
        label = "Sucre",
        description = "",
        weight = 0.3,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/sugar.png",
        type = "item_standard",
    },
    ["semencedetoreau"] = {
        label = "Semence bovine",
        description = "Curieuse idée",
        weight = 0.2,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/foutrebovin.png",
        type = "item_standard",
    },
    ["cereale"] = {
        label = "Céréale",
        description = "",
        weight = 0.1,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 2000,
        imgsrc = "items/consumable_predator_bait.png",
        type = "item_standard",
    },
-------- USINE ---------
["crossecattleman"] = {
    label = "Crosse Colt 1873",
    description = "",
    weight = 4,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/revolverstock.png",
    type = "item_standard",
},
["crosseschoffield"] = {
    label = "Crosse Smith & Wesson Model 3",
    description = "",
    weight = 4,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/revolverstock.png",
    type = "item_standard",
},
["crossedoubleaction"] = {
    label = "Crosse 1873 Chamelot-Delvigne",
    description = "",
    weight = 4,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/revolverstock.png",
    type = "item_standard",
},
["crosselemat"] = {
    label = "Crosse Lemat Revolver",
    description = "",
    weight = 4,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/revolverstock.png",
    type = "item_standard",
},
["crossenavy"] = {
    label = "Crosse Colt 1851 Navy",
    description = "",
    weight = 4,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/revolverstock.png",
    type = "item_standard",
},
["crossevolcanic"] = {
    label = "Crosse Smith & Wesson 1855",
    description = "",
    weight = 4,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/revolverstock.png",
    type = "item_standard",
},
["crossecanonscie"] = {
    label = "Crosse Colt 1883 Scié",
    description = "",
    weight = 4,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/riflestock.png",
    type = "item_standard",
},
["crosseevans"] = {
    label = "Crosse Evans",
    description = "",
    weight = 8,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/repeaterstock.png",
    type = "item_standard",
},
["crossecarabine"] = {
    label = "Crosse M1865 Spencer",
    description = "",
    weight = 8,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/repeaterstock.png",
    type = "item_standard",
},
["crosselancaster"] = {
    label = "Crosse Winchester 1873",
    description = "",
    weight = 8,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/repeaterstock.png",
    type = "item_standard",
},
["crosselitchfield"] = {
    label = "Crosse 1860 Henry",
    description = "",
    weight = 8,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/repeaterstock.png",
    type = "item_standard",
},
["crossespringfield"] = {
    label = "Crosse Springfield Model 1873",
    description = "",
    weight = 8,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/shtgn_stock.png",
    type = "item_standard",
},
["crosserollingblock"] = {
    label = "Crosse Remington Rolling Block",
    description = "",
    weight = 8,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/shtgn_stock.png",
    type = "item_standard",
},
["crossedoublecanon"] = {
    label = "Crosse Colt 1883",
    description = "",
    weight = 8,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/rptr_stock.png",
    type = "item_standard",
},
["corpsdarmecattleman"] = {
    label = "Corps d'arme Colt 1873",
    description = "",
    weight = 8,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/revolverframe.png",
    type = "item_standard",
},
["corpsdarmeschoffield"] = {
    label = "Corps d'arme Smith & Wesson Model 3",
    description = "",
    weight = 8,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/revolverframe.png",
    type = "item_standard",
},
["corpsdarmedoubleaction"] = {
    label = "Corps d'arme 1873 Chamelot-Delvigne",
    description = "",
    weight = 8,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/revolverframe.png",
    type = "item_standard",
},
["corpsdarmelemat"] = {
    label = "Corps d'arme Lemat Revolver",
    description = "",
    weight = 8,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/revolverframe.png",
    type = "item_standard",
},
["corpsdarmenavy"] = {
    label = "Corps d'arme Colt 1851 Navy",
    description = "",
    weight = 8,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/revolverframe.png",
    type = "item_standard",
},
["corpsdarmevolcanic"] = {
    label = "Corps d'arme Smith & Wesson 1855",
    description = "",
    weight = 8,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/revolverframe.png",
    type = "item_standard",
},
["corpsdarmecanonscie"] = {
    label = "Corps d'arme Colt 1883 Scié",
    description = "",
    weight = 8,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/revolverframe.png",
    type = "item_standard",
},
["corpsdarmeevans"] = {
    label = "Corps d'arme Evans",
    description = "",
    weight = 10,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/repeaterframe.png",
    type = "item_standard",
},
["corpsdarmecarabine"] = {
    label = "Corps d'arme M1865 Spencer",
    description = "",
    weight = 10,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/repeaterframe.png",
    type = "item_standard",
},
["corpsdarmelancaster"] = {
    label = "Corps d'arme Winchester 1873",
    description = "",
    weight = 10,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/repeaterframe.png",
    type = "item_standard",
},
["corpsdarmelitchfield"] = {
    label = "Corps d'arme 1860 Henry",
    description = "",
    weight = 10,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/repeaterframe.png",
    type = "item_standard",
},
["corpsdarmespringfield"] = {
    label = "Corps d'arme Springfield Model 1873",
    description = "",
    weight = 10,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/elephantrifleframe.png",
    type = "item_standard",
},
["corpsdarmerollingblock"] = {
    label = "Corps d'arme Remington Rolling Block",
    description = "",
    weight = 10,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/elephantrifleframe.png",
    type = "item_standard",
},
["corpsdarmedoublecanon"] = {
    label = "Corps d'arme Colt 1883",
    description = "",
    weight = 10,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/elp_frame.png",
    type = "item_standard",
},
["barrilletcattleman"] = {
    label = "Barrillet Colt 1873",
    description = "",
    weight = 2,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/revolvercylinder.png",
    type = "item_standard",
},
["barrilletschoffield"] = {
    label = "Barrillet Smith & Wesson Model 3",
    description = "",
    weight = 2,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/revolvercylinder.png",
    type = "item_standard",
},
["barrilletdoubleaction"] = {
    label = "Barrillet 1873 Chamelot-Delvigne",
    description = "",
    weight = 2,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/revolvercylinder.png",
    type = "item_standard",
},
["barrilletlemat"] = {
    label = "Barrillet Lemat Revolver",
    description = "",
    weight = 2,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/revolvercylinder.png",
    type = "item_standard",
},
["barrilletnavy"] = {
    label = "Barrillet Colt 1851 Navy",
    description = "",
    weight = 2,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/revolvercylinder.png",
    type = "item_standard",
},
["levierdarmementvolcanic"] = {
    label = "Levier d'armement Smith & Wesson 1855",
    description = "",
    weight = 2,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/provision_scrap_metal.png",
    type = "item_standard",
},
["levierdarmementcanonscie"] = {
    label = "Levier d'armement Colt 1883 Scié",
    description = "",
    weight = 2,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/provision_scrap_metal.png",
    type = "item_standard",
},
["levierdarmementevans"] = {
    label = "Levier d'armement Evans",
    description = "",
    weight = 4,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/provision_scrap_metal.png",
    type = "item_standard",
},
["levierdarmementcarabine"] = {
    label = "Levier d'armement M1865 Spencer",
    description = "",
    weight = 4,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/provision_scrap_metal.png",
    type = "item_standard",
},
["levierdarmementlancaster"] = {
    label = "Levier d'armement Winchester 1873",
    description = "",
    weight = 4,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/provision_scrap_metal.png",
    type = "item_standard",
},
["levierdarmementlitchfield"] = {
    label = "Levier d'armement 1860 Henry",
    description = "",
    weight = 4,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/provision_scrap_metal.png",
    type = "item_standard",
},
["levierdarmementspringfield"] = {
    label = "Levier d'armement Springfield Model 1873",
    description = "",
    weight = 4,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/provision_scrap_metal.png",
    type = "item_standard",
},
["levierdarmementrollingblock"] = {
    label = "Levier d'armement Remington Rolling Block",
    description = "",
    weight = 4,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/provision_scrap_metal.png",
    type = "item_standard",
},
["levierdarmementdoublecanon"] = {
    label = "Levier d'armement Colt 1883",
    description = "",
    weight = 4,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/provision_scrap_metal.png",
    type = "item_standard",
},
["canoncattleman"] = {
    label = "Canon Colt 1873",
    description = "",
    weight = 2,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/shortbarrel.png",
    type = "item_standard",
},
["canonschoffield"] = {
    label = "Canon Smith & Wesson Model 3",
    description = "",
    weight = 2,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/shortbarrel.png",
    type = "item_standard",
},
["canondoubleaction"] = {
    label = "Canon 1873 Chamelot-Delvigne",
    description = "",
    weight = 2,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/shortbarrel.png",
    type = "item_standard",
},
["canonlemat"] = {
    label = "Canon Lemat Revolver",
    description = "",
    weight = 2,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/shortbarrel.png",
    type = "item_standard",
},
["canonnavy"] = {
    label = "Canon Colt 1851 Navy",
    description = "",
    weight = 2,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/longbarrel.png",
    type = "item_standard",
},
["canonvolcanic"] = {
    label = "Canon Smith & Wesson 1855",
    description = "",
    weight = 2,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/shortbarrel.png",
    type = "item_standard",
},
["canoncanonscie"] = {
    label = "Canon Colt 1883 Scié",
    description = "",
    weight = 2,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/shortbarrel.png",
    type = "item_standard",
},
["canonevans"] = {
    label = "Canon Evans",
    description = "",
    weight = 4,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/longbarrel.png",
    type = "item_standard",
},
["canoncarabine"] = {
    label = "Canon M1865 Spencer",
    description = "",
    weight = 4,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/longbarrel.png",
    type = "item_standard",
},
["canonlancaster"] = {
    label = "Canon Winchester 1873",
    description = "",
    weight = 4,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/longbarrel.png",
    type = "item_standard",
},
["canonlitchfield"] = {
    label = "Canon 1860 Henry",
    description = "",
    weight = 4,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/longbarrel.png",
    type = "item_standard",
},
["canonspringfield"] = {
    label = "Canon Springfield Model 1873",
    description = "",
    weight = 4,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/lbarrel.png",
    type = "item_standard",
},
["canonrollingblock"] = {
    label = "Canon Remington Rolling Block",
    description = "",
    weight = 4,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/lbarrel.png",
    type = "item_standard",
},
["canondoublecanon"] = {
    label = "Canon Colt 1883",
    description = "",
    weight = 4,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/elp_frame.png",
    type = "item_standard",
},

----- EPICERIE ------

["tourtegibier"] = {
    label = "Tourte à la viande",
    description = "Fait avec amour, on l'espère",
    weight = 0.2,
    canBeDropped = true,
    canBeUsed = true,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/cherrypie.png",
    type = "item_standard",
},
["tourteviande"] = {
    label = "Tourte à la viande",
    description = "Fait avec amour, on l'espère",
    weight = 0.2,
    canBeDropped = true,
    canBeUsed = true,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/cherrypie.png",
    type = "item_standard",
},
["tourtevolaille"] = {
    label = "Tourte à la viande",
    description = "Fait avec amour, on l'espère",
    weight = 0.2,
    canBeDropped = true,
    canBeUsed = true,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/cherrypie.png",
    type = "item_standard",
},
["viandehachee"] = {
    label = "Viande hâchée",
    description = "De quoi ça provient ?",
    weight = 0.1,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/provision_rc_quartz_chunk.png",
    type = "item_standard",
},
["soupe"] = {
    label = "Soupe de légume",
    description = "Que des bonnes choses",
    weight = 0.2,
    canBeDropped = true,
    canBeUsed = true,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/tomatosoup.png",
    type = "item_standard",
},
["ragoutgibier"] = {
    label = "Ragoût",
    description = "De la viande, des légumes et de la joie",
    weight = 0.3,
    canBeDropped = true,
    canBeUsed = true,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/hotcocoa.png",
    type = "item_standard",
},
["ragoutviande"] = {
    label = "Ragoût",
    description = "De la viande, des légumes et de la joie",
    weight = 0.3,
    canBeDropped = true,
    canBeUsed = true,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/hotcocoa.png",
    type = "item_standard",
},
["ragoutvolaille"] = {
    label = "Ragoût",
    description = "De la viande, des légumes et de la joie",
    weight = 0.3,
    canBeDropped = true,
    canBeUsed = true,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/hotcocoa.png",
    type = "item_standard",
},
["beefsteakpatate"] = {
    label = "Beefsteak Patate",
    description = "De la viande, des patates et de la joie",
    weight = 0.3,
    canBeDropped = true,
    canBeUsed = true,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/meat_with_garlic.png",
    type = "item_standard",
},
["boeufaugin"] = {
    label = "Boeuf au gin",
    description = "Seulement pour les fins gourmets",
    weight = 0.3,
    canBeDropped = true,
    canBeUsed = true,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/consumable_meal_camp_stew_daily_2.png",
    type = "item_standard",
},
["cotedeboeuf"] = {
    label = "Côté de boeuf",
    description = "Une belle pièce de viande",
    weight = 0.3,
    canBeDropped = true,
    canBeUsed = true,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/consumable_meat_big_game_cooked.png",
    type = "item_standard",
},
["brochettegibier"] = {
    label = "Brochette",
    description = "A déguster autour du feu",
    weight = 0.3,
    canBeDropped = true,
    canBeUsed = true,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/consumable_meat_gamey_bird_cooked.png",
    type = "item_standard",
},
["brochetteviande"] = {
    label = "Brochette",
    description = "A déguster autour du feu",
    weight = 0.3,
    canBeDropped = true,
    canBeUsed = true,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/consumable_meat_gamey_bird_cooked.png",
    type = "item_standard",
},
["brochettevolaille"] = {
    label = "Brochette",
    description = "À déguster autour du feu",
    weight = 0.3,
    canBeDropped = true,
    canBeUsed = true,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/consumable_meat_gamey_bird_cooked.png",
    type = "item_standard",
},
["pain"] = {
    label = "Pain",
    description = "Un beau pain",
    weight = 0.3,
    canBeDropped = true,
    canBeUsed = true,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/consumable_bread_roll.png",
    type = "item_standard",
},
["gateau"] = {
    label = "Gâteau",
    description = "Succulent",
    weight = 0.3,
    canBeDropped = true,
    canBeUsed = true,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/cakeslice.png",
    type = "item_standard",
},
["tartemyrtille"] = {
    label = "Tarte au myrtille",
    description = "Délicieux",
    weight = 0.3,
    canBeDropped = true,
    canBeUsed = true,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/cakeslice.png",
    type = "item_standard",
},
["viandeherbe"] = {
    label = "Viande aux herbes",
    description = "Quel arôme",
    weight = 0.2,
    canBeDropped = true,
    canBeUsed = true,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/consumable_prime_beef_oregano_cooked.png",
    type = "item_standard",
},
["volailleherbe"] = {
    label = "Viande aux herbes",
    description = "Quel arôme",
    weight = 0.2,
    canBeDropped = true,
    canBeUsed = true,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/consumable_prime_beef_oregano_cooked.png",
    type = "item_standard",
},
["gibierherbe"] = {
    label = "Viande aux herbes",
    description = "Quel arôme",
    weight = 0.2,
    canBeDropped = true,
    canBeUsed = true,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/consumable_prime_beef_oregano_cooked.png",
    type = "item_standard",
},
["soupechampignon"] = {
    label = "Soupe de champignon",
    description = "Un mélange exquis",
    weight = 0.3,
    canBeDropped = true,
    canBeUsed = true,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/mushroom_soup.png",
    type = "item_standard",
},
["bouteillelait"] = {
    label = "Bouteille de lait",
    description = "À boire sans modération",
    weight = 0.2,
    canBeDropped = true,
    canBeUsed = true,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/consumable_offal.png",
    type = "item_standard",
},

------- FORGE ------
["lingotor"] = {
    label = "Lingot d'or",
    description = "Quelle richesse",
    weight = 4,
    canBeDropped = true,
    canBeUsed = false,
    limit = 2000,
    imgsrc = "items/gold.png",
    type = "item_standard"
},
["WEAPON_MELEE_HAMMER"] =
{
    label = "Marteau",
    description = "Attention aux doigts",
    weight = 1.0,
    canBeDropped = true,
    requireLvl = 1,
    weaponHash = GetHashKey("WEAPON_MELEE_HAMMER"),
    imgsrc = "items/weapon_melee_hammer.png",
    type = "item_weapon"
},

------- craft radial ---------

["silex"] = {
    label = "Silex",
    description = "Un Silex",
    weight = 0.1,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/sharp_rock.png",
    type = "item_standard",
},
["fil"] = {
    label = "Fil",
    description = "Un fil",
    weight = 0.05,
    canBeDropped = true,
    canBeUsed = false,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/provision_fsh_copper_spool.png",
    type = "item_standard",
},

---- vêtement
["clothes"] = {
    label = "Tenue",
    description = "Quelques vêtements",
    weight = 0.1,
    canBeDropped = true,
    canBeUsed = true,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/clothing_generic_outfit.png",
    type = "item_standard",
},
["chapeau"] = {
    label = "Chapeau",
    description = "Couvre-chef",
    weight = 0.1,
    canBeDropped = true,
    canBeUsed = true,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/clothing_hl_player_hat_027_1.png",
    type = "item_standard",
},
["masque"] = {
    label = "Masque",
    description = "Incognito",
    weight = 0.1,
    canBeDropped = true,
    canBeUsed = true,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/kit_mask_brown_sack.png",
    type = "item_standard",
},

------- feu de camp -----------
["viandepetitmamiferecuite"] = {
    label = "Viande petit gibier cuite",
    description = "Petit mais consistant",
    weight = 0.1,
    canBeDropped = true,
    canBeUsed = true,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/consumable_meat_exotic_bird_cooked.png",
    type = "item_standard",
},
["viandecuite"] = {
    label = "Viande cuite",
    description = "Sans épices ? Quel manque de goût",
    weight = 0.1,
    canBeDropped = true,
    canBeUsed = true,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/consumable_meat_prime_beef_cooked.png",
    type = "item_standard",
},
["viandegibiercuite"] = {
    label = "Venaison cuit",
    description = "Sans épices ? Quel manque de goût",
    weight = 0.1,
    canBeDropped = true,
    canBeUsed = true,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/consumable_meat_mature_venison_cooked.png",
    type = "item_standard",
},
["viandereptilecuite"] = {
    label = "Viande de reptile cuite",
    description = "Pour les aventuriers",
    weight = 0.1,
    canBeDropped = true,
    canBeUsed = true,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/consumable_meat_stringy_cooked.png",
    type = "item_standard",
},
["viandevolaillecuite"] = {
    label = "Volaille cuite",
    description = "Elle aurait du savoir voler",
    weight = 0.1,
    canBeDropped = true,
    canBeUsed = true,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/consumable_meat_plump_bird_cooked.png",
    type = "item_standard",
},
["herbesaromatiques"] = {
    label = "Herbes aromatiques",
    description = "Des odeurs qui apaisent l'âme",
    weight = 0.1,
    canBeDropped = true,
    canBeUsed = true,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/consumable_herb_creeping_thyme.png",
    type = "item_standard",
},
--- store
["tabacchiquer"] = {
    label = "Tabac à chiquer",
    description = "Du bon tabac",
    weight = 0.1,
    canBeDropped = true,
    canBeUsed = true,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/consumable_chewing_tobacco.png",
    type = "item_standard",
},
["lemonade"] = {
    label = "Limonade",
    description = "Bien fraîche",
    weight = 0.1,
    canBeDropped = true,
    canBeUsed = true,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/berryjuice.png",
    type = "item_standard",
},
["good_whisky"] = {
    label = "Whisky",
    description = "Un bon Whisky",
    weight = 0.1,
    canBeDropped = true,
    canBeUsed = true,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/consumable_whiskey.png",
    type = "item_standard",
},
["dirty_whiskey"] = {
    label = "Mauvais Whisky",
    description = "Un mauvais Whisky",
    weight = 0.1,
    canBeDropped = true,
    canBeUsed = true,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/consumable_tenn_whiskey.png",
    type = "item_standard",
},
["cigar"] = {
    label = "Cigar",
    description = "Il ne vient pas de guarma, mais il est bon",
    weight = 0.1,
    canBeDropped = true,
    canBeUsed = true,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/consumable_cigar.png",
    type = "item_standard",
},
["cigarettes"] = {
    label = "Cigarette",
    description = "Une petite blonde",
    weight = 0.1,
    canBeDropped = true,
    canBeUsed = true,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/cigarette.png",
    type = "item_standard",
},
["coffee"] = {
    label = "Café",
    description = "Un petit noir",
    weight = 0.1,
    canBeDropped = true,
    canBeUsed = true,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/consumable_coffee.png",
    type = "item_standard",
},
["champignontoxique"] = {
    label = "Lépiote Brun-rose",
    description = "",
    weight = 0.2,
    canBeDropped = true,
    canBeUsed = true,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/consumable_herb_parasol_mushroom.png",
    type = "item_standard",
},
---- saloon 
["gin"] = {
    label = "Gin",
    description = "",
    weight = 0.1,
    canBeDropped = true,
    canBeUsed = true,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/consumable_gin.png",
    type = "item_standard",
},
["mezcal"] = {
    label = "Mezcal",
    description = "",
    weight = 0.1,
    canBeDropped = true,
    canBeUsed = true,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/consumable_potent_tonic.png",
    type = "item_standard",
},

--- portes
["lockpick"] = {
    label = "Crochet",
    description = "",
    weight = 0.2,
    canBeDropped = true,
    canBeUsed = true,
    requireLvl = 0,
    limit = 2000,
    imgsrc = "items/kit_lightning_conductor.png",
    type = "item_standard",
},
}



exports("GetItemsList", function()
    return Config.Items
end)

