fx_version "adamant"
games {"rdr3"}
rdr3_warning 'I acknowledge that this is a prerelease build of RedM, and I am aware my resources *will* become incompatible once RedM ships.'

client_script {
    "config.lua",
    "rm.lua"
}
server_script {'server.lua'}

ui_page "html/menu.html"

files {
	"html/menu.html",
	"html/raphael.min.js",
    "html/wheelnav.min.js",
	"html/twofingers.png",
	"html/bow.png",
	"html/nod.png",
	"html/tough.png",
	"html/tip1.png",
	"html/tip2.png",
	"html/tip3.png",
	"html/tip4.png",
	"html/job.png",
	"html/emote.png",
	"html/reload.png",
	"html/walkstyle.png",
	"html/endemote.png",
	"html/horseemote.png",
	"html/cloths.png",
	"html/pb.png",
	"html/doctor.png",
	"html/police.png",
	"html/id.png",
	"html/callp.png",
	"html/calld.png",
	"html/misc.png",
	"html/ca.png",
	"html/sjob.png",
	"html/close.png",
	"html/hat.png",
	"html/sleeves.png",
	"html/coller.png",
	"html/mask.png",
	"html/undress.png",
	"html/dress.png",
	"html/eyeware.png",
	"html/neckwear.png",
	"html/bandana.png",
	"html/shirt.png",
	"html/ring.png",
	"html/bow1.png",
	"html/tie.png",
	"html/coat.png",
	"html/closedcoat.png",
	"html/vest.png",
	"html/suspender.png",
	"html/armor.png",
	"html/poncho.png",
	"html/cloak.png",
	"html/bracelet.png",
	"html/glove.png",
	"html/belt.png",
	"html/gunbelt.png",
	"html/pants.png",
	"html/skirt.png",
	"html/chaps.png",
	"html/spats.png",
	"html/spurs.png",
	"html/buckle.png",
	"html/satchels.png",
	"html/poker.png",
	"html/boots.png",
	"html/flipc.png",
	"html/rps.png",
	"html/hud.png",
	"html/chat.png",
	"html/forcast.png",
	"html/dwagon.png",
	"html/dice.png",
	"html/pet.png",
	"html/race.png",
	"html/casual.png",
	"html/crazy.png",
	"html/drunkw.png",
	"html/erider.png",
	"html/flam.png",
	"html/horn.png",
	"html/gslinger.png",
	"html/inquisitive.png",
	"html/refined.png",
	"html/stype.png",
	"html/veteran.png",
	"html/default.png",
	"html/cbird.png",
	"html/greeting.png",
	"html/actions.png",
	"html/hurt.png",
	"html/standing.png",
	"html/dance.png",
	"html/mixed.png",
	"html/shared.png",
	"html/jig.png",
	"html/awkward.png",
	"html/carefree.png",
	"html/smart.png",
	"html/confident.png",
	"html/drunk.png",
	"html/drunk2.png",
	"html/confident3.png",
	"html/wild2.png",
	"html/drunk3.png",
	"html/full.png",
	"html/simple.png",
	"html/formal.png",
	"html/graceful.png",
	"html/thehassle.png",
	"html/hyped.png",
	"html/cheerful.png",
	"html/wild.png",
	"html/old.png",
	"html/confident2.png",
	"html/carefree2.png",
	"html/awkward2.png",
	"html/neutral.png",
	"html/gentlewave.png",
	"html/discreetwave.png",
	"html/friendlywave.png",
	"html/hypedwave.png",
	"html/sarcastic.png",
	"html/humble.png",
	"html/smooth.png",
	"html/laydown.png",
	"html/sit.png",
	"html/sweat.png",
	"html/freeze.png",
	"html/knock.png",
	"html/operation.png",
	"html/cry.png",
	"html/mourn.png",
	"html/surrender.png",
	"html/hostage.png",
	"html/handsup.png",
	"html/caught.png",
	"html/cover.png",
	"html/scared.png",
	"html/piss.png",
	"html/full2.png",
	"html/search.png",
	"html/point.png",
	"html/freezingcold.png",
	"html/overhere.png",
	"html/arm.png",
	"html/shoulder.png",
	"html/hip.png",
	"html/chest.png",
	"html/chest1.png",
	"html/neck.png",
	"html/back.png",
	"html/dying.png",
	"html/itches.png",
	"html/uncomfortable.png",
	"html/throwup.png",
	"html/collapse.png",
	"html/damage1.png",
	"html/damage2.png",
	"html/sick.png",
	"html/nervous.png",
	"html/drunke.png",
	"html/seductive.png",
	"html/feminine.png",
	"html/careless.png",
	"html/impatient.png",
	"html/pending.png",
	"html/handsbelt.png",
	"html/handsside.png",
	"html/badass.png",
	"html/crossarms.png",
	"html/confused.png",
	"html/abandoned.png",
	"html/guard.png",
	"html/clear.png",
	"html/angry.png",
	"html/sad.png",
	"html/so.png",
	"html/please.png",
	"html/quietnow.png",
	"html/stinky.png",
	"html/shh.png",
	"html/fightme.png",
	"html/keepup.png",
	"html/yeeha.png",
	"html/angry2.png",
	"html/sneaky.png",
	"html/chicken.png",
	"html/thumbsup.png",
	"html/thumbsdown.png",
	"html/gorilla.png",
	"html/careful.png",
	"html/flap.png",
	"html/laughat.png",
	"html/laugh.png",
	"html/challenge.png",
	"html/airkisses.png",
	"html/mirror.png",
	"html/notepad.png",
	"html/checkout.png",
	"html/flex.png",
	"html/threat.png",
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
}