Config = {}

Config.AnimCallCommand = "a"


Config.NotHoldKeye = true

Config.AnimMenuKeyPress = true
Config.AnimMenuKey = 0x80F28E95 


Config.OpenMenuCommandEnable = false
Config.OpenMenuCommand = "animmenu"

Config.AllowKeybind = true
Config.Keybind = {
	[1] = 0xE6F612E4,
	[2] = 0x1CE6D9EB,
	[3] = 0x4F49CC4C,
	[4] = 0x8F9F9E58,
	[5] = 0xAB62E997,
	[6] = 0xA1FDE2A6,
	[7] = 0xB03A913B,
	[8] = 0x42385422,
}

Config.Language = {
	[1] = "Voulez vous supprimer : ",
	[2] = " animation?",
	[3] = "Oui",
	[4] = "Non",
	[5] = "Ramper",
	[6] = "Se coucher",
	[7] = "Ramper",
	[8] = "Plus vite",
	[9] = "En Arrière",
	[10] = "S'accroupir",
	[11] = "Accepter",
	[12] = "On number you need select anim : ",
	[13] = "Commande: /"..Config.AnimCallCommand.." XXXXX",
	[14] = "Ajouter ou supprimer des favoris",
	[15] = "Supprimer",
	[16] = "Favori",
	--All other translates for style is in "html/index.html"
}

Config.Prop = {
	[1] = {name="Sheriff Badge 1", prop= "p_deputybadge01x", bone=31201, parameter={0.038, -0.14, -0.242, 75.5, 6.2, 38.1}, jobLock={"sheriff_rhodes", "sheriff_bla"}},
	[2] = {name="Sheriff Badge 2", prop= "p_deputybadge01x", bone=30226, parameter={0.058, 0.125, 0.036, -116.0, -5.0, -6.0}, jobLock={"sheriff_rhodes", "sheriff_bla"}},
	[3] = {name="Sheriff Badge 3", prop= "p_deputybadge01x", bone=30226, parameter={0.058, 0.121, 0.036, -116.0, -5.0, -6.0}, jobLock={"sheriff_rhodes", "sheriff_bla"}},
	[4] = {name="Marshall Badge 1", prop= "s_badgeusmarshal01x", bone=30226, parameter={0.08, 0.115, 0.04, 163.0, 0.0, 342.0}, jobLock={"marshall"}},
	[5] = {name="Marshall Badge 2", prop= "s_badgeusmarshal01x", bone=30226, parameter={0.08, 0.12, 0.04, 163.0, 0.0, 358.0}, jobLock={"marshall"}},
	[6] = {name="Marshall Badge 3", prop= "s_badgeusmarshal01x", bone=30226, parameter={0.08, 0.165, 0.06, 168.0, 0.0, -8.0}, jobLock={"marshall"}},
	[7] = {name="Sac 1", prop= "p_ambpack01x", bone=41232, parameter={0.33, -0.12, -0.19, 0.00, -56.0, 0.00}, jobLock={}},
	[8] = {name="Sac 2", prop= "p_ambpack02x", bone=41232, parameter={0.22, -0.1, -0.11, 6.0, -55.0, 0.0}, jobLock={}},
	[9] = {name="Sac 3", prop= "p_ambpack04x", bone=41232, parameter={0.08, 0.0, 0.11, 88.0, -62.0, 0.0}, jobLock={}},
	[10] = {name="Sac 4", prop= "p_bag01x", bone=22798, parameter={0.40, 0.05, -0.05, 180.0, 90.0, -70.0}, jobLock={}},
	[11] = {name="Carquois 1", prop= "p_arrowbundle01x", bone=1058, parameter={0.0, -0.17, -0.21, -90.0, -20.0, -170.00}, jobLock={}},
	[12] = {name="Guitare dans le dos", prop="p_guitar01x", bone=37600, parameter={0.29, -0.12, -0.22, -5.0, -21.0, 0.0}, jobLock={}},
	[13] = {name="Plume sur la tête", prop="p_feather01x", bone=21030, parameter={0.12, -0.05, -0.07, 259.0, 0.0, 111.0}, jobLock={}},
	[14] = {name="Paille dans la bouvhe", prop="p_cs_haypiece01x", bone=21030, parameter={-0.014, 0.069, 0.009, 56.4, 900.0, 179.3}, jobLock={}},
	[15] = {name="Carquois 2", prop= "p_arrowbundle02x", bone=1058, parameter={0.0, -0.17, -0.21, -90.0, -20.0, -170.00}, jobLock={}},
}


Config.Anim = {
	-- [1] = 		{female=true, 	name="Reset clothes", 			itsAnimation="command", 		command="db", iconRadial=true},
	-- [3] = 		{female=true, 	name="Pets", 					itsAnimation="command", 		command="pets"},
	-- [4] = 		{female=true, 	name="House Management", 		itsAnimation="command", 		command="house_manage"},
	-- [5] = 		{female=true, 	name="Camp Management", 		itsAnimation="command", 		command="camp_manage"},
	-- [6] = 		{female=true, 	name="Load Camp", 				itsAnimation="command", 		command="camp_load"},
	-- [7] = 		{female=true, 	name="Ranch Management", 		itsAnimation="command", 		command="ranch_manage"},
	[8] = 		{female=true, 	name="Inspecter l'arme", 				itsAnimation="command", 		command="inspect"},
	-- [9] = 		{female=true, 	name="Undress", 				itsAnimation="command", 		command="undress"},
	-- [10] = 		{female=true, 	name="Dress", 					itsAnimation="command", 		command="dress"},
	-- [11] = 		{female=true, 	name="S/N Bandana", 			itsAnimation="command", 		command="bandana"},
	-- [12] = 		{female=true, 	name="S/N Sleeves", 			itsAnimation="command", 		command="sleeves"},
	-- [13] = 		{female=true, 	name="S/N Hat", 				itsAnimation="command", 		command="hat"},
	-- [14] = 		{female=true, 	name="S/N Shirt", 				itsAnimation="command", 		command="shirt"},
	-- [15] = 		{female=true, 	name="S/N Vest", 				itsAnimation="command", 		command="vest"},
	-- [16] = 		{female=true, 	name="S/N Coat", 				itsAnimation="command", 		command="coat"},
	-- [17] = 		{female=true, 	name="S/N Belt", 				itsAnimation="command", 		command="belt"},
	-- [18] = 		{female=true, 	name="S/N Pants", 				itsAnimation="command", 		command="pants"},
	-- [19] = 		{female=true, 	name="S/N Skirt", 				itsAnimation="command", 		command="skirt"},
	-- [20] = 		{female=true, 	name="S/N Boots", 				itsAnimation="command", 		command="boots"}, 
	-- [21] = 		{female=true, 	name="S/N Poncho", 				itsAnimation ="command", 		command="poncho"},
	-- [22] = 		{female=true, 	name="S/N Cloak", 				itsAnimation="command", 		command="plastic"},
	-- [23] = 		{female=true, 	name="S/N Chaps", 				itsAnimation="command", 		command="chaps"},
	-- [24] = 		{female=true, 	name="S/N Spurs", 				itsAnimation="command", 		command="spurs"},
	-- [25] = 		{female=true, 	name="S/N Glasses", 			itsAnimation="command", 		command="glasses"},
	-- [26] = 		{female=true, 	name="S/N Mask", 				itsAnimation="command", 		command="mask"},
	-- [27] = 		{female=true, 	name="S/N Scarf", 				itsAnimation="command", 		command="satek"},
	-- [28] = 		{female=true, 	name="S/N Tie", 				itsAnimation="command", 		command="tie"},
	-- [29] = 		{female=true, 	name="S/N Suspenders", 			itsAnimation="command", 		command="Suspenders"},
	-- [30] = 		{female=true, 	name="S/N Gloves", 				itsAnimation="command", 		command="gloves"},
	-- [31] = 		{female=true, 	name="S/N Rings", 				itsAnimation="command", 		command="bracelet"},
	-- [32] = 		{female=true, 	name="S/N Bracelet", 			itsAnimation="command", 		command="brasny"},
	-- [33] = 		{female=true, 	name="S/N Bags", 				itsAnimation="command", 		command="accessories"},
	-- [34] = 		{female=true, 	name="S/N Belts", 				itsAnimation="command", 		command="passes"},
	-- [35] = 		{female=true, 	name="S/N Hairdressers", 		itsAnimation="command", 		command="hairdressers"},
	-- [36] = 		{female=true, 	name="S/N Leggings", 			itsAnimation="command", 		command="Leggings"},

	[100] = 	{female=true,	name="Révérence",				itsAnimation="emote", 			emote="KIT_EMOTE_GREET_FANCY_BOW_1"},
	[101] = 	{female=true,	name="Salut 1",				itsAnimation="emote", 			emote="KIT_EMOTE_GREET_WAVENEAR_1"},
	[103] = 	{female=true,	name="Viens vite",				itsAnimation="emote", 			emote="KIT_EMOTE_ACTION_BECKON_1"},
	[104] = 	{female=true,	name="Vérifier la piéce",			itsAnimation="emote", 			emote="KIT_EMOTE_ACTION_BITING_GOLD_COIN_1"},
	[105] = 	{female=true,	name="Envoyer un baiser",			itsAnimation="emote", 			emote="KIT_EMOTE_ACTION_BLOW_KISS_1"},
	[106] = 	{female=true,	name="Célébration 1",					itsAnimation="emote", 			emote="KIT_EMOTE_ACTION_BOAST_1"},
	[107] = 	{female=true,	name="Vérifier l'heure",		itsAnimation="emote", 			emote="KIT_EMOTE_ACTION_CHECK_POCKET_WATCH_1"},
	[108] = 	{female=true,	name="Pile ou face",			itsAnimation="emote", 			emote="KIT_EMOTE_ACTION_COIN_FLIP_1"},
	[109] = 	{female=true,	name="Célébration 2",					itsAnimation="emote", 			emote="KIT_EMOTE_ACTION_FIST_PUMP_1"},
	[110] = 	{female=true,	name="Bander les muscles",					itsAnimation="emote", 			emote="KIT_EMOTE_ACTION_FLEX_1"},
	[111] = 	{female=true,	name="Suivez moi",				itsAnimation="emote", 			emote="KIT_EMOTE_ACTION_FOLLOW_ME_1"},
	[112] = 	{female=true,	name="Frustration 1",			itsAnimation="emote", 			emote="KIT_EMOTE_ACTION_HISSYFIT_1"},
	[113] = 	{female=true,	name="Crie du loup",					itsAnimation="emote", 			emote="KIT_EMOTE_ACTION_HOWL_1"},
	[114] = 	{female=true,	name="Hypnotiser 1",				itsAnimation="emote", 			emote="KIT_EMOTE_ACTION_HYPNOSIS_POCKET_WATCH_1"},
	[115] = 	{female=true,	name="Je crois que...ah non!", 					itsAnimation="emote", 			emote="KIT_EMOTE_ACTION_IDEA_1"},
	[116] = 	{female=true,	name="Fabriquer", 				itsAnimation="emote", 			emote="KIT_EMOTE_ACTION_LETS_CRAFT_1"},
	[117] = 	{female=true, 	name="Pêcher", 					itsAnimation="emote", 			emote="KIT_EMOTE_ACTION_LETS_FISH_1"},
	[118] = 	{female=true, 	name="Par là !", 				itsAnimation="emote", 			emote="KIT_EMOTE_ACTION_LETS_GO_1"},
	[119] = 	{female=true, 	name="Jouer aux cartes", 				itsAnimation="emote", 			emote="KIT_EMOTE_ACTION_LETS_PLAY_CARDS_1"},
	[120] = 	{female=true, 	name="^Faire le sourd", 				itsAnimation="emote", 			emote="KIT_EMOTE_ACTION_LISTEN_1"},
	[121] = 	{female=true, 	name="Regarder au loin", 					itsAnimation="emote", 			emote="KIT_EMOTE_ACTION_LOOK_DISTANCE_1"},
	[122] = 	{female=true, 	name="Pointer du doigt", 					itsAnimation="emote", 			emote="KIT_EMOTE_ACTION_POINT_1"},
	[123] = 	{female=true, 	name="Rassemblement !", 					itsAnimation="emote", 			emote="KIT_EMOTE_ACTION_POSSE_UP_1"},
	[124] = 	{female=true, 	name="Implorer Dieu", 		itsAnimation="emote", 			emote="KIT_EMOTE_ACTION_PRAYER_1"},
	[125] = 	{female=true,	name="Pierre Papier Ciseaux", 	itsAnimation="emote", 			emote="KIT_EMOTE_ACTION_ROCK_PAPER_SCISSORS_1",},
	[126] = 	{female=true, 	name="Plan machiavélique", 		itsAnimation="emote", 			emote="KIT_EMOTE_ACTION_SCHEME_1"},
	[127] = 	{female=true, 	name="Pan Pan Pan !", 				itsAnimation="emote", 			emote="KIT_EMOTE_ACTION_SHOOTHIP_1"},
	[128] = 	{female=true, 	name="Explosion de joie", 					itsAnimation="emote", 			emote="KIT_EMOTE_ACTION_SKYWARD_SHOOTING_1"},
	[129] = 	{female=true, 	name="Moucher", 					itsAnimation="emote", 			emote="KIT_EMOTE_ACTION_SNOT_ROCKET_1"},
	[130] = 	{female=true, 	name="As de la gachette", 				itsAnimation="emote", 			emote="KIT_EMOTE_ACTION_SPIN_AND_AIM_1"},
	[131] = 	{female=true, 	name="Cracher 1", 					itsAnimation="emote", 			emote="KIT_EMOTE_ACTION_SPIT_1"},
	[132] = 	{female=true, 	name="Faire peur", 				itsAnimation="emote", 			emote="KIT_EMOTE_ACTION_SPOOKY_1"},
	[134] = 	{female=true, 	name="Stop", 			itsAnimation="emote", 			emote="KIT_EMOTE_ACTION_STOP_HERE_1"},
	[135] = 	{female=true, 	name="Ecrire dans le cahier", 	itsAnimation="emote", 			emote="KIT_EMOTE_ACTION_TAKE_NOTES_1"},
	[136] = 	{female=true, 	name="Alcool fort", 				itsAnimation="emote", 			emote="KIT_EMOTE_ACTION_WET_YOUR_WHISTLE_1"},
	[137] = 	{female=true, 	name="Petite danse", 				itsAnimation="emote", 			emote="KIT_EMOTE_DANCE_AWKWARD_A_1"},
	[138] = 	{female=true,	name="Bonne musique 1",		itsAnimation="emote", 			emote="KIT_EMOTE_DANCE_CAREFREE_A_1"},
	[139] = 	{female=true,	name="Bonne musique 2",		itsAnimation="emote", 			emote="KIT_EMOTE_DANCE_CAREFREE_B_1"},
	[140] = 	{female=true,	name="Bonne musique 3",		itsAnimation="emote", 			emote="KIT_EMOTE_DANCE_CONFIDENT_A_1"},
	[141] = 	{female=true,	name="Bonne musique 4",		itsAnimation="emote", 			emote="KIT_EMOTE_DANCE_CONFIDENT_B_1"},
	[142] = 	{female=true,	name="Bonne musique 5",		itsAnimation="emote", 			emote="KIT_EMOTE_DANCE_DRUNK_A_1"},
	[143] = 	{female=true,	name="Bonne musique 6",		itsAnimation="emote", 			emote="KIT_EMOTE_DANCE_DRUNK_B_1"},
	[144] = 	{female=true,	name="Bonne musique 7",		itsAnimation="emote", 			emote="KIT_EMOTE_DANCE_FORMAL_A_1"},
	[145] = 	{female=true,	name="Bonne musique 8",		itsAnimation="emote", 			emote="KIT_EMOTE_DANCE_GRACEFUL_A_1"},
	[150] = 	{female=true,	name="Salut timide",				itsAnimation="emote", 			emote="KIT_EMOTE_GREET_GENTLEWAVE_1"},
	[151] = 	{female=true,	name="Lasso cowboy",			itsAnimation="emote", 			emote="KIT_EMOTE_GREET_GET_OVER_HERE_1"},
	[152] = 	{female=true,	name="Merci beaucoup", 				itsAnimation="emote", 			emote="KIT_EMOTE_GREET_GLAD_1"},
	[153] = 	{female=true,	name="Bien joué 1",				itsAnimation="emote", 			emote="KIT_EMOTE_GREET_HAT_FLICK_1"},
	[154] = 	{female=true,	name="Bien joué 2",				itsAnimation="emote", 			emote="KIT_EMOTE_GREET_HAT_TIP_1"},
	[155] = 	{female=true,	name="Sacré toi !",			itsAnimation="emote", 			emote="KIT_EMOTE_GREET_HEY_YOU_1"},
	[156] = 	{female=true,	name="Merci infiniment",		itsAnimation="emote", 			emote="KIT_EMOTE_GREET_OUTPOUR_1"},
	[157] = 	{female=true,	name="Merci asiatique",				itsAnimation="emote", 			emote="KIT_EMOTE_GREET_RESPECTFUL_BOW_1"},
	[158] = 	{female=true,	name="Ils étaient 7",					itsAnimation="emote", 			emote="KIT_EMOTE_GREET_SEVEN_1"},
	[159] = 	{female=true,	name="Salut 2",				itsAnimation="emote", 			emote="KIT_EMOTE_GREET_SUBTLE_WAVE_1"},
	[160] = 	{female=true,	name="Tadaaa",					itsAnimation="emote", 			emote="KIT_EMOTE_GREET_TADA_1"},
	[161] = 	{female=true,	name="Toi viens là !",				itsAnimation="emote", 			emote="KIT_EMOTE_GREET_THUMBSUP_1"},
	[162] = 	{female=true,	name="Tout à fait",		itsAnimation="emote", 			emote="KIT_EMOTE_GREET_TOUGH_1"},
	[163] = 	{female=true,	name="Faire l'éloge",				itsAnimation="emote", 			emote="KIT_EMOTE_REACTION_AMAZED_1"},
	[164] = 	{female=true,	name="Applaudir 3",				itsAnimation="emote", 			emote="KIT_EMOTE_REACTION_APPLAUSE_1"},
	[165] = 	{female=true,	name="Supplier",			itsAnimation="emote", 			emote="KIT_EMOTE_REACTION_BEGMERCY_1"},
	[167] = 	{female=true,	name="Tête dans la main 1",				itsAnimation="emote", 			emote="KIT_EMOTE_REACTION_FACEPALM_1"},
	[168] = 	{female=true,	name="Rage 1",				itsAnimation="emote", 			emote="KIT_EMOTE_REACTION_HANGOVER_1"},
	[169] = 	{female=true,	name="Offensé 1",				itsAnimation="emote", 			emote="KIT_EMOTE_REACTION_HOW_DARE_YOU_1"},
	[170] = 	{female=true,	name="Vomi 1",				itsAnimation="emote", 			emote="KIT_EMOTE_REACTION_HURL_1"},
	[171] = 	{female=true,	name="Chuuuut",					itsAnimation="emote", 			emote="KIT_EMOTE_REACTION_HUSH_YOUR_MOUTH_1"},
	[172] = 	{female=true,	name="Rire 1",					itsAnimation="emote", 			emote="KIT_EMOTE_REACTION_JOVIAL_LAUGH_1"},
	[173] = 	{female=true,	name="Oui oui",				    itsAnimation="emote", 			emote="KIT_EMOTE_REACTION_NOD_HEAD_1"},
	[174] = 	{female=true,	name="Ouuuf",	itsAnimation="emote", 			emote="KIT_EMOTE_REACTION_PHEW_1"},
	[176] = 	{female=true,	name="Terrifiant",				itsAnimation="emote", 			emote="KIT_EMOTE_REACTION_SCARED_1"},
	[177] = 	{female=true,	name="Refus catégorique",				itsAnimation="emote", 			emote="KIT_EMOTE_REACTION_SHAKEHEAD_1"},
	[178] = 	{female=true,	name="Petite blague",	itsAnimation="emote", 			emote="KIT_EMOTE_REACTION_SHOT_1"},
	[179] = 	{female=true,	name="Je ne sais pas", 				itsAnimation="emote", 			emote="KIT_EMOTE_REACTION_SHRUG_1"},
	[181] = 	{female=true,	name="Applaudir lentement", 				itsAnimation="emote", 			emote="KIT_EMOTE_REACTION_SLOW_CLAP_1"},
	[182] = 	{female=true,	name="Sentir", 				itsAnimation="emote", 			emote="KIT_EMOTE_REACTION_SNIFFING_1"},
	[183] = 	{female=true,	name="Pleurer", 					itsAnimation="emote", 			emote="KIT_EMOTE_REACTION_SOB_1"},
	[184] = 	{female=true,	name="Drapeau blanc", 			itsAnimation="emote", 			emote="KIT_EMOTE_REACTION_SURRENDER_1"},
	[186] = 	{female=true,	name="Pointer du doigt", 				itsAnimation="emote", 			emote="KIT_EMOTE_REACTION_THIS_GUY_1"},
	[187] = 	{female=true,	name="Pouce vers le bas", 			itsAnimation="emote", 			emote="KIT_EMOTE_REACTION_THUMBSDOWN_1"},
	[188] = 	{female=true,	name="Rejeter", 			itsAnimation="emote", 			emote="KIT_EMOTE_REACTION_WAG_FINGER_1"},
	[189] = 	{female=true,	name="Moi ?", 				itsAnimation="emote", 			emote="KIT_EMOTE_REACTION_WHO_ME_1"},
	[190] = 	{female=true,	name="Célébration 3", 					itsAnimation="emote", 			emote="KIT_EMOTE_REACTION_YEEHAW_1"},
	[191] = 	{female=true,	name="Vas y frappe", 			itsAnimation="emote", 			emote="KIT_EMOTE_TAUNT_BEST_SHOT_1"},
	[192] = 	{female=true,	name="Tu vas pleurer ?", 			itsAnimation="emote", 			emote="KIT_EMOTE_TAUNT_BOOHOO_1"},
	[193] = 	{female=true,	name="Poule mouillée", 			itsAnimation="emote", 			emote="KIT_EMOTE_TAUNT_CHICKEN_1"},
	[194] = 	{female=true,	name="Trompette !", 				itsAnimation="emote", 			emote="KIT_EMOTE_TAUNT_COCK_SNOOK_1"},
	[195] = 	{female=true,	name="Sauvaaage", 					itsAnimation="emote", 			emote="KIT_EMOTE_TAUNT_COUGAR_SNARL_1"},
	[196] = 	{female=true,	name="Claque", 			itsAnimation="emote", 			emote="KIT_EMOTE_TAUNT_CRUISING_BRUISING_1"},
	[197] = 	{female=true,	name="Réfléchis bien", 			itsAnimation="emote", 			emote="KIT_EMOTE_TAUNT_CUCKOO_1"},
	[198] = 	{female=true,	name="Provocation", 			itsAnimation="emote", 			emote="KIT_EMOTE_TAUNT_FIDDLEHEAD_1"},
    [199] = 	{female=true,	name="Doigt 1", 				itsAnimation="emote", 			emote="KIT_EMOTE_TAUNT_FLIP_OFF_1"},
	[200] = 	{female=true,	name="Doigt 2", 				itsAnimation="emote", 			emote="KIT_EMOTE_TAUNT_FINGER_SLINGER_1"},
	[201] = 	{female=true,	name="Bouuuu", 				itsAnimation="emote", 			emote="KIT_EMOTE_TAUNT_FRIGHTEN_1"},
	[202] = 	{female=true,	name="Frappe sur le torse", 				    itsAnimation="emote", 			emote="KIT_EMOTE_TAUNT_GORILLA_CHEST_1"},
	[203] = 	{female=true,	name="Regarde moi", 			itsAnimation="emote", 			emote="KIT_EMOTE_TAUNT_IM_WATCHING_YOU_1"},
	[204] = 	{female=true,	name="Taunt", 			itsAnimation="emote", 			emote="KIT_EMOTE_TAUNT_INSIGNIFICANT_1"},
	[205] = 	{female=true,	name="Tu la vois celle là", 			itsAnimation="emote", 			emote="KIT_EMOTE_TAUNT_PROVOKE_1"},
	[206] = 	{female=true,	name="Tu es mort !", 			itsAnimation="emote", 			emote="KIT_EMOTE_TAUNT_THROAT_SLIT_1"},
	[207] = 	{female=true,	name="Qu'est-ce qu'il y a ?", 			itsAnimation="emote", 			emote="KIT_EMOTE_TAUNT_UP_YOURS_1"},
	[208] = 	{female=true,	name="Duel", 				itsAnimation="emote", 			emote="KIT_EMOTE_TAUNT_VERSUS_1"},
	[209] = 	{female=true,	name="Explosion !", 					itsAnimation="emote", 			emote="KIT_EMOTE_TAUNT_WAR_CRY_1"},
	[210] = 	{female=true,	name="Odeur nauséabonde", 				itsAnimation="emote", 			emote="KIT_EMOTE_TAUNT_YOUSTINK_1"},

	[300] = 	{female=true,	name="Nettoyer sa tasse", 			itsAnimation="scenario", 		scenario="WORLD_HUMAN_BARTENDER_CLEAN_GLASS",		time=-1},
    [301] = 	{female=true,	name="Nettoyer une table", 			itsAnimation="scenario", 		scenario="WORLD_HUMAN_CLEAN_TABLE",					time=-1},
    [302] = 	{female=false,	name="Jouer de la trompette", 		itsAnimation="scenario", 		scenario="WORLD_HUMAN_TRUMPET",						time=-1},
    [303] = 	{female=false,	name="Jouer de la guitare", 			itsAnimation="scenario", 		scenario="WORLD_HUMAN_SIT_GUITAR",					time=-1},
    [304] = 	{female=false,	name="Se mettre à genoux", 					itsAnimation="scenario", 		scenario="SC_WORLD_HUMAN_KNEELING",					time=-1},
    [305] = 	{female=true,	name="Mains jointes", 					itsAnimation="scenario", 		scenario="WORLD_HUMAN_GRAVE_MOURNING",				time=-1},
    [306] = 	{female=true,	name="Prendre des notes", 	itsAnimation="scenario", 		scenario="world_human_write_notebook",				time=-1},
    [307] = 	{female=false,	name="Pisser", 					itsAnimation="scenario", 		scenario="world_human_pee",							time=-1},
	

    [500] = 	{female=true,	name="Danse 1", 				itsAnimation="animNorm", 		anim={"script_mp@emotes@dance@awkward@a@male@unarmed@full_looped", "action_alt1_lf"},					time=-1,		flag=1},
    [501] = 	{female=true,	name="Danse 2", 				itsAnimation="animNorm", 		anim={"script_mp@emotes@dance@carefree@a@male@unarmed@full_looped",	"action_alt1_mid_lf"},				time=-1,		flag=1},
    [502] = 	{female=true,	name="Danse 3", 				itsAnimation="animNorm", 		anim={"script_mp@emotes@dance@drunk@b@male@unarmed@full_looped", "action_lf"},							time=-1,		flag=1},
    [503] = 	{female=true,	name="Danse 4", 				itsAnimation="animNorm", 		anim={"script_mp@emotes@dance@carefree@a@male@unarmed@full_looped",	"action_lf"},						time=-1,		flag=1},
    [504] = 	{female=true,	name="Danse 5", 				itsAnimation="animNorm", 		anim={"script_mp@emotes@dance@carefree@b@male@unarmed@full_looped",	"action_alt1_rf"},					time=-1,		flag=1},
    [505] = 	{female=true,	name="Danse 6", 				itsAnimation="animNorm", 		anim={"script_mp@emotes@dance@graceful@a@male@unarmed@full_loopedd", "action_alt2_lf"},					time=-1,		flag=1},
    [506] = 	{female=true,	name="Danse 7", 				itsAnimation="animNorm", 		anim={"script_mp@emotes@dance@carefree@b@male@unarmed@full_looped", "loop"},							time=-1,		flag=1},
    [507] = 	{female=true,	name="Danse 8", 				itsAnimation="animNorm", 		anim={"script_mp@emotes@dance@drunk@a@male@unarmed@full_looped", "action_lf"},							time=-1,		flag=1},
    [508] = 	{female=true,	name="Danse 9", 				itsAnimation="animNorm", 		anim={"script_mp@emotes@dance@drunk@b@male@unarmed@full_looped", "action_alt1_rf"},						time=-1,		flag=1},
    [509] = 	{female=true,	name="Danse 10", 				itsAnimation="animNorm", 		anim={"script_mp@emotes@dance@drunk@b@male@unarmed@full_looped", "action_alt2_fl"},						time=-1,		flag=1},
    [510] = 	{female=true,	name="Danse 11", 				itsAnimation="animNorm", 		anim={"script_mp@emotes@dance@old@a@male@unarmed@full_looped", "loop"},									time=-1,		flag=1},
    [511] = 	{female=true,	name="Danse 12", 				itsAnimation="animNorm", 		anim={"script_mp@emotes@dance@wild@a@male@unarmed@full_looped", "action_alt1_back_fwd"},				time=-1,		flag=1},
    [512] = 	{female=true,	name="Danse 13", 				itsAnimation="animNorm", 		anim={"amb_misc@world_human_dancing@female_a@idle_c", "idle_g"},										time=-1,		flag=1},
    [513] = 	{female=true,	name="Tousser", 					itsAnimation="animNorm", 		anim={"amb_wander@upperbody_idles@miner@right_hand@male_a@idle_a", "idle_a"},							time=-1,		flag=1},
    [514] = 	{female=true,	name="Bénédiction", 					itsAnimation="animNorm", 		anim={"script_mp@last_round@photos", "pose1_m04"},														time=-1,		flag=25},
    [515] = 	{female=true,	name="Blessé 1", 				itsAnimation="animNorm", 		anim={"mech_loco_m@character@arthur@injured@left_shoulder@unarmed@_variations@fidgets", "fidget_a"},	time=-1,		flag=25},
    [516] = 	{female=true,	name="Blessé 2", 				itsAnimation="animNorm", 		anim={"mech_loco_m@character@arthur@injured@crouch@left_shoulder@unarmed@idle_outside", "idle"},		time=-1,		flag=25},
    [517] = 	{female=true,	name="Blessé 3", 				itsAnimation="animNorm", 		anim={"script_rc@dopn@ig@ig4_rsc2_enterdoctorsoffice", "ig4_edo_walktochair_arthur"},					time=-1,		flag=17},
    [518] = 	{female=true,	name="S'accrocher", 			itsAnimation="animNorm", 		anim={"script_proc@robberies@unapproved", "stand_prisoner_cell_idle_a"},								time=-1,		flag=1},
    [519] = 	{female=true,	name="Se rendre", 				itsAnimation="animNorm", 		anim={"script_mp@bounty@legendary@lbnik@ig@lbnik_ig3_bullettime", "on_knees_idle_hostage"},				time=-1,		flag=1},
    [520] = 	{female=true,	name="Assis 1", 					itsAnimation="animNorm", 		anim={"amb_rest_lean@world_human_lean_rail@male_a@lean@base", "base"},									time=-1,		flag=63},
    [521] = 	{female=true,	name="Assis 1", 					itsAnimation="animNorm", 		anim={"amb_camp@world_camp_sit_ground_stew@resting@male_a@idle_a", "idle_c"},							time=-1,		flag=1},
    [522] = 	{female=true,	name="Assis 2", 					itsAnimation="animNorm", 		anim={"amb_camp@world_camp_fire_sit_ground@male_a@trans", "sit_ground_trans_sit_ground_e"},				time=-1,		flag=1},
    [523] = 	{female=true,	name="Assis 3", 					itsAnimation="animNorm", 		anim={"amb_camp@world_camp_fire_sit_ground@male_c@idle_a", "idle_a"},									time=-1,		flag=1},
    [524] = 	{female=true,	name="Assis 4", 					itsAnimation="animNorm", 		anim={"amb_camp@world_camp_fire_sit_ground@female_a@idle_b", "idle_d"},									time=-1,		flag=1},
    [525] = 	{female=true,	name="Assis 5", 					itsAnimation="animNorm", 		anim={"amb_rest_sit@world_human_depressed_sit_ground@male_b@idle_a", "idle_a"},							time=-1,		flag=1},
    [526] = 	{female=true,	name="Assis 6", 					itsAnimation="animNorm", 		anim={"amb_camp@world_camp_fire_sit_ground@male_b@idle_a", "idle_a"},									time=-1,		flag=1},
    [527] = 	{female=true,	name="Assis 7", 					itsAnimation="animNorm", 		anim={"amb_camp@world_camp_fire_sit_ground@male_b@idle_a", "idle_b"},									time=-1,		flag=1},
    [528] = 	{female=true,	name="Assis 8", 					itsAnimation="animNorm", 		anim={"amb_camp@world_camp_sit_ground_stew@resting@male_a@idle_a", "idle_a"},							time=-1,		flag=1},
    [529] = 	{female=true,	name="Assis 9", 					itsAnimation="animNorm", 		anim={"amb_camp@world_camp_fire_tend_sit@add_logs@male_a@base", "base"},								time=-1,		flag=1},
    [530] = 	{female=true,	name="Assis 10",					itsAnimation="animNorm", 		anim={"script_rc@bch2@leadout@rsc_7", "end_loop_john"},													time=-1,		flag=1},
    [531] = 	{female=true,	name="Assis 11",					itsAnimation="animNorm", 		anim={"amb_generic@world_human_generic_sit_ground@legs_up@female_a@base", "base"},						time=-1,		flag=1},
    [532] = 	{female=true,	name="Assis 12",					itsAnimation="animNorm", 		anim={"script_rc@bch2@leadout@rsc_7", "end_loop_charles"},												time=-1,		flag=1},
    [533] = 	{female=true,	name="Dormir 1", 				itsAnimation="animNorm", 		anim={"amb_rest@world_human_sleep_ground@pillow@male_b@idle_a", "idle_b"},								time=-1,		flag=1},
    [534] = 	{female=true,	name="Dormir 2", 				itsAnimation="animNorm", 		anim={"amb_rest@world_human_sleep_ground@arm@female_a@idle_a", "idle_a"},								time=-1,		flag=1},
    [535] = 	{female=true,	name="Dormir 3", 				itsAnimation="animNorm", 		anim={"amb_rest@world_human_sleep_ground@arm@male_b@idle_c", "idle_h"},									time=-1,		flag=1},
    [536] = 	{female=true,	name="Dormir 4", 				itsAnimation="animNorm", 		anim={"amb_rest@prop_human_sleep_leanto_tent@front@female_a@trans", "a_trans_sleep_ground_arm_a"},		time=-1,		flag=1},
    [537] = 	{female=true,	name="Dormir 5", 				itsAnimation="animNorm", 		anim={"amb_camp@world_camp_fire_sit_ground@male_c@trans", "c_trans_recline_b"},							time=-1,		flag=1},
    [538] = 	{female=true,	name="Dormir 6",					itsAnimation="animNorm", 		anim={"script_rc@bch2@leadout@rsc_7", "end_loop_uncle"},												time=-1,		flag=1},
    [539] = 	{female=true,	name="Dormir 7",					itsAnimation="animNorm", 		anim={"script_rc@bch5@leadout@rsc4", "base_uncle"},														time=-1,		flag=1},
    [540] = 	{female=true,	name="Dormir 8",					itsAnimation="animNorm", 		anim={"amb_camp@world_camp_fire_sit_ground@recline@male_c@base", "base"},								time=-1,		flag=1},
    [541] = 	{female=true,	name="Adossé 1", 				itsAnimation="animNorm", 		anim={"amb_temp@world_human_leaning@male@wall@back@foot_up@react_shock","right"},						time=-1,		flag=1},
    [542] = 	{female=true,	name="Adossé 2", 				itsAnimation="animNorm", 		anim={"amb_rest_lean@world_human_lean@bar@read_newspaper@male_d@idle_a","idle_a"},						time=-1,		flag=1},
    [543] = 	{female=true,	name="Adossé 3", 				itsAnimation="animNorm", 		anim={"amb_camp@prop_camp_butcher@resting@deer@female_a@base", "base"},									time=-1,		flag=1},
    [544] = 	{female=true,	name="Adossé 4", 				itsAnimation="animNorm", 		anim={"amb_rest_lean@world_human_lean@post@left@female_a@idle_a", "idle_b"},							time=-1,		flag=1},
    [545] = 	{female=true,	name="Adossé 5", 				itsAnimation="animNorm", 		anim={"amb_rest_lean@world_human_lean@wall@right@male_b@idle_a", "idle_b"},								time=-1,		flag=1},
    [546] = 	{female=true,	name="Adossé 6", 				itsAnimation="animNorm", 		anim={"amb_rest_lean@world_human_lean@post@right@hand_planted@male_b@idle_b", "idle_d"},				time=-1,		flag=1},
    [547] = 	{female=true,	name="Adossé 7", 				itsAnimation="animNorm", 		anim={"amb_rest_lean@world_human_lean@wall@female_a@idle_b", "idle_d"},									time=-1,		flag=1},
    [548] = 	{female=true,	name="Adossé 8", 				itsAnimation="animNorm", 		anim={"amb_rest_lean@world_human_lean_fence_fwd_check_out_livestock@male_e@idle_c", "idle_g"},			time=-1,		flag=1},
    [549] = 	{female=true,	name="Adossé 9", 				itsAnimation="animNorm", 		anim={"amb_rest_lean@world_human_lean@wall@male_c@idle_b", "idle_f"},									time=-1,		flag=1},
    [550] = 	{female=true,	name="Adossé 10", 				itsAnimation="animNorm", 		anim={"amb_rest_lean@world_human_lean@post@right@female_a@idle_b", "idle_f"},							time=-1,		flag=1},
    [551] = 	{female=true,	name="Adossé 11", 				itsAnimation="animNorm", 		anim={"amb_rest_drunk@world_human_lean@railing@drinking@male_b@idle_a","idle_c"},						time=-1,		flag=1},
    [552] = 	{female=true,	name="Adossé 12", 				itsAnimation="animNorm", 		anim={"amb_rest_drunk@world_human_barcustomer@sober@no_drink@male_a@idle_a", "idle_a"},					time=-1,		flag=1},
    [553] = 	{female=true,	name="Adossé 13", 				itsAnimation="animNorm", 		anim={"script_common@shared_scenarios@seated@sheriff_desk@stand_desk@male_a@base", "base"},				time=-1,		flag=1},
    [554] = 	{female=true,	name="Adossé 14", 				itsAnimation="animNorm", 		anim={"script_story@ind2@leadout@ext", "exit_micah_player"},											time=-1,		flag=1},
    [555] = 	{female=true,	name="Adossé 15", 				itsAnimation="animNorm", 		anim={"amb_camp@world_camp_fire_standing@male_a@base", "base"},											time=-1,		flag=1},
    [556] = 	{female=true,	name="Adossé 16", 				itsAnimation="animNorm", 		anim={"cnv_camp@rcbvr@wnt@ccjhn2", "base_john"},														time=-1,		flag=1},
    [557] = 	{female=true,	name="Adossé 17", 				itsAnimation="animNorm", 		anim={"amb_rest_lean@world_human_lean@railing@male_b@base", "base"},									time=-1,		flag=1},
    [558] = 	{female=true,	name="Mains sur les hanches",			itsAnimation="animNorm", 		anim={"amb_rest@world_human_sternguy@male_a@base", "base"},												time=-1,		flag=25},
    [559] = 	{female=true,	name="Mains croisées 1",	itsAnimation="animNorm", 		anim={"amb_misc@world_human_waiting_impatient@male_d@base", "base"},									time=-1,		flag=25},
    [560] = 	{female=true,	name="Mains dans le dos",	itsAnimation="animNorm", 		anim={"amb_misc@world_human_stand_waiting@male_b@idle_a", "idle_b"},									time=-1,		flag=25},
    [561] = 	{female=true,	name="Bras croisées",			itsAnimation="animNorm", 		anim={"amb_misc@world_human_stare_stoic@male_a@base", "base"},											time=-1,		flag=25},
    [562] = 	{female=true,	name="Vomir 1",				itsAnimation="animNorm", 		anim={"amb_misc@world_human_vomit@male_a@idle_c", "idle_h"},											time=-1,		flag=25},
    [563] = 	{female=true,	name="Vomir 2",				itsAnimation="animNorm", 		anim={"amb_misc@world_human_vomit_kneel@male_a@idle_c", "idle_g"},										time=-1,		flag=25},
    [564] = 	{female=true,	name="Taper à la porte",						itsAnimation="animNorm", 		anim={"amb_misc@world_human_door_knock@male_a@idle_a", "idle_b"},										time=-1,		flag=25},
	[573] = 	{female=true,	name="Observer",				itsAnimation="animNorm", 		anim={"amb_work@world_human_inspect@male_a@base", "base"},												time=-1,		flag=1},
	[574] = 	{female=true,	name="Faire des ricochets",			itsAnimation="animNorm", 		anim={"amb_misc@world_human_skip_rocks@male_b@wip_base", "wip_base"},									time=-1,		flag=1},
	[575] = 	{female=true,	name="Tenir une malette 1",		itsAnimation="animNorm", 		anim={"script_rc@bwcg@leadout@rc2", "waitloop01_player"},												time=-1,		flag=25},
	[576] = 	{female=true,	name="Tenir une malette 2",		itsAnimation="animNorm", 		anim={"script_rc@bwcg@leadout@rc2", "waitloop01_player"},												time=-1,		flag=25},
    [577] = 	{female=true,	name="Mains jointes 2",	itsAnimation="animNorm", 		anim={"script_rc@cldn@leadout@rsc6", "idle_priest"},													time=-1,		flag=25},
    [578] = 	{female=true,	name="Adossé 18",				itsAnimation="animNorm", 		anim={"amb_rest_lean@world_human_lean@railing@smoking@male_b@idle_b","idle_e"},							time=-1,		flag=1},
    [579] = 	{female=true,	name="Se curer le nez",		itsAnimation="animNorm", 		anim={"ai_gestures@gen_male@standing@speaker@rt_hand", "neutral_fidget_rubnose_l_001"},					time=-1,		flag=1},

	[1000] = 	{female=true,	name="Jouer du violon", 					itsAnimation="animWithProp", 	anim={"ai_gestures@instruments@fiddle@standing@female@drunk", "fiddle_low_long_shorts_-1_02"},			time=-1,		flag=25, 			props={"p_fiddle01x", "PH_L_Hand", 0.0, 0.0, 0.0, 0.0, 0.0, 0.0}},
	[1001] = 	{female=true,	name="Accouder au bar 1", 					itsAnimation="animWithProp", 	anim={"script_story@gry1@ig@ig_2_takedowns@ig_2_arthur_takedown_drunk@idle_loops", "base_drunk"},		time=-1,		flag=25, 			props={"p_group_gamble_bottlewine01x", "skel_l_hand", 0.07, -0.04, 0.08, 252.0, 0.0, 0.0}},
    [1002] = 	{female=true,	name="Accouder au bar 2", 					itsAnimation="animWithProp", 	anim={"script_story@sal1@ig@sal1_ig1_drink", "arthur_long_drink_arthur"},								time=-1,		flag=1, 			props={"p_glass06x", "SKEL_R_Finger42", 0.03, -0.04, -0.02, 187.0, 0.0, 0.0}},
    [1003] = 	{female=true,	name="Taper au marteau", 					itsAnimation="animWithProp", 	anim={"amb_work@world_human_hammer@kneel@male_a@trans", "a_trans_a"},									time=-1,		flag=1, 			props={"p_hammer01x", "PH_R_Hand", 0.0, 0.0, 0.0, 0.0, 0.0, 0.0}},
    [1004] = 	{female=true,	name="Jouer de la Trompette 1",		itsAnimation="animWithProp", 	anim={"ai_gestures@instruments@trumpet@standing@140bpm", "upbeat_high_cen_003"},						time=-1,		flag=25, 			props={"p_trumpet01x", "PH_R_Hand", 0.0, 0.0, 0.0, 0.0, 0.0, 0.0}},
    [1005] = 	{female=true,	name="Play du Banjo 1",			itsAnimation="animWithProp", 	anim={"ai_gestures@instruments@banjo@seated@female@normal", "banjo_spine_0_hand_-1_02"},				time=-1,		flag=25, 			props={"s_banjosnakeskin01x", "PH_R_Hand", 0.0, 0.0, 0.0, 0.0, 0.0, 0.0}},
    [1006] = 	{female=true,	name="Play de la guitare 1",		itsAnimation="animWithProp", 	anim={"ai_gestures@instruments@guitar@seated@chair@120bpm", "upbeat_picking_strum_veryfast_rt_0_02"},	time=-1,		flag=25, 			props={"p_guitar01x", "PH_R_Hand", 0.0, 0.0, 0.0, 0.0, 0.0, 0.0}},
    [1007] = 	{female=true,	name="Play de la basse",			itsAnimation="animWithProp", 	anim={"ai_gestures@instruments@band_test", "db_playing"},												time=-1,		flag=1, 			props={"p_cs_contrabass01x", "PH_R_Hand", 0.0, 0.0, 0.0, 0.0, 0.0, 0.0}},
    [1008] = 	{female=true,	name="Porter un bébé",			itsAnimation="animWithProp", 	anim={"amb_camp@prop_camp_seat_chair@clean_rifle@female_a@react_look@loop@generic", "react_look_front_loop"},time=-1,		flag=25, 		props={"prop_stuntdoll_01", "PH_R_Hand", 0.0, 0.0, 0.0, 56.0, 203.0, -90.0}},
    [1009] = 	{female=true,	name="Compter des billets",			 	itsAnimation="animWithProp", 	anim={"amb_camp@prop_camp_seat_chair_table@clean_rifle@male_a@base", "base"},							time=-1,		flag=25, 			props={"p_moneystack01x", "PH_R_Hand", 0.06, 0.03, -0.01, 28.0, 0.0, 0.0}},
    [1010] = 	{female=true,	name="Porter du coton",				itsAnimation="animWithProp", 	anim={"mech_carry_box", "idle"},																		time=-1,		flag=25, 			props={"s_cottonginned01x", "PH_R_Hand", 0.0, -0.05, 0.0, 0.0, 0.0, 0.0}},
    [1011] = 	{female=true,	name="Pousser une brouette",				itsAnimation="animWithProp", 	anim={"mech_loco_m@character@beau_gray@carry@suitcase@idle", "idle"},									time=-1,		flag=25, 			props={"p_poopwheelbarrow02x", "MS_R_Pectoral", -0.65, 0.41, -0.95, 25.0, -27.0, -165.0}},
    [1012] = 	{female=true,	name="Paille dans la bouche",		itsAnimation="animWithProp", 	anim={"", ""},																							time=-1,		flag=25, 			props={"p_cs_haypiece01x", "skel_head", -0.014, 0.069, 0.009, 56.4, 900.0, 179.3}},
	[1013] = 	{female=true,	name="Fumer une pipe 1",			itsAnimation="animWithProp", 	anim={"script_mp@emotes@smoke_cigarette@female@unarmed@upper", "action_alt2"},							time=-1,		flag=25, 			props={"p_opiumpipe01x", "skel_r_hand", 0.1, -0.02, -0.06, 18.0, 78.0, -7.0}},
	[1014] = 	{female=true,	name="Fumer pipe 2",			itsAnimation="animWithProp", 	anim={"amb_rest_sit@world_human_sit_ground@smoke@male_b@idle_a", "idle_b"},								time=-1,		flag=1, 			props={"p_peacepipe01x", "skel_r_hand", -0.16, -0.12, -0.06, -58.0, -163.0, 241.0}},
	[1015] = 	{female=true,	name="Distribuer les journaux",	itsAnimation="animWithProp", 	anim={"amb_work@world_human_paper_sell@male_a@idle_a", "idle_c"},										time=-1,		flag=25, 			props={"p_newspaperlivestock01x", "SKEL_L_Finger00", 0.07, -0.02, 0.17, 86.0, -164.0, 5.0}},
	[1016] = 	{female=true,	name="Porter une boite 1",			itsAnimation="animWithProp", 	anim={"amb_wander@code_human_box_wander@male_a@base", "base"},											time=-1,		flag=25, 			props={"p_bottlecrate01x", "PH_R_Hand", 0.00, 0.00, -0.02, 0.0, 0.0, 0.0}},
	[1017] = 	{female=true,	name="Porter une boite 2",			itsAnimation="animWithProp", 	anim={"mech_loco_m@character@arthur@carry@crate_tnt@idle", "idle"},										time=-1,		flag=25, 			props={"p_cs_crateammo01x", "SKEL_L_Hand", 0.12, 0.08, 0.42, 280.0, 180.0, 410.0}},
	[1018] = 	{female=true,	name="Lire les journaux",			itsAnimation="animWithProp", 	anim={"amb_rest_lean@world_human_lean@barrel@read_newspaper@male_a@base", "base"},						time=-1,		flag=25, 			props={"p_newspaper01x", "SKEL_L_Finger00", 0.07, -0.02, 0.17, 86.0, -164.0, 5.0}},
	[1019] = 	{female=true,	name="Tenir un parapluie",		itsAnimation="animWithProp", 	anim={"amb_rest_sit@prop_human_seat_bench@parasol@female_a@wip_base","wip_base"},						time=-1,		flag=25, 			props={"p_parasol02x", "skel_r_hand", 0.07, -0.04, -0.02, -90.0, 0.0, 0.0}},
	[1020] = 	{female=true,	name="Tenir une torche",			itsAnimation="animWithProp", 	anim={"mech_doors@arms@torch", "mainhand_idle"},														time=-1,		flag=25, 			props={"s_interact_torch", "PH_R_Hand", 0.04, 0.08, -0.02, -91.0, 10.0, -10.0}},
	[1021] = 	{female=true,	name="Lire une carte",				itsAnimation="animWithProp", 	anim={"mech_inspection@mini_map@base", "hold"},															time=-1,		flag=25, 			props={"mp001_mp_map01x", "XH_L_Hand00", -0.06, 0.12, 0.36, -10.0, -120.0, -40.0}},
	[1022] = 	{female=true,	name="Porter une planche",				itsAnimation="animWithProp", 	anim={"mech_loco_m@character@dutch@carry@suppse couchers@idle", "idle"},										time=-1,		flag=25, 			props={"p_woodplank04x", "PH_L_Hand", 0.03, 0.11, 0.06, 86.0, 0.0, 4.0}},
	[1023] = 	{female=true,	name="Porter un sac",				itsAnimation="animWithProp", 	anim={"mech_loco_m@generic@carry@ped@idle", "idle"},													time=-1,		flag=25, 			props={"p_sandbags03x", "SKEL_L_Hand", 0.02, 0.13, 0.28, 2.0, 139.0, 0.0}},
	[1024] = 	{female=true,	name="Porter une malette",			itsAnimation="animWithProp", 	anim={"mech_loco_m@character@beau_gray@carry@suitcase@idle", "idle"},									time=-1,		flag=25, 			props={"p_boxmedsuitcase01x", "PH_L_Hand", 0.01, 0.16, -0.1, 271.0, 0.0, 173.0}},
	[1025] = 	{female=true,	name="Passer le balais 1",			itsAnimation="animWithProp", 	anim={"amb_work@world_human_broom@working@male_b@base", "base"},										time=-1,		flag=25, 			props={"p_broom04x", "PH_R_Hand", 0.0, 0.0, 0.0, 0.0, 0.0, 0.0}},
	[1026] = 	{female=true,	name="Passer le balais 2",			itsAnimation="animWithProp", 	anim={"amb_work@world_human_broom@working@female_b@idle_a", "idle_b"},									time=-1,		flag=25, 			props={"p_broom02x", "PH_R_Hand", 0.0, -0.03, 0.0, -3.0, 0.0, 0.0}},
	[1027] = 	{female=true,	name="Tenir une bougie",				itsAnimation="animWithProp", 	anim={"mech_inspection@cigarette_card@base", "hold"},													time=-1,		flag=25, 			props={"p_candlestick03x", "PH_L_Hand", 0.06, -0.08, -0.03, -42.0, -16.0, -16.0}},
	[1028] = 	{female=true,	name="Utiliser une fourche",		itsAnimation="animWithProp", 	anim={"amb_work@world_human_pitch_hay@male_a@pitch@idle_a", "idle_a"},									time=-1,		flag=1, 			props={"p_pitchfork01x", "PH_R_Hand", -0.04, -0.07, -0.03, -95.0, -230.0, -38.0}},
	[1029] = 	{female=true,	name="Utiliser un rateau",				itsAnimation="animWithProp", 	anim={"amb_work@world_human_farmer_rake@male_a@idle_a", "idle_a"},										time=-1,		flag=1, 			props={"p_rake02x", "PH_R_Hand", 0.0, 0.0, 0.19, 0.0, 0.0, 0.0}},
	[1030] = 	{female=true,	name="Semer des graines",					itsAnimation="animWithProp", 	anim={"amb_work@world_human_feed_chickens@female_a@base", "base"},										time=-1,		flag=1, 			props={"p_feedbag01bx", "PH_L_Hand", 0.0, 0.0, 0.0, 0.0, 0.0, 0.0}},
	[1031] = 	{female=true,	name="Porter une boite 3",			itsAnimation="animWithProp", 	anim={"amb_wander@code_human_box_wander@male_a@base", "base"},											time=-1,		flag=25, 			props={"p_12moonshinecrate01", "PH_R_Hand", 0.0, 0.0, 0.0, 0.0, 0.0, -87.0}},
	[1032] = 	{female=true,	name="Pousser un landau",			itsAnimation="animWithProp", 	anim={"veh_common@wheeled@front@fr@in_seat@male@fidgets", "idle_c"},									time=-1,		flag=25, 			props={"p_babystroller", "MH_ApronFront_PT_000", -0.03, 0.99, -0.30, 0.0, 0.0, 0.0}},
	[1033] = 	{female=true,	name="Boire un canon",				itsAnimation="animWithProp", 	anim={"script_re@moonshine_camp@return_taste@trans", "good_male_b"},									time=-1,		flag=25, 			props={"p_jug01x", "PH_R_Hand", 0.0, 0.0, 0.0, 0.0, 0.0, 0.0}},
	[1034] = 	{female=true,	name="Bouquet",					itsAnimation="animWithProp", 	anim={"mech_inspection@generic@lh@base","hold"},														time=-1,		flag=25, 			props={"mp006_p_mp_potflowerarng01x", "SKEL_L_Finger11", 0.0, -0.04, -0.15, 0.0, 0.0, 0.0}},
	[2000] =	{female=true,	name="Creeping",				itsAnimation="lying"},
	[2100] = 	{female=true,	name="Danse partagée 1",		itsAnimation="animShared", 		animDict="cnv_camp@rchso@cnv@ccdtc33@player_karen", animName="arthur_dance_loop",delay1=500, 			animDict2="cnv_camp@rchso@cnv@ccdtc33@player_karen", animName2="karen_dance_loop",delay2=500,		time=-1,		flag=1, offset=vector4(-0.05, 0.55, 0.0, 205.0)},
	[2101] = 	{female=true,	name="Partagé se coucher 1",			itsAnimation="animShared", 		animDict="amb_rest_sit@world_human_sit_ground@fall_asleep@female_a@sleeping@base", animName="base",delay1=500, 			animDict2="amb_rest@world_human_sleep_ground@pillow@female_a@idle_a", animName2="idle_a",delay2=500,		time=-1,		flag=1, offset=vector4(0.40, -0.55, 0.0, 110.0)},
	[2102] = 	{female=true,	name="Partagé se coucher 2",			itsAnimation="animShared", 		animDict="amb_rest_sit@world_human_sit_ground@fall_asleep@female_a@sleeping@base", animName="base",delay1=500, 			animDict2="amb_camp@world_camp_jack_es_sleep@male_a@base", animName2="base",delay2=500,		time=-1,		flag=1, offset=vector4(0.40, -0.55, 0.0, 110.0)},
	[2103] = 	{female=true,	name="Partagé se coucher 4",			itsAnimation="animShared", 		animDict="amb_rest_sit@world_human_sit_ground@fall_asleep@male_a@sleeping@base", animName="base",delay1=500, 			animDict2="amb_rest@world_human_sleep_ground@pillow@female_a@idle_a", animName2="idle_a",delay2=500,		time=-1,		flag=1, offset=vector4(0.10, -0.85, 0.0, 30.0)},
	[2104] = 	{female=true,	name="Partagé se coucher 5",			itsAnimation="animShared", 		animDict="amb_rest_sit@world_human_sit_ground@fall_asleep@male_a@sleeping@base", animName="base",delay1=500, 			animDict2="amb_camp@world_camp_jack_es_sleep@male_a@base", animName2="base",delay2=500,		time=-1,		flag=1, offset=vector4(0.10, -0.95, -0.0, 30.0)},
	[2105] = 	{female=true,	name="Partagé câlin 1",			itsAnimation="animShared", 		animDict="mech_carry_box", animName="idle",delay1=500, 			animDict2="mech_carry_box", animName2="idle",delay2=500,		time=-1,		flag=1, offset=vector4(-0.00, 0.35, 0.0, 190.0)},
	[2106] = 	{female=true,	name="Partagé câlin 2",			itsAnimation="animShared", 		animDict="mech_loco_m@generic@carry@box@front@idle", animName="idle",delay1=500, 			animDict2="mech_loco_m@generic@carry@box@front@idle", animName2="idle",delay2=500,		time=-1,		flag=1, offset=vector4(-0.00, 0.12, 0.0, 180.0)},


	[2500] = 	{female=true,	name="Démarche normale",				    itsAnimation="walkingStyle", 	walkAnim="MP_Style_Casual"},
	[2501] = 	{female=true,	name="Démarche fou",				    itsAnimation="walkingStyle", 	walkAnim="MP_Style_Crazy"},
	[2502] = 	{female=true,	name="Démarche ivre",				    itsAnimation="walkingStyle", 	walkAnim="mp_style_drunk"},
	[2503] = 	{female=true,	name="Démarche fier",				itsAnimation="walkingStyle", 	walkAnim="MP_Style_EasyRider"},
	[2504] = 	{female=true,	name="Démarche flamboyante",				itsAnimation="walkingStyle", 	walkAnim="MP_Style_Flamboyant"},
	[2505] = 	{female=true,	name="Démarche sûr de soi",				itsAnimation="walkingStyle", 	walkAnim="MP_Style_Greenhorn"},
	[2506] = 	{female=true,	name="Démarche As de la gachette",				itsAnimation="walkingStyle", 	walkAnim="MP_Style_Gunslinger"},
	[2507] = 	{female=true,	name="Démarche Inquisitive",				itsAnimation="walkingStyle", 	walkAnim="mp_style_inquisitive"},
	[2508] = 	{female=true,	name="Démarche Refined",				    itsAnimation="walkingStyle", 	walkAnim="MP_Style_Refined"},
	[2509] = 	{female=true,	name="Démarche discrète",				itsAnimation="walkingStyle", 	walkAnim="MP_Style_SilentType"},
	[2510] = 	{female=true,	name="Démarche Veteran",				    itsAnimation="walkingStyle", 	walkAnim="MP_Style_Veteran"},

	-- [1] = {female=true, name="TEST ANIMACE PROP", itsAnimation="animWithProp", animDict="amb_misc@world_human_twnrec_funeral@wip_base@female_c", animName="base", time=1000, flag=25, props={"p_beefstew_spoon01x", "PH_R_Hand", 0.0, 0.0, 0.0, 0.0, 0.0, 0.0}},
    -- [2] = {female=true, name="TEST ANIMACE", itsAnimation="animNorm", animDict="amb_misc@world_human_twnrec_funeral@wip_base@female_c", animName="base", time=1000, flag=25},
    -- [3] = {female=true, name="TEST SCENARIO", itsAnimation="scenario", scenario="WORLD_HUMAN_SCENARIO", time=1000},

}




