comp_cart = {
		['extras'] = {
            {category= 'extras', hash= 0},
            {category= 'extras',hash= 1},
            {category= 'extras',hash= 2},
            {category= 'extras',hash= 3},
            {category= 'extras',hash= 4},
            {category= 'extras',hash= 5},
            {category= 'extras',hash= 6},
            {category= 'extras',hash= 7},
            {category= 'extras',hash= 8},
            {category= 'extras',hash= 9},
            {category= 'extras',hash= 10},
            {category= 'extras',hash= 11},
            {category= 'extras',hash= 12},
            {category= 'extras',hash= 13},
            {category= 'extras',hash= 14},
            {category= 'extras',hash= 15},
            {category= 'extras',hash= 16},
            {category= 'extras',hash= 17},
            {category= 'extras',hash= 18},
            },
        ['tints'] = {
            {category= 'tints', hash= 0},
            {category= 'tints',hash= 1},
            {category= 'tints',hash= 2},
            {category= 'tints',hash= 3},
            {category= 'tints',hash= 4},
            {category= 'tints',hash= 5},
            {category= 'tints',hash= 6},
            {category= 'tints',hash= 7},
            {category= 'tints',hash= 8},
            {category= 'tints',hash= 9},
            {category= 'tints',hash= 10},
            {category= 'tints',hash= 11},
            {category= 'tints',hash= 12},
            {category= 'tints',hash= 13},
            {category= 'tints',hash= 14},
            {category= 'tints',hash= 15},
            {category= 'tints',hash= 16},
            {category= 'tints',hash= 17},
            {category= 'tints',hash= 18},
            {category= 'tints',hash= 19},
            {category= 'tints',hash= 20},
            {category= 'tints',hash= 21},
            {category= 'tints',hash= 22},
            {category= 'tints',hash= 23},
            {category= 'tints',hash= 24},
            {category= 'tints',hash= 25},
            {category= 'tints',hash= 26},
            {category= 'tints',hash= 27},
            {category= 'tints',hash= 28},
            {category= 'tints',hash= 29},
            },
        ['liveries'] = {
            {category= 'liveries', hash= 0},
            {category= 'liveries',hash= 1},
            {category= 'liveries',hash= 2},
            {category= 'liveries',hash= 3},
            {category= 'liveries',hash= 4},
            {category= 'liveries',hash= 5},
            {category= 'liveries',hash= 6},
            {category= 'liveries',hash= 7},
            {category= 'liveries',hash= 8},
            {category= 'liveries',hash= 9},
            {category= 'liveries',hash= 10},
            {category= 'liveries',hash= 11},
            {category= 'liveries',hash= 12},
            {category= 'liveries',hash= 13},
            {category= 'liveries',hash= 14},
            {category= 'liveries',hash= 15},
            {category= 'liveries',hash= 16},
            {category= 'liveries',hash= 17},
            {category= 'liveries',hash= 18},
            {category= 'liveries',hash= 19},
            {category= 'liveries',hash= 20},
            {category= 'liveries',hash= 21},
            {category= 'liveries',hash= 22},
            {category= 'liveries',hash= 23},
            {category= 'liveries',hash= 24},
            {category= 'liveries',hash= 25},
            {category= 'liveries',hash= 26},
            {category= 'liveries',hash= 27},
            {category= 'liveries',hash= 28},
            {category= 'liveries',hash= 29},
            {category= 'liveries',hash= 30},
            },
}
cart_props = {           
    ["armoredCar01x"] = {
        {category= 'propsets',hash= 0x3633F226},
    },

    ["armoredCar03x"] = {
        {category= 'propsets',hash= 0x61C404D4},
    },


    ["cart01"] = {
        {category = 'propsets',hash = 0x4CF7280B},
        {category = 'propsets',hash = 0x3AC590FD},
        {category = 'propsets',hash = 0xE93A8CA4},
        {category = 'propsets',hash = 0xB6E12589},
        {category = 'propsets',hash = 0x40A1D17D},
        {category = 'propsets',hash = 0x1AD30903},
        {category = 'propsets',hash = 0x77363629},
        {category = 'propsets',hash = 0x629D0CF7},
        {category = 'propsets',hash = 0xCC98E0ED},
    },

    ["cart02"] = {
        {category = 'propsets',hash = 0xB5BA4773},
        {category = 'propsets',hash = 0x7F44711B},
        {category = 'propsets',hash = 0x727D869F},
        {category = 'propsets',hash = 0xDD24C8A3},
        {category = 'propsets',hash = 0x3038C255},
    },

    ["cart03"] = {
        {category = 'propsets',hash = 0xCE541308},
        {category = 'propsets',hash = 0x8731AF58},
        {category = 'propsets',hash = 0xD393E64E},
        {category = 'propsets',hash = 0xF9C47DEB},
        {category = 'propsets',hash = 0x25797E29},
        {category = 'propsets',hash = 0x72CD835A},
        {category = 'propsets',hash = 0xE4481E62},
        {category = 'propsets',hash = 0xF67E42CE},
        {category = 'propsets',hash = 0x22B6A11},
    },

    ["cart04"] = {
        {category = 'propsets',hash = 0x35179A9D},
        {category = 'propsets',hash = 0x3AC015A6},
        {category = 'propsets',hash = 0x5268EA7C},
        {category = 'propsets',hash = 0x6428D8AF},
        {category = 'propsets',hash = 0xC9257141},
        {category = 'propsets',hash = 0x801CE702},
        {category = 'propsets',hash = 0x6DA1420F},
    },

    ["cart06"] = {
        {category = 'propsets',hash = 0x3A9ED0DE},
        {category = 'propsets',hash = 0x1CE5226B},
        {category = 'propsets',hash = 0x5DDFBD84},
        {category = 'propsets',hash = 0x61D350BF},
        {category = 'propsets',hash = 0x22703188},
        {category = 'propsets',hash = 0xF45C555D},
    },

    ["cart07"] = {
        {category = 'propsets',hash = 0x3A11989E},
        {category = 'propsets',hash = 0x764E4965},
        {category = 'propsets',hash = 0xE914A2E9},
        {category = 'propsets',hash = 0x9CCB819E},
        {category = 'propsets',hash = 0xD5CA5F25},
        {category = 'propsets',hash = 0xFEA6B0E1},
    },

    ["cart08"] = {
        {category = 'propsets',hash = 0xC254F2B4},
        {category = 'propsets',hash = 0x3236A3F4},
        {category = 'propsets',hash = 0xE02B784E},
        {category = 'propsets',hash = 0x950116B},
        {category = 'propsets',hash = 0xD4DEB2DC},
        {category = 'propsets',hash = 0x89F39D07},
    },

    ["coach2"] = {
        {category = 'propsets',hash = 0x3F234E85},
        {category = 'propsets',hash = 0xA6F5543},
        {category = 'propsets',hash = 0x8767C891},
        {category = 'propsets',hash = 0x7A10FCE3},
    },

    ["ArmySupplyWagon"] = {
        {category = 'propsets',hash = 0x939F555B},
    },

    ["chuckwagon000x"] = {
        {category = 'propsets',hash = 0x22B8797C},
        {category = 'propsets',hash = 0x7E1804F},
        {category = 'propsets',hash = 0x7F27A22C},
        {category = 'propsets',hash = 0x5D708834},
        {category = 'propsets',hash = 0x243532DE},
        {category = 'propsets',hash = 0xC975C565},
        {category = 'propsets',hash = 0xB42E9AD7},
        {category = 'propsets',hash = 0x193164C3},
        {category = 'propsets',hash = 0xAA63D51E},
        {category = 'propsets',hash = 0x207A0349},
        {category = 'propsets',hash = 0x4783B51},
        {category = 'propsets',hash = 0x49B98405},
        {category = 'propsets',hash = 0x9DD78F86},
        {category = 'propsets',hash = 0x564F5387},
        {category = 'propsets',hash = 0x4EFDAD66},
        {category = 'propsets',hash = 0x5FAAA6C4},
        {category = 'propsets',hash = 0xFC0AD95F},
        {category = 'propsets',hash = 0x428B1F8},
        {category = 'propsets',hash = 0xEC3679AF},
        {category = 'propsets',hash = 0x6C059B49},
        {category = 'propsets',hash = 0x6888C6E8},
        {category = 'propsets',hash = 0x537CFB83},
        {category = 'propsets',hash = 0xF3A5017F},
        {category = 'propsets',hash = 0xC8EEAC13},
        {category = 'propsets',hash = 0xC0531DF7},
        {category = 'propsets',hash = 0x27A013C0},
        {category = 'propsets',hash = 0x2758AD27},
        {category = 'propsets',hash = 0x329A24A5},
        {category = 'propsets',hash = 0xE3DCDE2E},
        {category = 'propsets',hash = 0xEEA5F3C0},
        {category = 'propsets',hash = 0xC89D27B3},
        {category = 'propsets',hash = 0xD6F7C468},
        {category = 'propsets',hash = 0x291C68B4},
        {category = 'propsets',hash = 0x36363C1B},
        {category = 'propsets',hash = 0x4458D860},
        {category = 'propsets',hash = 0x12FE75AC},
        {category = 'propsets',hash = 0x20D6115B},
        {category = 'propsets',hash = 0x357D990E},
        {category = 'propsets',hash = 0x811DD1C0},
    },

    ["supplywagon"] = {
        {category = 'propsets',hash = 0xE5512C02},
        {category = 'propsets',hash = 0xD487BC1E},
        {category = 'propsets',hash = 0x29D71B3},
        {category = 'propsets',hash = 0xC2873038},
        {category = 'propsets',hash = 0xD8234831},
        {category = 'propsets',hash = 0xA36612B9},
        {category = 'propsets',hash = 0xF45D7693},
    },


    ["coal_wagon"] = {
        {category = 'propsets',hash = 0xFB07EB8F},
    },

    ["chuckwagon002x"] = {
        {category = 'propsets',hash = 0x5F8D0C3},
        {category = 'propsets',hash = 0x87D4B9EB},
        {category = 'propsets',hash = 0x3E43C586},
        {category = 'propsets',hash = 0xC367BF75},
        {category = 'propsets',hash = 0xDB2731C0},
        {category = 'propsets',hash = 0xCD13AC0},
        {category = 'propsets',hash = 0xF8D712CC},
        {category = 'propsets',hash = 0xD6F6CF0C},
        {category = 'propsets',hash = 0xEC3679AF},
        {category = 'propsets',hash = 0x6C059B49},
        {category = 'propsets',hash = 0x6888C6E8},
        {category = 'propsets',hash = 0x537CFB83},
        {category = 'propsets',hash = 0xF3A5017F},
        {category = 'propsets',hash = 0xC8EEAC13},
        {category = 'propsets',hash = 0xC0531DF7},
        {category = 'propsets',hash = 0x27A013C0},
        {category = 'propsets',hash = 0x2758AD27},
        {category = 'propsets',hash = 0x329A24A5},
        {category = 'propsets',hash = 0xE3DCDE2E},
        {category = 'propsets',hash = 0xEEA5F3C0},
        {category = 'propsets',hash = 0xC89D27B3},
        {category = 'propsets',hash = 0xD6F7C468},
        {category = 'propsets',hash = 0x291C68B4},
        {category = 'propsets',hash = 0x36363C1B},
        {category = 'propsets',hash = 0x4458D860},
        {category = 'propsets',hash = 0x12FE75AC},
        {category = 'propsets',hash = 0x20D6115B},
        {category = 'propsets',hash = 0x357D990E},
        {category = 'propsets',hash = 0x811DD1C0},
    },


    ["stagecoach001x"] = {
        {category = 'propsets',hash = 0xBBD6A694},
        {category = 'propsets',hash = 0xA9A10229},
    },

    ["stagecoach002x"] = {
        {category = 'propsets',hash = 0xFDF568AB},
        {category = 'propsets',hash = 0xF03ACD36},
        {category = 'propsets',hash = 0xC5F23B79},
    },

    ["stagecoach003x"] = {
        {category = 'propsets',hash = 0x98FC2780},
    },

    ["stagecoach004x"] = {
        {category = 'propsets',hash = 0xCD4368AC},
        {category = 'propsets',hash = 0xD49DDF3F},
        {category = 'propsets',hash = 0xC5C6E96E},
        {category = 'propsets',hash = 0x10771F57},
        {category = 'propsets',hash = 0x1DF47A07},
    },

    ["stagecoach005x"] = {
        {category = 'propsets',hash = 0xD184F14C},
        {category = 'propsets',hash = 0xC1EA5217},
    },

    ["stagecoach006x"] = {
        {category = 'propsets',hash = 0x454477E7},
        {category = 'propsets',hash = 0x5D8DA875},
    },

    ["wagon02x"] = {
        {category = 'propsets',hash = 0xB4D0151D},
        {category = 'propsets',hash = 0x9DD78F86},
        {category = 'propsets',hash = 0xC5F9270F},
        {category = 'propsets',hash = 0xC30DA298},
        {category = 'propsets',hash = 0xC9FC1491},
        {category = 'propsets',hash = 0xDB8E07F6},
        {category = 'propsets',hash = 0x51038076},
        {category = 'propsets',hash = 0x3020218E},
        {category = 'propsets',hash = 0xEBF664DC},
        {category = 'propsets',hash = 0x274ACFC},
        {category = 'propsets',hash = 0xC31C4EE9},
        {category = 'propsets',hash = 0xD2BA20F0},
        {category = 'propsets',hash = 0x8A85012F},
        {category = 'propsets',hash = 0xEB6727ED},
        {category = 'propsets',hash = 0x140DA997},
        {category = 'propsets',hash = 0xD99C4EF0},
        {category = 'propsets',hash = 0x6104E12A},
        {category = 'propsets',hash = 0x8416144E},
        {category = 'propsets',hash = 0x9CEC8AB5},
        {category = 'propsets',hash = 0xA6CA0F4},
        {category = 'propsets',hash = 0x79CDDA25},
        {category = 'propsets',hash = 0x6E31C44D},
        {category = 'propsets',hash = 0xB7DB6DA7},
        {category = 'propsets',hash = 0xC3BE42BB},
        {category = 'propsets',hash = 0x3CCEB844},
        {category = 'propsets',hash = 0xBE99FB24},
        {category = 'propsets',hash = 0xE2FD95D3},
        {category = 'propsets',hash = 0x4B141B6E},
        {category = 'propsets',hash = 0x9DC4AF84},
        {category = 'propsets',hash = 0x57AAE511},
        {category = 'propsets',hash = 0xA01E8A40},
        {category = 'propsets',hash = 0xAB6DDB05},
        {category = 'propsets',hash = 0x9ED193C3},
        {category = 'propsets',hash = 0xE79A3856},
        {category = 'propsets',hash = 0xF6AA1E52},
        {category = 'propsets',hash = 0xCEFFB06E},
        {category = 'propsets',hash = 0xA215D69B},
        {category = 'propsets',hash = 0xAB49E903},
        {category = 'propsets',hash = 0xEC3679AF},
        {category = 'propsets',hash = 0x6C059B49},
        {category = 'propsets',hash = 0x6888C6E8},
        {category = 'propsets',hash = 0x537CFB83},
        {category = 'propsets',hash = 0xF3A5017F},
        {category = 'propsets',hash = 0xC8EEAC13},
        {category = 'propsets',hash = 0xC0531DF7},
        {category = 'propsets',hash = 0x27A013C0},
        {category = 'propsets',hash = 0x2758AD27},
        {category = 'propsets',hash = 0x329A24A5},
        {category = 'propsets',hash = 0xE3DCDE2E},
        {category = 'propsets',hash = 0xEEA5F3C0},
        {category = 'propsets',hash = 0xC89D27B3},
        {category = 'propsets',hash = 0xD6F7C468},
        {category = 'propsets',hash = 0x291C68B4},
        {category = 'propsets',hash = 0x36363C1B},
        {category = 'propsets',hash = 0x4458D860},
        {category = 'propsets',hash = 0x12FE75AC},
        {category = 'propsets',hash = 0x20D6115B},
        {category = 'propsets',hash = 0x357D990E},
        {category = 'propsets',hash = 0x811DD1C0},
    },

    ["wagon04x"] = {
        {category = 'propsets',hash = 0xB4D0151D},
        {category = 'propsets',hash = 0xC5F9270F},
        {category = 'propsets',hash = 0xC30DA298},
        {category = 'propsets',hash = 0x87FA4581},
        {category = 'propsets',hash = 0x7E6FD57E},
        {category = 'propsets',hash = 0xB62CEA16},
        {category = 'propsets',hash = 0xEF865B68},
        {category = 'propsets',hash = 0xE4EFAC64},
        {category = 'propsets',hash = 0x27D2B51B},
        {category = 'propsets',hash = 0x279508B1},
        {category = 'propsets',hash = 0x6683A1BE},
        {category = 'propsets',hash = 0x369DDE3F},
        {category = 'propsets',hash = 0x369DDE3F},
        {category = 'propsets',hash = 0xF15BC5DC},
        {category = 'propsets',hash = 0xA13CB21A},
        {category = 'propsets',hash = 0x8CCC893A},
        {category = 'propsets',hash = 0x7EFEED9F},
        {category = 'propsets',hash = 0xEC3679AF},
        {category = 'propsets',hash = 0x6C059B49},
        {category = 'propsets',hash = 0x6888C6E8},
        {category = 'propsets',hash = 0x537CFB83},
        {category = 'propsets',hash = 0xF3A5017F},
        {category = 'propsets',hash = 0xC8EEAC13},
        {category = 'propsets',hash = 0xC0531DF7},
        {category = 'propsets',hash = 0x27A013C0},
        {category = 'propsets',hash = 0x2758AD27},
        {category = 'propsets',hash = 0x329A24A5},
        {category = 'propsets',hash = 0xE3DCDE2E},
        {category = 'propsets',hash = 0xEEA5F3C0},
        {category = 'propsets',hash = 0xC89D27B3},
        {category = 'propsets',hash = 0xD6F7C468},
        {category = 'propsets',hash = 0x291C68B4},
        {category = 'propsets',hash = 0x36363C1B},
        {category = 'propsets',hash = 0x4458D860},
        {category = 'propsets',hash = 0x12FE75AC},
        {category = 'propsets',hash = 0x20D6115B},
        {category = 'propsets',hash = 0x357D990E},
        {category = 'propsets',hash = 0x811DD1C0},
        {category = 'propsets',hash = 0x29978F8B},
    },

    ["wagon05x"] = {
        {category = 'propsets',hash = 0x434A419},
        {category = 'propsets',hash = 0x7913A9CA},
        {category = 'propsets',hash = 0xB4D0151D},
        {category = 'propsets',hash = 0xC5F9270F},
        {category = 'propsets',hash = 0xC30DA298},
        {category = 'propsets',hash = 0x98298374},
        {category = 'propsets',hash = 0x6A48BB59},
        {category = 'propsets',hash = 0xE1A5CB17},
        {category = 'propsets',hash = 0x6AE80AD1},
        {category = 'propsets',hash = 0xDD5D9638},
        {category = 'propsets',hash = 0xE2DCC8AE},
        {category = 'propsets',hash = 0xFECFB4A},
        {category = 'propsets',hash = 0xDE15731A},
        {category = 'propsets',hash = 0xE9A3AC69},
        {category = 'propsets',hash = 0x7A648A97},
        {category = 'propsets',hash = 0xA6597D73},
        {category = 'propsets',hash = 0x35DEDAC3},
        {category = 'propsets',hash = 0x145D7845},
        {category = 'propsets',hash = 0xF69B589D},
        {category = 'propsets',hash = 0xED7E9519},
        {category = 'propsets',hash = 0x6DADCA54},
        {category = 'propsets',hash = 0x9CE3F9D1},
        {category = 'propsets',hash = 0xAE8D9D24},
        {category = 'propsets',hash = 0xC343C690},
        {category = 'propsets',hash = 0xD4F9E9FC},
        {category = 'propsets',hash = 0xE3F1885B},
        {category = 'propsets',hash = 0xECB299EA},
    },

    ["wagon06x"] = {
        {category = 'propsets',hash = 0xC07425C},
        {category = 'propsets',hash = 0x1BCDC2E},
        {category = 'propsets',hash = 0x7C7F5DA8},
        {category = 'propsets',hash = 0x8E92A2BF},
        {category = 'propsets',hash = 0x84B48F03},
        {category = 'propsets',hash = 0xC970987A},
    },

    ["wagonDairy01x"] = {
        {category = 'propsets',hash = 0xF9A15939},
    },

    ["utilliwag"] = {
        {category = 'propsets',hash = 0x7704DA65},
        {category = 'propsets',hash = 0x4DDD3EF3},
        {category = 'propsets',hash = 0xFB1F4FA0},
        {category = 'propsets',hash = 0xC5F47022},
        {category = 'propsets',hash = 0x8F3DE86A},
        {category = 'propsets',hash = 0x3AEECCF7},
        {category = 'propsets',hash = 0x44F69E63},
        {category = 'propsets',hash = 0x5B113D37},
        {category = 'propsets',hash = 0x96ABCF44},
        {category = 'propsets',hash = 0xEA068C68},
        {category = 'propsets',hash = 0xD80E644C},
        {category = 'propsets',hash = 0xA16276E5},
        {category = 'propsets',hash = 0x8E93D148},
        {category = 'propsets',hash = 0xC9806D4D},
    },

    ["gatchuck"] = {
        {category = 'propsets',hash = 0x8F3DE86A},
        {category = 'propsets',hash = 0xCF747230},
    },

}