AnimConfig = {}
AnimConfig.Radius = 250.0
AnimConfig.Animations = {
    ["conveyor-top"] = {
        dict = "props_misc@annesburg_coal",
        anim = "conveyor01x_full",
        model = "p_annconveyor01x",
    },
    ["conveyor-mid-slide"] = {
        dict = "props_misc@annesburg_coal",
        anim = "annconvmid1x_full",
        model = "p_annconvmid1x_belt",
    },
    ["conveyor-mid"] = {
        dict = "props_misc@annesburg_coal",
        anim = "annconvey03_full",
        model = "p_annconveyor03x",
    },
    ["conveyor-lower"] = {
        dict = "props_misc@annesburg_coal",
        anim = "annconvey04_full",
        model = "p_annconveyor04x",
    },
    ["conveyor-sifter"] = {
        dict = "props_misc@annesburg_coal",
        anim = "annsifter01_full",
        model = "p_annsifter01x",
    },
    ["conveyor-steamengine"] = {
        dict = "props_misc@annesburg_coal",
        anim = "steameng01_full",
        model = "p_annsteameng01x",
    },
    ["conveyor-coalbin"] = {
        dict = "props_misc@annesburg_coal",
        anim = "coalbin01_full",
        model = "p_anncoalbin01x",
    },
    ["conveyor-pulleys3"] = {
        dict = "props_misc@annesburg_coal",
        anim = "anngears03_full",
        model = "p_annpulleys03x",
    },
    ["conveyor-pulleys4"] = {
        dict = "props_misc@annesburg_coal",
        anim = "anngears04_full",
        model = "p_annpulleys04x",
    },
    ["church-bell"] = {
        dict = "props_misc@church_bells", 
        anim = "loop",
        model = "p_churchbell01x",
        bell = true
    },
    ["p_gunsmithtrapdoor01x"] = {
        dict = "script_proc@robberies@shop@rhodes@gunsmith@inside_upstairs", 
        anim = "door_loop_trapdoor",
        model = "p_gunsmithtrapdoor01x",
    },
}

["script_proc@robberies@shop@rhodes@gunsmith@inside_upstairs"] = {
    "enter_counter_register",
    "enter_counter_trapdoor",
    "exit_counter_register",
    "exit_counter_trapdoor",
    "handsup_register_door",
    "handsup_register_owner",
    "handsup_register_register",
    "handsup_register_trapdoor",
    "idle_2_register_owner",
    "idle_2_register_register",
    "idle_2_register_trapdoor",
    "inventory_loop_register",
    "inventory_loop_trapdoor",
    "open_register_2_door_cash01",
    "open_register_2_door_cash02",
    "open_register_2_door_door",
    "open_register_2_door_owner",
    "open_register_2_door_register",
    "open_register_2_door_trapdoor",
    "open_trap_p1p2_from_ai_door",
    "open_trap_p1p2_from_ai_owner",
    "open_trap_p1p2_from_ai_register",
    "open_trap_p1p2_from_ai_trapdoor",
    "open_trap_p1p2_register",
    "open_trap_p1p2_trapdoor",
    "open_trap_p1p2_v2_door",
    "open_trap_p1p2_v2_owner",
    "open_trap_p1p2_v2_register",
    "open_trap_p1p2_v2_trapdoor",
    "register_2_door_owner",
    "register_2_door_register",
    "register_2_door_trapdoor",
    "trans_2_trap_door_door",
    "trans_2_trap_door_from_ai_door",
    "trans_2_trap_door_from_ai_owner",
    "trans_2_trap_door_from_ai_register",
    "trans_2_trap_door_from_ai_trapdoor",
    "trans_2_trap_door_owner",
    "trans_2_trap_door_register",
    "trans_2_trap_door_trapdoor",
    "trap_door_line01_door",
    "base_counter_register",
    "trap_door_line01_owner",
    "base_counter_trapdoor",
    "trap_door_line01_register",
    "trap_door_line01_trapdoor",
    "trap_door_wait_register",
    "trap_door_wait_trapdoor",
    "counter_idle_register",
    "counter_idle_trapdoor",
    "walk_to_counter_owner",
    "counter_to_door_owner",
    "counter_to_door_register",
    "counter_to_door_trapdoor",
    "walk_to_counter_register",
    "walk_to_counter_trapdoor",
    "door_loop_register",
    "inventory_loop_owner",
    "inventory_loop_door",
    "door_loop_owner",
    "door_loop_door",
    "enter_player",
    "open_trap_p1p2_owner",
    "trap_door_wait_door",
    "counter_to_door_door",
    "trap_door_wait_owner",
    "counter_idle_owner",
    "counter_idle_door",
    "breakout03_trapdoor",
    "idle_2_register_door",
    "breakout03_register",
    "breakout03_owner",
    "breakout03_door",
    "open_trap_p1p2_door",
    "breakout02_trapdoor",
    "enter_counter_owner",
    "breakout02_register",
    "walk_to_counter_door",
    "breakout02_owner",
    "breakout02_door",
    "register_2_door_door",
    "breakout01_trapdoor",
    "enter_counter_door",
    "breakout01_register",
    "breakout01_owner",
    "breakout01_door",
    "base_trapdoor",
    "door_loop_trapdoor",
    "base_player",
    "base_counter_owner",
    "base_counter_door",
    "exit_counter_owner",
    "exit_counter_door",
    "enter_trapdoor",
},