Config = {}

Config.Jobs = {
    [1] = "usine",
}


Config.MsgWorking = "Appuie sur Del" -- Message de récolte
Config.MsgOpenMenu = "Appuie sur Entrer" -- Message de traitement

Config.RessourcesPointPos = vector3(2562.859, -1495.206, 46.0) -- Récolte Souffre
Config.WorkingTime = 5000
Config.DistanceToInteract = 1.5

Config.CreateFerAndLaitonPos = vector3(2317.1611, -1455.7, 47.01) -- 1 Charbon + 10 Minerai brut  = Lingot de Laiton

Config.Atelier = vector3(2361.018, -1450.258, 45.07627) -- Creer toutes les balles
Config.Assembly = vector3(2363.794, -1467.513, 45.0539) 
Config.Poudre = vector3(2366.975, -1467.534, 45.05197) 
Config.Etabli = vector3(2370.284, -1467.989, 45.04718) 


Config.AnimDict = "amb_work@world_human_hammer@table@male_a@trans"
Config.CraftAnim = {
    "base_trans_base",
}

Config.RecolteSouffreDict = 'amb_camp@prop_camp_butcher@working@deer@male_a@meat_drop@stand_exit'
Config.RecolteSouffreAnim = 'exit_front' -- A CHANGER



Config.CraftingsReceipe = {
    
['crossecattleman'] = {
    type = 'usineetabli',
    Itemtocraft = 2,
    ItemReceipe1Name = 'bois',
    ItemReceipe1Amount = 1,
    ItemReceipe2Name = 'ferpepite',
    ItemReceipe2Amount = 4,
    ItemToGive = 'crossecattleman',
    Amount = 1,
    WorkingTime = 15,
    label = 'Crosse Colt 1873',
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/wood.png', text = "Bois",count = "x1"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x4"}}
},
['crosseschoffield'] = {
    type = 'usineetabli',
    Itemtocraft = 2,
    ItemReceipe1Name = 'bois',
    ItemReceipe1Amount = 1,
    ItemReceipe2Name = 'ferpepite',
    ItemReceipe2Amount = 4,
    ItemToGive = 'crosseschoffield',
    Amount = 1,
    WorkingTime = 15,
    label = 'Crosse Smith & Wesson Model 3',
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/wood.png', text = "Bois",count = "x1"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x4"}}
},
['crossedoubleaction'] = {
    type = 'usineetabli',
    Itemtocraft = 2,
    ItemReceipe1Name = 'bois',
    ItemReceipe1Amount = 1,
    ItemReceipe2Name = 'ferpepite',
    ItemReceipe2Amount = 4,
    ItemToGive = 'crossedoubleaction',
    Amount = 1,
    WorkingTime = 15,
    label = 'Crosse 1873 Chamelot-Delvigne',
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/wood.png', text = "Bois",count = "x1"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x4"}}
},
['crosselemat'] = {
    type = 'usineetabli',
    Itemtocraft = 2,
    ItemReceipe1Name = 'bois',
    ItemReceipe1Amount = 3,
    ItemReceipe2Name = 'ferpepite',
    ItemReceipe2Amount = 5,
    ItemToGive = 'crosselemat',
    Amount = 1,
    WorkingTime = 15,
    label = 'Crosse Lemat revolver',
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/wood.png', text = "Bois",count = "x3"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x5"}}
},
['crossenavy'] = {
    type = 'usineetabli',
    Itemtocraft = 2,
    ItemReceipe1Name = 'bois',
    ItemReceipe1Amount = 3,
    ItemReceipe2Name = 'ferpepite',
    ItemReceipe2Amount = 10,
    ItemToGive = 'crossenavy',
    Amount = 1,
    WorkingTime = 15,
    label = 'Crosse Colt 1851 Navy',
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/wood.png', text = "Bois",count = "x3"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x10"}}
},
['crossevolcanic'] = {
    type = 'usineetabli',
    Itemtocraft = 2,
    ItemReceipe1Name = 'bois',
    ItemReceipe1Amount = 3,
    ItemReceipe2Name = 'ferpepite',
    ItemReceipe2Amount = 15,
    ItemToGive = 'crossevolcanic',
    Amount = 1,
    WorkingTime = 15,
    label = 'Crosse Smith and Wesson 1855',
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/wood.png', text = "Bois",count = "x3"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x15"}}
},
['crosseevans'] = {
    type = 'usineetabli',
    Itemtocraft = 2,
    ItemReceipe1Name = 'bois',
    ItemReceipe1Amount = 10,
    ItemReceipe2Name = 'ferpepite',
    ItemReceipe2Amount = 15,
    ItemToGive = 'crosseevans',
    Amount = 1,
    WorkingTime = 15,
    label = 'Crosse Evans',
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/wood.png', text = "Bois",count = "x10"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x15"}}
},
['crossecarabine'] = {
    type = 'usineetabli',
    Itemtocraft = 2,
    ItemReceipe1Name = 'bois',
    ItemReceipe1Amount = 10,
    ItemReceipe2Name = 'ferpepite',
    ItemReceipe2Amount = 15,
    ItemToGive = 'crossecarabine',
    Amount = 1,
    WorkingTime = 15,
    label = 'Crosse M1865 Spencer',
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/wood.png', text = "Bois",count = "x10"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x15"}}
},
['crosselancaster'] = {
    type = 'usineetabli',
    Itemtocraft = 2,
    ItemReceipe1Name = 'bois',
    ItemReceipe1Amount = 10,
    ItemReceipe2Name = 'ferpepite',
    ItemReceipe2Amount = 15,
    ItemToGive = 'crosselancaster',
    Amount = 1,
    WorkingTime = 15,
    label = 'Crosse Winchester 1873',
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/wood.png', text = "Bois",count = "x10"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x15"}}
},
['crosselitchfield'] = {
    type = 'usineetabli',
    Itemtocraft = 2,
    ItemReceipe1Name = 'bois',
    ItemReceipe1Amount = 10,
    ItemReceipe2Name = 'ferpepite',
    ItemReceipe2Amount = 15,
    ItemToGive = 'crosselitchfield',
    Amount = 1,
    WorkingTime = 15,
    label = 'Crosse 1860 Henry',
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/wood.png', text = "Bois",count = "x10"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x15"}}
},
['crossespringfield'] = {
    type = 'usineetabli',
    Itemtocraft = 2,
    ItemReceipe1Name = 'bois',
    ItemReceipe1Amount = 10,
    ItemReceipe2Name = 'ferpepite',
    ItemReceipe2Amount = 15,
    ItemToGive = 'crossespringfield',
    Amount = 1,
    WorkingTime = 15,
    label = 'Crosse Springfield Model 1873',
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/wood.png', text = "Bois",count = "x10"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x15"}}
},
['crosserollingblock'] = {
    type = 'usineetabli',
    Itemtocraft = 2,
    ItemReceipe1Name = 'bois',
    ItemReceipe1Amount = 10,
    ItemReceipe2Name = 'ferpepite',
    ItemReceipe2Amount = 15,
    ItemToGive = 'crosserollingblock',
    Amount = 1,
    WorkingTime = 15,
    label = 'Crosse Rolling Block',
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/wood.png', text = "Bois",count = "x10"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x15"}}
},
['crossedoublecanon'] = {
    type = 'usineetabli',
    Itemtocraft = 2,
    ItemReceipe1Name = 'bois',
    ItemReceipe1Amount = 10,
    ItemReceipe2Name = 'ferpepite',
    ItemReceipe2Amount = 10,
    ItemToGive = 'crossedoublecanon',
    Amount = 1,
    WorkingTime = 15,
    label = 'Crosse Colt 1883',
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/wood.png', text = "Bois",count = "x10"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x15"}}
},
['crossecanonscie'] = {
    type = 'usineetabli',
    Itemtocraft = 2,
    ItemReceipe1Name = 'bois',
    ItemReceipe1Amount = 3,
    ItemReceipe2Name = 'ferpepite',
    ItemReceipe2Amount = 10,
    ItemToGive = 'crossecanonscie',
    Amount = 1,
    WorkingTime = 15,
    label = 'Crosse Colt 1883 Scié',
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/wood.png', text = "Bois",count = "x3"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x10"}}
},


--Corps d'armes--
['corpsdarmecattleman'] = {
    type = 'usineetablideux',
    Itemtocraft = 4,
    ItemReceipe1Name = 'cuivrepepite',
    ItemReceipe1Amount = 20,
    ItemReceipe2Name = 'zincpepite',
    ItemReceipe2Amount = 8,
    ItemReceipe3Name = 'ferpepite',
    ItemReceipe3Amount = 2,
    ItemReceipe4Name = 'charbon',
    ItemReceipe4Amount = 1,
    ItemToGive = 'corpsdarmecattleman',
    Amount = 1,
    WorkingTime = 15,
    label = "Corps d'arme Colt 1873",
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/pepitecuivre.png', text = "Pépite de cuivre",count = "x20"}, {src = 'nui://redemrp_inventory/html/items/provision_gold_nugget.png', text = "Pépite de zinc",count = "x8"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x2"}, {src = 'nui://redemrp_inventory/html/items/rock.png', text = "Charbon",count = "x1"}}
},
['corpsdarmeschofflied'] = {
    type = 'usineetablideux',
    Itemtocraft = 4,
    ItemReceipe1Name = 'cuivrepepite',
    ItemReceipe1Amount = 25,
    ItemReceipe2Name = 'zincpepite',
    ItemReceipe2Amount = 10,
    ItemReceipe3Name = 'ferpepite',
    ItemReceipe3Amount = 4,
    ItemReceipe4Name = 'charbon',
    ItemReceipe4Amount = 1,
    ItemToGive = 'corpsdarmeschoffield',
    Amount = 1,
    WorkingTime = 15,
    label = "Corps d'arme Smith & Wesson model 3",
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/pepitecuivre.png', text = "Pépite de cuivre",count = "x25"}, {src = 'nui://redemrp_inventory/html/items/provision_gold_nugget.png', text = "Pépite de zinc",count = "x10"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x4"}, {src = 'nui://redemrp_inventory/html/items/rock.png', text = "Charbon",count = "x1"}}
},
['corpsdarmedoubleaction'] = {
    type = 'usineetablideux',
    Itemtocraft = 4,
    ItemReceipe1Name = 'cuivrepepite',
    ItemReceipe1Amount = 45,
    ItemReceipe2Name = 'zincpepite',
    ItemReceipe2Amount = 36,
    ItemReceipe3Name = 'ferpepite',
    ItemReceipe3Amount = 7,
    ItemReceipe4Name = 'charbon',
    ItemReceipe4Amount = 3,
    ItemToGive = 'corpsdarmedoubleaction',
    Amount = 1,
    WorkingTime = 15,
    label = "Corps d'arme 1873 Chamelot-Delvigne",
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/pepitecuivre.png', text = "Pépite de cuivre",count = "x45"}, {src = 'nui://redemrp_inventory/html/items/provision_gold_nugget.png', text = "Pépite de zinc",count = "x36"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x7"}, {src = 'nui://redemrp_inventory/html/items/rock.png', text = "Charbon",count = "x3"}}
},
['corpsdarmelemat'] = {
    type = 'usineetablideux',
    Itemtocraft = 4,
    ItemReceipe1Name = 'cuivrepepite',
    ItemReceipe1Amount = 90,
    ItemReceipe2Name = 'zincpepite',
    ItemReceipe2Amount = 55,
    ItemReceipe3Name = 'ferpepite',
    ItemReceipe3Amount = 20,
    ItemReceipe4Name = 'charbon',
    ItemReceipe4Amount = 10,
    ItemToGive = 'corpsdarmelemat',
    Amount = 1,
    WorkingTime = 15,
    label = "Corps d'arme Lemat Revolver",
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/pepitecuivre.png', text = "Pépite de cuivre",count = "x90"}, {src = 'nui://redemrp_inventory/html/items/provision_gold_nugget.png', text = "Pépite de zinc",count = "x55"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x20"}, {src = 'nui://redemrp_inventory/html/items/rock.png', text = "Charbon",count = "x10"}}
},
['corpsdarmenavy'] = {
    type = 'usineetablideux',
    Itemtocraft = 4,
    ItemReceipe1Name = 'cuivrepepite',
    ItemReceipe1Amount = 100,
    ItemReceipe2Name = 'zincpepite',
    ItemReceipe2Amount = 60,
    ItemReceipe3Name = 'ferpepite',
    ItemReceipe3Amount = 20,
    ItemReceipe4Name = 'charbon',
    ItemReceipe4Amount = 10,
    ItemToGive = 'corpsdarmenavy',
    Amount = 1,
    WorkingTime = 15,
    label = "Corps d'arme Colt 1851 Navy",
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/pepitecuivre.png', text = "Pépite de cuivre",count = "x100"}, {src = 'nui://redemrp_inventory/html/items/provision_gold_nugget.png', text = "Pépite de zinc",count = "x60"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x20"}, {src = 'nui://redemrp_inventory/html/items/rock.png', text = "Charbon",count = "x10"}}
},
['corpsdarmevolcanic'] = {
    type = 'usineetablideux',
    Itemtocraft = 4,
    ItemReceipe1Name = 'cuivrepepite',
    ItemReceipe1Amount = 130,
    ItemReceipe2Name = 'zincpepite',
    ItemReceipe2Amount = 60,
    ItemReceipe3Name = 'ferpepite',
    ItemReceipe3Amount = 35,
    ItemReceipe4Name = 'charbon',
    ItemReceipe4Amount = 10,
    ItemToGive = 'corpsdarmevolcanic',
    Amount = 1,
    WorkingTime = 15,
    label = "Corps d'arme Smith & Wesson 1855",
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/pepitecuivre.png', text = "Pépite de cuivre",count = "x130"}, {src = 'nui://redemrp_inventory/html/items/provision_gold_nugget.png', text = "Pépite de zinc",count = "x60"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x35"}, {src = 'nui://redemrp_inventory/html/items/rock.png', text = "Charbon",count = "x10"}}
},
['corpsdarmeevans'] = {
    type = 'usineetablideux',
    Itemtocraft = 4,
    ItemReceipe1Name = 'cuivrepepite',
    ItemReceipe1Amount = 150,
    ItemReceipe2Name = 'zincpepite',
    ItemReceipe2Amount = 70,
    ItemReceipe3Name = 'ferpepite',
    ItemReceipe3Amount = 35,
    ItemReceipe4Name = 'charbon',
    ItemReceipe4Amount = 10,
    ItemToGive = 'corpsdarmeevans',
    Amount = 1,
    WorkingTime = 15,
    label = "Corps d'arme Evans",
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/pepitecuivre.png', text = "Pépite de cuivre",count = "x150"}, {src = 'nui://redemrp_inventory/html/items/provision_gold_nugget.png', text = "Pépite de zinc",count = "x70"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x35"}, {src = 'nui://redemrp_inventory/html/items/rock.png', text = "Charbon",count = "x10"}}
},
['corpsdarmecarabine'] = {
    type = 'usineetablideux',
    Itemtocraft = 4,
    ItemReceipe1Name = 'cuivrepepite',
    ItemReceipe1Amount = 130,
    ItemReceipe2Name = 'zincpepite',
    ItemReceipe2Amount = 60,
    ItemReceipe3Name = 'ferpepite',
    ItemReceipe3Amount = 35,
    ItemReceipe4Name = 'charbon',
    ItemReceipe4Amount = 10,
    ItemToGive = 'corpsdarmecarabine',
    Amount = 1,
    WorkingTime = 15,
    label = "Corps d'arme M1865 Spencer",
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/pepitecuivre.png', text = "Pépite de cuivre",count = "x130"}, {src = 'nui://redemrp_inventory/html/items/provision_gold_nugget.png', text = "Pépite de zinc",count = "x60"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x35"}, {src = 'nui://redemrp_inventory/html/items/rock.png', text = "Charbon",count = "x10"}}
},
['corpsdarmelancaster'] = {
    type = 'usineetablideux',
    Itemtocraft = 4,
    ItemReceipe1Name = 'cuivrepepite',
    ItemReceipe1Amount = 170,
    ItemReceipe2Name = 'zincpepite',
    ItemReceipe2Amount = 90,
    ItemReceipe3Name = 'ferpepite',
    ItemReceipe3Amount = 35,
    ItemReceipe4Name = 'charbon',
    ItemReceipe4Amount = 10,
    ItemToGive = 'corpsdarmelancaster',
    Amount = 1,
    WorkingTime = 15,
    label = "Corps d'arme Winchester 1873",
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/pepitecuivre.png', text = "Pépite de cuivre",count = "x170"}, {src = 'nui://redemrp_inventory/html/items/provision_gold_nugget.png', text = "Pépite de zinc",count = "x90"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x35"}, {src = 'nui://redemrp_inventory/html/items/rock.png', text = "Charbon",count = "x10"}}
},
['corpsdarmelitchfield'] = {
    type = 'usineetablideux',
    Itemtocraft = 4,
    ItemReceipe1Name = 'cuivrepepite',
    ItemReceipe1Amount = 170,
    ItemReceipe2Name = 'zincpepite',
    ItemReceipe2Amount = 90,
    ItemReceipe3Name = 'ferpepite',
    ItemReceipe3Amount = 35,
    ItemReceipe4Name = 'charbon',
    ItemReceipe4Amount = 10,
    ItemToGive = 'corpsdarmelitchfield',
    Amount = 1,
    WorkingTime = 15,
    label = "Corps d'arme 1860 Henry",
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/pepitecuivre.png', text = "Pépite de cuivre",count = "x170"}, {src = 'nui://redemrp_inventory/html/items/provision_gold_nugget.png', text = "Pépite de zinc",count = "x90"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x35"}, {src = 'nui://redemrp_inventory/html/items/rock.png', text = "Charbon",count = "x10"}}
},
['corpsdarmespringfield'] = {
    type = 'usineetablideux',
    Itemtocraft = 4,
    ItemReceipe1Name = 'cuivrepepite',
    ItemReceipe1Amount = 180,
    ItemReceipe2Name = 'zincpepite',
    ItemReceipe2Amount = 90,
    ItemReceipe3Name = 'ferpepite',
    ItemReceipe3Amount = 35,
    ItemReceipe4Name = 'charbon',
    ItemReceipe4Amount = 10,
    ItemToGive = 'corpsdarmespringfield',
    Amount = 1,
    WorkingTime = 15,
    label = "Corps d'arme Springfield Model 1873",
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/pepitecuivre.png', text = "Pépite de cuivre",count = "x180"}, {src = 'nui://redemrp_inventory/html/items/provision_gold_nugget.png', text = "Pépite de zinc",count = "x90"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x35"}, {src = 'nui://redemrp_inventory/html/items/rock.png', text = "Charbon",count = "x10"}}
},
['corpsdarmerollingblock'] = {
    type = 'usineetablideux',
    Itemtocraft = 4,
    ItemReceipe1Name = 'cuivrepepite',
    ItemReceipe1Amount = 200,
    ItemReceipe2Name = 'zincpepite',
    ItemReceipe2Amount = 90,
    ItemReceipe3Name = 'ferpepite',
    ItemReceipe3Amount = 35,
    ItemReceipe4Name = 'charbon',
    ItemReceipe4Amount = 10,
    ItemToGive = 'corpsdarmerollingblock',
    Amount = 1,
    WorkingTime = 15,
    label = "Corps d'arme Remington Rolling Block",
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/pepitecuivre.png', text = "Pépite de cuivre",count = "x200"}, {src = 'nui://redemrp_inventory/html/items/provision_gold_nugget.png', text = "Pépite de zinc",count = "x90"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x35"}, {src = 'nui://redemrp_inventory/html/items/rock.png', text = "Charbon",count = "x10"}}
},
['corpsdarmedoublecanon'] = {
    type = 'usineetablideux',
    Itemtocraft = 4,
    ItemReceipe1Name = 'cuivrepepite',
    ItemReceipe1Amount = 90,
    ItemReceipe2Name = 'zincpepite',
    ItemReceipe2Amount = 60,
    ItemReceipe3Name = 'ferpepite',
    ItemReceipe3Amount = 25,
    ItemReceipe4Name = 'charbon',
    ItemReceipe4Amount = 10,
    ItemToGive = 'corpsdarmedoublecanon',
    Amount = 1,
    WorkingTime = 15,
    label = "Corps d'arme Colt 1883",
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/pepitecuivre.png', text = "Pépite de cuivre",count = "x90"}, {src = 'nui://redemrp_inventory/html/items/provision_gold_nugget.png', text = "Pépite de zinc",count = "x60"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x25"}, {src = 'nui://redemrp_inventory/html/items/rock.png', text = "Charbon",count = "x10"}}
},
['corpsdarmecanonscie'] = {
    type = "usineetablideux",
    Itemtocraft = 4,
    ItemReceipe1Name = 'cuivrepepite',
    ItemReceipe1Amount = 90,
    ItemReceipe2Name = 'zincpepite',
    ItemReceipe2Amount = 60,
    ItemReceipe3Name = 'ferpepite',
    ItemReceipe3Amount = 35,
    ItemReceipe4Name = 'charbon',
    ItemReceipe4Amount = 10,
    ItemToGive = 'corpsdarmecanonscie',
    Amount = 1,
    WorkingTime = 15,
    label = "Corps d'arme Colt 1883 scié",
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/pepitecuivre.png', text = "Pépite de cuivre",count = "x90"}, {src = 'nui://redemrp_inventory/html/items/provision_gold_nugget.png', text = "Pépite de zinc",count = "x60"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x35"}, {src = 'nui://redemrp_inventory/html/items/rock.png', text = "Charbon",count = "x10"}}


},
--barrillet--

['barrilletcattleman'] = {
    type = 'usineetabli',
    Itemtocraft = 3,
    ItemReceipe1Name = 'cuivrepepite',
    ItemReceipe1Amount = 10,
    ItemReceipe2Name = 'zincpepite',
    ItemReceipe2Amount = 4,
    ItemReceipe3Name = 'charbon',
    ItemReceipe3Amount = 1,
    ItemToGive = 'barrilletcattleman',
    Amount = 1,
    WorkingTime = 15,
    label = 'barrillet Colt 1873',
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/pepitecuivre.png', text = "Pépite de cuivre",count = "x10"}, {src = 'nui://redemrp_inventory/html/items/provision_gold_nugget.png', text = "Pépite de zinc",count = "x4"}, {src = 'nui://redemrp_inventory/html/items/rock.png', text = "Charbon",count = "x1"}}
},
['barrilletschoffield'] = {
    type = 'usineetabli',
    Itemtocraft = 3,
    ItemReceipe1Name = 'cuivrepepite',
    ItemReceipe1Amount = 10,
    ItemReceipe2Name = 'zincpepite',
    ItemReceipe2Amount = 4,
    ItemReceipe3Name = 'charbon',
    ItemReceipe3Amount = 1,
    ItemToGive = 'barrilletschoffield',
    Amount = 1,
    WorkingTime = 15,
    label = 'barrillet Smith & Wesson Model 3',
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/pepitecuivre.png', text = "Pépite de cuivre",count = "x10"}, {src = 'nui://redemrp_inventory/html/items/provision_gold_nugget.png', text = "Pépite de zinc",count = "x4"}, {src = 'nui://redemrp_inventory/html/items/rock.png', text = "Charbon",count = "x1"}}
},
['barrilletdoubleaction'] = {
    type = 'usineetabli',
    Itemtocraft = 4,
    ItemReceipe1Name = 'cuivrepepite',
    ItemReceipe1Amount = 15,
    ItemReceipe2Name = 'zincpepite',
    ItemReceipe2Amount = 12,
    ItemReceipe3Name = 'ferpepite',
    ItemReceipe3Amount = 1,
    ItemReceipe4Name = 'charbon',
    ItemReceipe4Amount = 3,
    ItemToGive = 'barrilletdoubleaction',
    Amount = 1,
    WorkingTime = 15,
    label = 'barrillet 1873 Chamelot-Delvigne',
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/pepitecuivre.png', text = "Pépite de cuivre",count = "x15"}, {src = 'nui://redemrp_inventory/html/items/provision_gold_nugget.png', text = "Pépite de zinc",count = "x12"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x1"}, {src = 'nui://redemrp_inventory/html/items/rock.png', text = "Charbon",count = "x3"}}
},
['barrilletlemat'] = {
    type = 'usineetabli',
    Itemtocraft = 4,
    ItemReceipe1Name = 'cuivrepepite',
    ItemReceipe1Amount = 50,
    ItemReceipe2Name = 'zincpepite',
    ItemReceipe2Amount = 15,
    ItemReceipe3Name = 'ferpepite',
    ItemReceipe3Amount = 5,
    ItemReceipe4Name = 'charbon',
    ItemReceipe4Amount = 10,
    ItemToGive = 'barrilletlemat',
    Amount = 1,
    WorkingTime = 15,
    label = 'barrillet Lemat revolver',
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/pepitecuivre.png', text = "Pépite de cuivre",count = "x50"}, {src = 'nui://redemrp_inventory/html/items/provision_gold_nugget.png', text = "Pépite de zinc",count = "x15"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x5"}, {src = 'nui://redemrp_inventory/html/items/rock.png', text = "Charbon",count = "x10"}}
},
['barrilletnavy'] = {
    type = 'usineetabli',
    Itemtocraft = 4,
    ItemReceipe1Name = 'cuivrepepite',
    ItemReceipe1Amount = 50,
    ItemReceipe2Name = 'zincpepite',
    ItemReceipe2Amount = 15,
    ItemReceipe3Name = 'ferpepite',
    ItemReceipe3Amount = 10,
    ItemReceipe4Name = 'charbon',
    ItemReceipe4Amount = 10,
    ItemToGive = 'barrilletnavy',
    Amount = 1,
    WorkingTime = 15,
    label = 'barrillet Colt 1851 Navy',
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/pepitecuivre.png', text = "Pépite de cuivre",count = "x50"}, {src = 'nui://redemrp_inventory/html/items/provision_gold_nugget.png', text = "Pépite de zinc",count = "x15"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x10"}, {src = 'nui://redemrp_inventory/html/items/rock.png', text = "Charbon",count = "x10"}}
},




--levier d'armement--
['levierdarmementvolcanic'] = {
    type = 'usineetabli',
    Itemtocraft = 4,
    ItemReceipe1Name = 'cuivrepepite',
    ItemReceipe1Amount = 90,
    ItemReceipe2Name = 'zincpepite',
    ItemReceipe2Amount = 40,
    ItemReceipe3Name = 'ferpepite',
    ItemReceipe3Amount = 20,
    ItemReceipe4Name = 'charbon',
    ItemReceipe4Amount = 10,
    ItemToGive = 'levierdarmementvolcanic',
    Amount = 1,
    WorkingTime = 15,
    label = "Levier d'armement Smith & Wesson 1855",
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/pepitecuivre.png', text = "Pépite de cuivre",count = "x90"}, {src = 'nui://redemrp_inventory/html/items/provision_gold_nugget.png', text = "Pépite de zinc",count = "x40"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x20"}, {src = 'nui://redemrp_inventory/html/items/rock.png', text = "Charbon",count = "x10"}}
},
['levierdarmementevans'] = {
    type = 'usineetabli',
    Itemtocraft = 4,
    ItemReceipe1Name = 'cuivrepepite',
    ItemReceipe1Amount = 70,
    ItemReceipe2Name = 'zincpepite',
    ItemReceipe2Amount = 30,
    ItemReceipe3Name = 'ferpepite',
    ItemReceipe3Amount = 20,
    ItemReceipe4Name = 'charbon',
    ItemReceipe4Amount = 10,
    ItemToGive = 'levierdarmementevans',
    Amount = 1,
    WorkingTime = 15,
    label = "Levier d'armement Evans",
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/pepitecuivre.png', text = "Pépite de cuivre",count = "x70"}, {src = 'nui://redemrp_inventory/html/items/provision_gold_nugget.png', text = "Pépite de zinc",count = "x30"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x20"}, {src = 'nui://redemrp_inventory/html/items/rock.png', text = "Charbon",count = "x10"}}
},
['levierdarmementcarabine'] = {
    type = 'usineetabli',
    Itemtocraft = 4,
    ItemReceipe1Name = 'cuivrepepite',
    ItemReceipe1Amount = 60,
    ItemReceipe2Name = 'zincpepite',
    ItemReceipe2Amount = 20,
    ItemReceipe3Name = 'ferpepite',
    ItemReceipe3Amount = 20,
    ItemReceipe4Name = 'charbon',
    ItemReceipe4Amount = 10,
    ItemToGive = 'levierdarmementcarabine',
    Amount = 1,
    WorkingTime = 15,
    label = "Levier d'armement M1865 Spencer",
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/pepitecuivre.png', text = "Pépite de cuivre",count = "x60"}, {src = 'nui://redemrp_inventory/html/items/provision_gold_nugget.png', text = "Pépite de zinc",count = "x20"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x20"}, {src = 'nui://redemrp_inventory/html/items/rock.png', text = "Charbon",count = "x10"}}
},
['levierdarmementlancaster'] = {
    type = 'usineetabli',
    Itemtocraft = 4,
    ItemReceipe1Name = 'cuivrepepite',
    ItemReceipe1Amount = 70,
    ItemReceipe2Name = 'zincpepite',
    ItemReceipe2Amount = 30,
    ItemReceipe3Name = 'ferpepite',
    ItemReceipe3Amount = 20,
    ItemReceipe4Name = 'charbon',
    ItemReceipe4Amount = 10,
    ItemToGive = 'levierdarmementlancaster',
    Amount = 1,
    WorkingTime = 15,
    label = "Levier d'armement Winchester 1873",
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/pepitecuivre.png', text = "Pépite de cuivre",count = "x70"}, {src = 'nui://redemrp_inventory/html/items/provision_gold_nugget.png', text = "Pépite de zinc",count = "x30"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x20"}, {src = 'nui://redemrp_inventory/html/items/rock.png', text = "Charbon",count = "x10"}}
},
['levierdarmementlitchfield'] = {
    type = 'usineetabli',
    Itemtocraft = 4,
    ItemReceipe1Name = 'cuivrepepite',
    ItemReceipe1Amount = 70,
    ItemReceipe2Name = 'zincpepite',
    ItemReceipe2Amount = 30,
    ItemReceipe3Name = 'ferpepite',
    ItemReceipe3Amount = 20,
    ItemReceipe4Name = 'charbon',
    ItemReceipe4Amount = 10,
    ItemToGive = 'levierdarmementlitchfield',
    Amount = 1,
    WorkingTime = 15,
    label = "Levier d'armement 1860 Henry",
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/pepitecuivre.png', text = "Pépite de cuivre",count = "x70"}, {src = 'nui://redemrp_inventory/html/items/provision_gold_nugget.png', text = "Pépite de zinc",count = "x30"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x20"}, {src = 'nui://redemrp_inventory/html/items/rock.png', text = "Charbon",count = "x10"}}
},
['levierdarmementspringfield'] = {
    type = 'usineetabli',
    Itemtocraft = 4,
    ItemReceipe1Name = 'cuivrepepite',
    ItemReceipe1Amount = 90,
    ItemReceipe2Name = 'zincpepite',
    ItemReceipe2Amount = 40,
    ItemReceipe3Name = 'ferpepite',
    ItemReceipe3Amount = 20,
    ItemReceipe4Name = 'charbon',
    ItemReceipe4Amount = 10,
    ItemToGive = 'levierdarmementspringfield',
    Amount = 1,
    WorkingTime = 15,
    label = "Levier d'armement Springfield Model 1873",
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/pepitecuivre.png', text = "Pépite de cuivre",count = "x90"}, {src = 'nui://redemrp_inventory/html/items/provision_gold_nugget.png', text = "Pépite de zinc",count = "x40"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x20"}, {src = 'nui://redemrp_inventory/html/items/rock.png', text = "Charbon",count = "x10"}}
},
['levierdarmementrollingblock'] = {
    type = 'usineetabli',
    Itemtocraft = 4,
    ItemReceipe1Name = 'cuivrepepite',
    ItemReceipe1Amount = 70,
    ItemReceipe2Name = 'zincpepite',
    ItemReceipe2Amount = 30,
    ItemReceipe3Name = 'ferpepite',
    ItemReceipe3Amount = 15,
    ItemReceipe4Name = 'charbon',
    ItemReceipe4Amount = 10,
    ItemToGive = 'levierdarmementrollingblock',
    Amount = 1,
    WorkingTime = 15,
    label = "Levier d'armement Rolling Block",
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/pepitecuivre.png', text = "Pépite de cuivre",count = "x70"}, {src = 'nui://redemrp_inventory/html/items/provision_gold_nugget.png', text = "Pépite de zinc",count = "x30"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x15"}, {src = 'nui://redemrp_inventory/html/items/rock.png', text = "Charbon",count = "x10"}}
},
['levierdarmementdoublecanon'] = {
    type = 'usineetabli',
    Itemtocraft = 4,
    ItemReceipe1Name = 'cuivrepepite',
    ItemReceipe1Amount = 40,
    ItemReceipe2Name = 'zincpepite',
    ItemReceipe2Amount = 20,
    ItemReceipe3Name = 'ferpepite',
    ItemReceipe3Amount = 30,
    ItemReceipe4Name = 'charbon',
    ItemReceipe4Amount = 20,
    ItemToGive = 'levierdarmementdoublecanon',
    Amount = 1,
    WorkingTime = 15,
    label = "Levier d'armement Colt 1883",
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/pepitecuivre.png', text = "Pépite de cuivre",count = "x40"}, {src = 'nui://redemrp_inventory/html/items/provision_gold_nugget.png', text = "Pépite de zinc",count = "x20"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x30"}, {src = 'nui://redemrp_inventory/html/items/rock.png', text = "Charbon",count = "x20"}}
},
['levierdarmementcanonscie'] = {
    type = 'usineetabli',
    Itemtocraft = 4,
    ItemReceipe1Name = 'cuivrepepite',
    ItemReceipe1Amount = 40,
    ItemReceipe2Name = 'zincpepite',
    ItemReceipe2Amount = 20,
    ItemReceipe3Name = 'ferpepite',
    ItemReceipe3Amount = 30,
    ItemReceipe4Name = 'charbon',
    ItemReceipe4Amount = 20,
    ItemToGive = 'levierdarmementcanonscie',
    Amount = 1,
    WorkingTime = 15,
    label = "Levier d'armement Colt 1883 Scié",
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/pepitecuivre.png', text = "Pépite de cuivre",count = "x40"}, {src = 'nui://redemrp_inventory/html/items/provision_gold_nugget.png', text = "Pépite de zinc",count = "x20"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x30"}, {src = 'nui://redemrp_inventory/html/items/rock.png', text = "Charbon",count = "x20"}}
},




----CANON----
['canoncattleman'] = {
    type = 'usineetablideux',
    Itemtocraft = 4,
    ItemReceipe1Name = 'cuivrepepite',
    ItemReceipe1Amount = 15,
    ItemReceipe2Name = 'zincpepite',
    ItemReceipe2Amount = 6,
    ItemReceipe3Name = 'ferpepite',
    ItemReceipe3Amount = 2,
    ItemReceipe4Name = 'charbon',
    ItemReceipe4Amount = 1,
    ItemToGive = 'canoncattleman',
    Amount = 1,
    WorkingTime = 15,
    label = 'Canon Colt 1873',
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/pepitecuivre.png', text = "Pépite de cuivre",count = "x15"}, {src = 'nui://redemrp_inventory/html/items/provision_gold_nugget.png', text = "Pépite de zinc",count = "x6"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x2"}, {src = 'nui://redemrp_inventory/html/items/rock.png', text = "Charbon",count = "x1"}}
},
['canonschoffield'] = {
    type = 'usineetablideux',
    Itemtocraft = 4,
    ItemReceipe1Name = 'cuivrepepite',
    ItemReceipe1Amount = 20,
    ItemReceipe2Name = 'zincpepite',
    ItemReceipe2Amount = 8,
    ItemReceipe3Name = 'ferpepite',
    ItemReceipe3Amount = 4,
    ItemReceipe4Name = 'charbon',
    ItemReceipe4Amount = 1,
    ItemToGive = 'canonschoffield',
    Amount = 1,
    WorkingTime = 15,
    label = 'Canon Smith & Wesson Model 3',
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/pepitecuivre.png', text = "Pépite de cuivre",count = "x20"}, {src = 'nui://redemrp_inventory/html/items/provision_gold_nugget.png', text = "Pépite de zinc",count = "x8"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x4"}, {src = 'nui://redemrp_inventory/html/items/rock.png', text = "Charbon",count = "x1"}}
},
['canondoubleaction'] = {
    type = 'usineetablideux',
    Itemtocraft = 4,
    ItemReceipe1Name = 'cuivrepepite',
    ItemReceipe1Amount = 30,
    ItemReceipe2Name = 'zincpepite',
    ItemReceipe2Amount = 24,
    ItemReceipe3Name = 'ferpepite',
    ItemReceipe3Amount = 4,
    ItemReceipe4Name = 'charbon',
    ItemReceipe4Amount = 3,
    ItemToGive = 'canondoubleaction',
    Amount = 1,
    WorkingTime = 15,
    label = 'Canon 1873 Chamelot-Delvigne',
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/pepitecuivre.png', text = "Pépite de cuivre",count = "x30"}, {src = 'nui://redemrp_inventory/html/items/provision_gold_nugget.png', text = "Pépite de zinc",count = "x24"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x4"}, {src = 'nui://redemrp_inventory/html/items/rock.png', text = "Charbon",count = "x3"}}
},
['canonlemat'] = {
    type = 'usineetablideux',
    Itemtocraft = 4,
    ItemReceipe1Name = 'cuivrepepite',
    ItemReceipe1Amount = 60,
    ItemReceipe2Name = 'zincpepite',
    ItemReceipe2Amount = 30,
    ItemReceipe3Name = 'ferpepite',
    ItemReceipe3Amount = 25,
    ItemReceipe4Name = 'charbon',
    ItemReceipe4Amount = 10,
    ItemToGive = 'canonlemat',
    Amount = 1,
    WorkingTime = 15,
    label = 'Canon Lemat Revolver',
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/pepitecuivre.png', text = "Pépite de cuivre",count = "x60"}, {src = 'nui://redemrp_inventory/html/items/provision_gold_nugget.png', text = "Pépite de zinc",count = "x30"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x25"}, {src = 'nui://redemrp_inventory/html/items/rock.png', text = "Charbon",count = "x10"}}
},
['canonnavy'] = {
    type = 'usineetablideux',
    Itemtocraft = 4,
    ItemReceipe1Name = 'cuivrepepite',
    ItemReceipe1Amount = 100,
    ItemReceipe2Name = 'zincpepite',
    ItemReceipe2Amount = 35,
    ItemReceipe3Name = 'ferpepite',
    ItemReceipe3Amount = 30,
    ItemReceipe4Name = 'charbon',
    ItemReceipe4Amount = 10,
    ItemToGive = 'canonnavy',
    Amount = 1,
    WorkingTime = 15,
    label = 'Canon Colt 1851 Navy',
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/pepitecuivre.png', text = "Pépite de cuivre",count = "x100"}, {src = 'nui://redemrp_inventory/html/items/provision_gold_nugget.png', text = "Pépite de zinc",count = "x35"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x30"}, {src = 'nui://redemrp_inventory/html/items/rock.png', text = "Charbon",count = "x10"}}
},
['canonvolcanic'] = {
    type = 'usineetablideux',
    Itemtocraft = 4,
    ItemReceipe1Name = 'cuivrepepite',
    ItemReceipe1Amount = 80,
    ItemReceipe2Name = 'zincpepite',
    ItemReceipe2Amount = 30,
    ItemReceipe3Name = 'ferpepite',
    ItemReceipe3Amount = 20,
    ItemReceipe4Name = 'charbon',
    ItemReceipe4Amount = 10,
    ItemToGive = 'canonvolcanic',
    Amount = 1,
    WorkingTime = 15,
    label = 'Canon Smith & Wesson 1855',
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/pepitecuivre.png', text = "Pépite de cuivre",count = "x80"}, {src = 'nui://redemrp_inventory/html/items/provision_gold_nugget.png', text = "Pépite de zinc",count = "x30"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x20"}, {src = 'nui://redemrp_inventory/html/items/rock.png', text = "Charbon",count = "x10"}}
},
['canonevans'] = {
    type = 'usineetablideux',
    Itemtocraft = 4,
    ItemReceipe1Name = 'cuivrepepite',
    ItemReceipe1Amount = 80,
    ItemReceipe2Name = 'zincpepite',
    ItemReceipe2Amount = 30,
    ItemReceipe3Name = 'ferpepite',
    ItemReceipe3Amount = 20,
    ItemReceipe4Name = 'charbon',
    ItemReceipe4Amount = 10,
    ItemToGive = 'canonevans',
    Amount = 1,
    WorkingTime = 15,
    label = 'Canon Evans',
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/pepitecuivre.png', text = "Pépite de cuivre",count = "x80"}, {src = 'nui://redemrp_inventory/html/items/provision_gold_nugget.png', text = "Pépite de zinc",count = "x30"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x20"}, {src = 'nui://redemrp_inventory/html/items/rock.png', text = "Charbon",count = "x10"}}
},
['canoncarabine'] = {
    type = 'usineetablideux',
    Itemtocraft = 4,
    ItemReceipe1Name = 'cuivrepepite',
    ItemReceipe1Amount = 110,
    ItemReceipe2Name = 'zincpepite',
    ItemReceipe2Amount = 40,
    ItemReceipe3Name = 'ferpepite',
    ItemReceipe3Amount = 20,
    ItemReceipe4Name = 'charbon',
    ItemReceipe4Amount = 10,
    ItemToGive = 'canoncarabine',
    Amount = 1,
    WorkingTime = 15,
    label = 'Canon M1865 Spencer ',    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/pepitecuivre.png', text = "Pépite de cuivre",count = "x110"}, {src = 'nui://redemrp_inventory/html/items/provision_gold_nugget.png', text = "Pépite de zinc",count = "x40"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x20"}, {src = 'nui://redemrp_inventory/html/items/rock.png', text = "Charbon",count = "x10"}}
},
['canonlancaster'] = {
    type = 'usineetablideux',
    Itemtocraft = 4,
    ItemReceipe1Name = 'cuivrepepite',
    ItemReceipe1Amount = 110,
    ItemReceipe2Name = 'zincpepite',
    ItemReceipe2Amount = 40,
    ItemReceipe3Name = 'ferpepite',
    ItemReceipe3Amount = 20,
    ItemReceipe4Name = 'charbon',
    ItemReceipe4Amount = 10,
    ItemToGive = 'canonlancaster',
    Amount = 1,
    WorkingTime = 15,
    label = 'Canon Winchester 1873',
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/pepitecuivre.png', text = "Pépite de cuivre",count = "x110"}, {src = 'nui://redemrp_inventory/html/items/provision_gold_nugget.png', text = "Pépite de zinc",count = "x40"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x20"}, {src = 'nui://redemrp_inventory/html/items/rock.png', text = "Charbon",count = "x10"}}
},
['canonlitchfield'] = {
    type = 'usineetablideux',
    Itemtocraft = 4,
    ItemReceipe1Name = 'cuivrepepite',
    ItemReceipe1Amount = 110,
    ItemReceipe2Name = 'zincpepite',
    ItemReceipe2Amount = 40,
    ItemReceipe3Name = 'ferpepite',
    ItemReceipe3Amount = 20,
    ItemReceipe4Name = 'charbon',
    ItemReceipe4Amount = 10,
    ItemToGive = 'canonlitchfield',
    Amount = 1,
    WorkingTime = 15,
    label = 'Canon 1860 Henry',
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/pepitecuivre.png', text = "Pépite de cuivre",count = "x110"}, {src = 'nui://redemrp_inventory/html/items/provision_gold_nugget.png', text = "Pépite de zinc",count = "x40"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x20"}, {src = 'nui://redemrp_inventory/html/items/rock.png', text = "Charbon",count = "x10"}}
},
['canonspringfield'] = {
    type = 'usineetablideux',
    Itemtocraft = 4,
    ItemReceipe1Name = 'cuivrepepite',
    ItemReceipe1Amount = 130,
    ItemReceipe2Name = 'zincpepite',
    ItemReceipe2Amount = 70,
    ItemReceipe3Name = 'ferpepite',
    ItemReceipe3Amount = 30,
    ItemReceipe4Name = 'charbon',
    ItemReceipe4Amount = 10,
    ItemToGive = 'canonspringfield',
    Amount = 1,
    WorkingTime = 15,
    label = 'Canon Springfield Model 1873',
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/pepitecuivre.png', text = "Pépite de cuivre",count = "x130"}, {src = 'nui://redemrp_inventory/html/items/provision_gold_nugget.png', text = "Pépite de zinc",count = "x70"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x30"}, {src = 'nui://redemrp_inventory/html/items/rock.png', text = "Charbon",count = "x10"}}
},
['canonrollingblock'] = {
    type = 'usineetablideux',
    Itemtocraft = 4,
    ItemReceipe1Name = 'cuivrepepite',
    ItemReceipe1Amount = 130,
    ItemReceipe2Name = 'zincpepite',
    ItemReceipe2Amount = 80,
    ItemReceipe3Name = 'ferpepite',
    ItemReceipe3Amount = 35,
    ItemReceipe4Name = 'charbon',
    ItemReceipe4Amount = 10,
    ItemToGive = 'canonrollingblock',
    Amount = 1,
    WorkingTime = 15,
    label = 'Canon Remington Rolling Block',
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/pepitecuivre.png', text = "Pépite de cuivre",count = "x130"}, {src = 'nui://redemrp_inventory/html/items/provision_gold_nugget.png', text = "Pépite de zinc",count = "x80"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x35"}, {src = 'nui://redemrp_inventory/html/items/rock.png', text = "Charbon",count = "x10"}}
},
['canondoublecanon'] = {
    type = 'usineetablideux',
    Itemtocraft = 4,
    ItemReceipe1Name = 'cuivrepepite',
    ItemReceipe1Amount = 100,
    ItemReceipe2Name = 'zincpepite',
    ItemReceipe2Amount = 60,
    ItemReceipe3Name = 'ferpepite',
    ItemReceipe3Amount = 40,
    ItemReceipe4Name = 'charbon',
    ItemReceipe4Amount = 20,
    ItemToGive = 'canondoublecanon',
    Amount = 1,
    WorkingTime = 15,
    label = 'Canon Colt 1883',
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/pepitecuivre.png', text = "Pépite de cuivre",count = "x100"}, {src = 'nui://redemrp_inventory/html/items/provision_gold_nugget.png', text = "Pépite de zinc",count = "x60"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x40"}, {src = 'nui://redemrp_inventory/html/items/rock.png', text = "Charbon",count = "x20"}}
},
['canoncanonscie'] = {
    type = 'usineetablideux',
    Itemtocraft = 4,
    ItemReceipe1Name = 'cuivrepepite',
    ItemReceipe1Amount = 70,
    ItemReceipe2Name = 'zincpepite',
    ItemReceipe2Amount = 30,
    ItemReceipe3Name = 'ferpepite',
    ItemReceipe3Amount = 40,
    ItemReceipe4Name = 'charbon',
    ItemReceipe4Amount = 20,
    ItemToGive = 'canoncanonscie',
    Amount = 1,
    WorkingTime = 15,
    label = 'Canon Colt 1883 Scié',
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/pepitecuivre.png', text = "Pépite de cuivre",count = "x70"}, {src = 'nui://redemrp_inventory/html/items/provision_gold_nugget.png', text = "Pépite de zinc",count = "x30"}, {src = 'nui://redemrp_inventory/html/items/cannabis.png', text = "Pépite de fer",count = "x40"}, {src = 'nui://redemrp_inventory/html/items/rock.png', text = "Charbon",count = "x20"}}
},

-------- BALLES ---------

['gunpowder'] = {
    type = 'usinepoudre',
    Itemtocraft = 2,
    ItemReceipe1Name = 'charbon',
    ItemReceipe1Amount = 1,
    ItemReceipe2Name = 'souffre',
    ItemReceipe2Amount = 1,
    ItemToGive = 'gunpowder',
    Amount = 1,
    WorkingTime = 1,
    label = 'Poudre à canon',
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/rock.png', text = "Charbon",count = "x1"}, {src = 'nui://redemrp_inventory/html/items/collector_fossil_stone.png', text = "Souffre",count = "x1"}}
},
['douille'] = {
    type = 'usineassemblage',
    Itemtocraft = 2,
    ItemReceipe1Name = 'cuivrepepite',
    ItemReceipe1Amount = 1,
    ItemReceipe2Name = 'plombpepite',
    ItemReceipe2Amount = 1,
    ItemToGive = 'douille',
    Amount = 1,
    WorkingTime = 1,
    label = 'Douille',
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/pepitecuivre.png', text = "Pépite de cuivre",count = "x1"}, {src = 'nui://redemrp_inventory/html/items/silverore.png', text = "Pépite de plomb",count = "x1"}}
},
['ammo_revolver'] = {
    type = 'usineassemblage',
    Itemtocraft = 2,
    ItemReceipe1Name = 'gunpowder',
    ItemReceipe1Amount = 1,
    ItemReceipe2Name = 'douille',
    ItemReceipe2Amount = 1,
    ItemToGive = 'ammo_revolver',
    Amount = 10,
    WorkingTime = 1,
    label = 'Balles de Revolver',
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/cocaine.png', text = "Poudre à canon",count = "x1"}, {src = 'nui://redemrp_inventory/html/items/upgrade_pouch_ammo.png', text = "Douille",count = "x1"}}
},
['ammo_pistolet'] = {
    type = 'usineassemblage',
    Itemtocraft = 2,
    ItemReceipe1Name = 'gunpowder',
    ItemReceipe1Amount = 1,
    ItemReceipe2Name = 'douille',
    ItemReceipe2Amount = 1,
    ItemToGive = 'ammo_pistolet',
    Amount = 10,
    WorkingTime = 1,
    label = 'Balles de Pistolet',
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/cocaine.png', text = "Poudre à canon",count = "x1"}, {src = 'nui://redemrp_inventory/html/items/upgrade_pouch_ammo.png', text = "Douille",count = "x1"}}
},
['ammo_repeater'] = {
    type = 'usineassemblage',
    Itemtocraft = 2,
    ItemReceipe1Name = 'gunpowder',
    ItemReceipe1Amount = 2,
    ItemReceipe2Name = 'douille',
    ItemReceipe2Amount = 1,
    ItemToGive = 'ammo_repeater',
    Amount = 10,
    WorkingTime = 1,
    label = 'Balles de Carabine',
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/cocaine.png', text = "Poudre à canon",count = "x2"}, {src = 'nui://redemrp_inventory/html/items/upgrade_pouch_ammo.png', text = "Douille",count = "x1"}}
},
['ammo_shotgun'] = {
    type = 'usineassemblage',
    Itemtocraft = 2,
    ItemReceipe1Name = 'gunpowder',
    ItemReceipe1Amount = 2,
    ItemReceipe2Name = 'douille',
    ItemReceipe2Amount = 1,
    ItemToGive = 'ammo_shotgun',
    Amount = 10,
    WorkingTime = 1,
    label = 'Chevrotine',
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/cocaine.png', text = "Poudre à canon",count = "x2"}, {src = 'nui://redemrp_inventory/html/items/upgrade_pouch_ammo.png', text = "Douille",count = "x1"}}
},
['ammo_rifle'] = {
    type = 'usineassemblage',
    Itemtocraft = 2,
    ItemReceipe1Name = 'gunpowder',
    ItemReceipe1Amount = 3,
    ItemReceipe2Name = 'douille',
    ItemReceipe2Amount = 1,
    ItemToGive = 'ammo_rifle',
    Amount = 10,
    WorkingTime = 1,
    label = 'Balles de fusil',
    descriptionimages = {{src = 'nui://redemrp_inventory/html/items/cocaine.png', text = "Poudre à canon",count = "x3"}, {src = 'nui://redemrp_inventory/html/items/upgrade_pouch_ammo.png', text = "Douille",count = "x1"}}
},
}